getporter/porter

Makefile
This variable is used in the `test-cli` target but didn't have a default set...
=> fix(Makefile): add REGISTRY default

docs/config.toml, docs/content/architecture.md, docs/content/docs.md, docs/content/mixin-architecture.md, docs/content/mixin-dev-guide.md, docs/themes/porter/layouts/index.html, docs/themes/porter/layouts/partials/header.html, docs/themes/porter/layouts/partials/offcanvas.html, docs/themes/porter/layouts/partials/sidebar.html
This links to the new docs written in #117 and #120.
Preview available at:
* Overview Pages
* https://deploy-preview-126--porter.netlify.com/architecture/
* https://deploy-preview-126--porter.netlify.com/mixin-dev-guide/
* https://deploy-preview-126--porter.netlify.com/build-image/
* https://deploy-preview-126--porter.netlify.com/mixin-architecture/
=> Link new docs

pkg/porter/create.go
The verb should indicate that we are performing the action now. There is no turning back. dah duh DUM! 😀
=> Fix typo in porter create

cmd/exec/main.go, cmd/exec/upgrade.go, pkg/config/manifest.go, pkg/config/manifest_test.go, pkg/mixin/exec/upgrade.go
Adds `upgrade` action support to porter (and the `exec` mixin).
Closes https://github.com/deislabs/porter/issues/123
=> feat(*): add upgrade action support

CONTRIBUTING.md
Add a tip to the contributing guide on when an issue should be created and collaborated upon before submitting a pull request.
=> Explain when to create issues before a PR

CONTRIBUTING.md, Makefile
The install target dumps the bin into ~/.porter and symlinks it to /usr/local/bin.
Note that this doesn't work with porter until #139 is merged.
=> Add install target

pkg/config/config.go, pkg/config/config_test.go
When someone symlinks /usr/local/bin/porter from ~/.porter/porter, we need to handle that properly
so that we can still find the mixins and other assets in the original directory.
Also cache the resolved PORTER_HOME so we don't have to do that more than once.
=> Resolve PORTER_HOME when it's symlinked

pkg/config/manifest.go, pkg/config/manifest_test.go, pkg/config/testdata/slice-test.yaml
This PR updates how we handle slice elements for doing parameter/credential/ouput sourcing.
We probably should think about revisiting the entire process for this in the future.
In summary, we are using reflectwalk to handle walking the manifest. This involves handling a couple
call backs, notably "SliceElement" and "MapElement". The Slice Element assumed that it would see something
of the form source: <x.y.z> as a string. In reality, if that's not wrapped in quote, Go and YAML see that
as a Map, but the map callback doesn't get called to handle that. This was resulting in the block not getting
rewritten and the exec mixin was exploding (probably any would have). This PR updates the logic of the slice elem processing to check and see if it's a map and handle it in a similar manner to a top …
=> Enhances how we're handling sourcing

README.md, docs/content/quickstart.md
Closes #144.
Was trying out Porter+Duffle, added a few things to the readme that would have helped me to know in advance.
I'm not 100% sure about the accuracy of the "Running your installer using Duffle" section I added, maybe you can clarify. Still not fully clear how the two tools are designed to play together.
=> Add quickstart and install to readme

pkg/porter/build.go, pkg/porter/build_test.go
Resolves https://github.com/deislabs/porter/issues/111
/cc @ryanmoran
=> Prints generated Dockerfile lines nicely

build/testdata/bundles/wordpress/porter.yaml
When we added in required params, it found a bug in our integration tests. We had underscores instead of hyphens in the parameter names when overriding the default values of parameters in a dependent bundle. So the logic for required parameters was kicking in.
=> Fix integration tests for required params

scripts/install/install-windows.ps1
The mixin runtimes are linux amd64 and shouldn't use the .exe file extension.
Fixes #188
=> Don't use .exe for mixin runtimes

Makefile, pkg/config/config.go, pkg/porter/build.go, pkg/porter/build_test.go
When we first wrote porter, we said "Maybe it would make our life easier to treat porter itself as a mixin?!" Well, it makes life harder now. So this ensures that porter is built to the root of bin, and isn't treated _exactly_ the same as other mixins anymore.
I didn't tackle the mixins.mk file because a few small changes to the location of the binary was enough to get it working for now however.
=> Porter is not a mixin

CONTRIBUTING.md, Makefile
By default when you do a `make build` it uses the latest tagged builds of other mixins. If a mixin is "in tree" like the exec mixin however, then you are getting a canary build of it.
This flips the default to `canary`, and then also make it possible to change the tag that it uses, so someone could use `latest` or a particular tagged version instead.
=> Make it easier to try out canary mixins

CONTRIBUTING.md
To make life easier for people, good first issue and help wanted no longer overlap. I've explained how they work in the contributing guide and link to a search against our repo for them. They are filtered by backlog so that they don't pick up issues that people are working on already.
I was going to link to a waffle query, but there's a bug (or misunderstanding) that I'm working with them on. Waffle would be better because it can do a cross repo query more easily.
=> Help people find good first issues

Makefile, pkg/config/config.go
* Put the go:generate directive at the top of any file that has a box
* The build runs a blanket go generate ./... so that we don't need to figure out which subpackages need to run packr2
* I did tests and swapping go build with packr2 build wasn't sufficient, it missed boxes, like pkg/config.
* Yes, this leaves *-packr.go files around, but at least we ignore them now and don't check them in. Hopefully it's not a problem.
This _isn't_ part of the mega PR of doom. 😀  Just general housekeeping. 
Closes #193
=> Use go generate with packr

CONTRIBUTING.md
I chatted with waffle and they helped me figure out a workaround since you can't filter based on the reserved labels (like backlog).
This is better than the other links because it lets us search across multiple repos at the same time more easily.
Don't merge this until #146 merges so I don't have to rebase it again please! 😀
=> Search waffle board for good first issues

docs/content/design/kubernetes-mixin.md
This adds a design document to the docs/ dir for the Kubernetes mixin. The mixin will use `kubectl`. Doc defines parameters available and what it will do at build time along with some basic info on how someone would supply manifests. 
Closes #185
=> Adding design document for kubernetes mixin

pkg/config/actions.go, pkg/exec/schema/exec.json, pkg/exec/testdata/schema.json, pkg/porter/schema.go, pkg/porter/schema_test.go, pkg/porter/testdata/schema.json
Closes #181 
Looking at this makes me wonder if I'm going about merging json schema documents into a single document the hard way / wrong way (because the tricks* that one would use to reduce duplication don't work with how I'm doing the merge). Unless someone knows the right way, right now, I'm hoping we can merge this and revisit later. Let me know what you think though.
\* By tricks, I mean what I was immediately tempted to do in this PR was to add a definition once for an exec step and then reference it in each action. However the way schemas from mixins are merged _right now_ by porter, is to only grab the action from the schema and incorporate it into the final schema document. I think we'd need a second pass to figure out the right way (or if there isn't a right way, a more robust …
=> Complete the exec schema command

mixin.mk
This snuck in on a merge but wasn't supposed to be there now that we use go generate.
=> Remove extra call to packr2 build

Makefile
This covers if you run just the runtime target, it ensures that the `go generate` step is executed, refreshing the packr data.
=> Require generate for the runtime target 

Makefile, mixin.mk, scripts/install/install-linux.sh, scripts/install/install-mac.sh, scripts/install/install-windows.ps1
* Fix install script for non-latest version 
* Fix where porter is built and published
=> Fix canary install

cmd/exec/main.go, pkg/exec/exec.go, pkg/exec/exec_test.go, pkg/exec/install.go, pkg/exec/install_test.go, pkg/exec/testdata/exec_input.yaml, pkg/mixin/runner.go, pkg/mixin/testdata/exec_input.yaml, pkg/porter/build.go, pkg/porter/run.go, pkg/porter/run_test.go
```
install:
- exec:
description: hello world
```
When sending steps to a mixin, provide context by wrapping them in the containing action (e.g. install, uninstall) so that the mixins can validate them against their schemas without having to maintain a
separate set of schema per action. This also will set us up for when `mixin build` will send a list of steps per action to validate.
This _should_ have been in #212 but ... wasn't. 😊 This also fixes the integration tests on master.
=>  Wrap steps in the containing action

scripts/install/install-windows.ps1
When updating a Windows install, the PowerShell script emits a lot of scary red error text before the discreet few lines about successfully installing.  This turns out to be just `mkdir` saying that the directories already exist and all is well.  This PR tells `mkdir` not to complain about directories already existing.
=> Suppress mkdir 'directory exists' output in Windows install

Makefile, cmd/kubernetes/build.go, cmd/kubernetes/install.go, cmd/kubernetes/main.go, cmd/kubernetes/schema.go, cmd/kubernetes/uninstall.go, cmd/kubernetes/upgrade.go, cmd/kubernetes/version.go, docs/content/design/kubernetes-mixin.md, pkg/kubernetes/build.go, pkg/kubernetes/helpers.go, pkg/kubernetes/install.go, pkg/kubernetes/install_test.go, pkg/kubernetes/kubernetes.go, pkg/kubernetes/schema.go, pkg/kubernetes/schema/kubernetes.json, pkg/kubernetes/schema_test.go, pkg/kubernetes/step.go, pkg/kubernetes/testdata/install-input-bad-outputs.yaml, pkg/kubernetes/testdata/install-input-bad-wait-flag.yaml, pkg/kubernetes/testdata/install-input-no-manifests.yaml, pkg/kubernetes/testdata/install-input.yaml, pkg/kubernetes/testdata/schema.json, pkg/kubernetes/testdata/uninstall-input.yaml, pkg/kubernetes/testdata/upgrade-input.yaml, pkg/kubernetes/uninstall.go, pkg/kubernetes/uninstall_test.go, pkg/kubernetes/upgrade.go, pkg/kubernetes/upgrade_test.go, pkg/kubernetes/version.go
This PR adds a Kubernetes mixin. It updates the design doc a little to reflect a couple of
param changes across the three verbs and harmonizes things using camelCase naming per the
[style guide](https://google.github.io/styleguide/jsoncstyleguide.xml?showone=Property_Name_Format#Property_Name_Format) from the GOOG.
Closes #82
=> Adding THE KUBERNETES MIXIN

cmd/porter/bundle.go, cmd/porter/bundle_test.go, cmd/porter/main.go, cmd/porter/main_test.go, pkg/parameters/parameters.go, pkg/parameters/parameters_test.go, pkg/porter/install.go, pkg/porter/install_test.go
This is the skeleton for the install command.
```
$ porter bundle install --help
Install a bundle
Usage:
porter install [flags]
Examples:
porter install
porter install --insecure
porter install --file myapp/bundle.json
porter install --name MyAppInDev
porter install --param-file base-values.txt --param-file dev-values.txt --param test-mode=true --param header-color=blue
porter install --cred azure --cred kubernetes
Flags:
-c, --cred strings         Credential to use when installing the bundle. May be either a named set of credentials or a filepath.
-f, --file string          Path to the CNAB definition to install (default "bundle.json")
-h, --help                 help for install
--insecure             Allow installing untrusted bundles
--name string          Name of the claim, defaults …
```
=> Add porter install command

pkg/config/manifest.go, pkg/porter/bundle.go
We were always writing out some bundle fields, like both path and the environment variable when it's always an either/or situation with those fields.
=> Omit empty bundle fields

pkg/porter/build.go, pkg/porter/build_test.go
This will let us handoff a --debug flag from porter install into the bundle without the user having to manually specify the parameter.
So the user can run `porter install --debug` and porter will handle automatically turning on the porter-debug parameter when it executes the bundle, and then `porter run` will pick it up and bind its `--debug` flag to that automatically.
This is just the first step of defining the parameter for all porter built bundles.
=> Inject porter-debug param into all bundles

cmd/porter/run.go, pkg/config/config.go, pkg/porter/run.go, pkg/porter/run_test.go
Look for the new porter-debug parameter that are included in porter bundles now and use it to default the porter run --debug flag.
=> Default --debug to the porter-debug parameter at runtime

examples/azure-mysql-wordpress/porter.yaml
Previously, installing this bundle would most definitely result in an error, as the server name was hard-coded.  The ARM deployment error would look something like:
```
Error: error deploying "mysql-azure-porter-demo-wordpress" in resource group "porter-test": error while waiting for deployment to complete: Code="DeploymentFailed" Message="At least one resource deployment operation failed. Please list deployment operations for details. Please see https://aka.ms/arm-debug for usage details." Details=[{"code":"BadRequest","message":"{\r\n  \"error\": {\r\n    \"code\": \"ServerNameAlreadyExists\",\r\n    \"message\": \"Specified server name is already used.\"\r\n  }\r\n}"}]
```
(tl;dr: ` \"message\": \"Specified server name is already used.\"`)
Therefore, in this PR, I propose to not only …
=> feat(examples): make mysql server name a required param

cmd/porter/bundle.go, pkg/porter/install.go, pkg/porter/install_test.go, scripts/test/test-hello.sh, scripts/test/test-wordpress.sh
This finishes up the work of getting `porter install --debug` hooked up completely between the client side and the runtime (inside the bundle) via a CNAB parameter. Check out the output from our test-cli to see that now when we run our integration tests we get debug output from inside the bundle! 🎉
=> Default the porter-debug flag using --debug

build/testdata/bundles/wordpress/porter.yaml, docs/content/authoring-bundles.md, examples/azure-mysql-wordpress/porter.yaml, pkg/cnab/provider/install.go, pkg/cnab/provider/uninstall.go, pkg/config/manifest.go, pkg/config/manifest_test.go, pkg/context/context.go, pkg/kubernetes/testdata/uninstall-input.yaml, pkg/mixin/runner_test.go, pkg/porter/build.go, pkg/porter/parameters.go, pkg/porter/run.go, scripts/test/test-wordpress.sh
Mask values in console output if value is:
- a credential
- an output
- a parameter if designated as sensitive
Implements https://github.com/deislabs/porter/issues/132
=> feat(*): mask sensitive values in console output

pkg/parameters/parameters.go, pkg/parameters/parameters_test.go
I wrote this code for svcat, and then it was donated to service catalog, but it is my copyright. So no need for those headers.
=> Remove copyright headers from params package

build/testdata/bundles/mysql/porter.yaml, build/testdata/bundles/wordpress/porter.yaml, scripts/test/test-hello.sh, scripts/test/test-terraform.sh, scripts/test/test-wordpress.sh
This should let the CI tests run concurrently without rando failing. The other bundles don't have any global state so they don't need to be modified.
* The k8s related bundles install into a new namespace per test run
* The test now run uninstall at the end of the test run to cleanup after themselves
Closes #215
Closes #268
=> Fix CI test runs so they don't step on each other

build/testdata/bundles/mysql/porter.yaml, scripts/test/test-wordpress.sh
helm release names have to be unique for the cluster, not just the namespace. Live 'n learn. 😀 
I also realized that I wasn't deleting the namespace at the end of the test run (I thought Helm did that for me if it made it). So this PR is essentially an homage to me not understanding Helm.
=> Use unique helm release names per test run

scripts/test/test-terraform.sh
Closes https://github.com/deislabs/porter-terraform/issues/8
Note: full fix included the following changes that slipped into a previous PR: https://github.com/deislabs/porter/pull/275/files#diff-6179e983ed8dc381b341cb64ef9c5519
=> fix(test-terraform.sh): pass in param on uninstall

azure-pipelines.yml
Don't double test/publish since brigade does our main build now. Later on we will add agents for windows/mac and we can test out our other install scripts after we prove out testing the linux script first.
=> Only test the install script on Azure Devops

Makefile, docs/content/mixin-distribution.md, mixin.mk, pkg/mixin/provider/install.go, pkg/mixin/provider/install_test.go
Instead of requiring the runtime binary for the mixin to be uploaded as foo-runtime-linux-amd64, allow the client mixin for linux, which is foo-linux-amd64, to be reused as there is no difference.
This sets us up anyway for when porter needs to support a customizable runtime image that could be a different os/arch.
Note: This doesn't change the name of the file on the filesystem, just what we require the mixin author to upload it as.
* generate filenames that match the new format in the porter repo
* install using porter mixin install
* consolidate targets for the internal / external mixins
After this PR, I'll update the azure, helm, and terraform repos, and then all of the mixins will have done a canary publish with the new naming conventiong
=> Do not encode -runtime into mixin download filename

cmd/porter/helptext/usage.txt, cmd/porter/main.go
* Fix the template to work for resources nested at lower levels, like
porter mixin feed, where feed is a resource.
* Use go functions in the template to decide whether or not to show/hide
a section or a command instead of template conditionals
* Do not show the help command itself
* Show commands (like install) before aliased commands or meta commands (like version) which aren't as common/important
=> Improve helptext template

pkg/config/manifest.go, pkg/config/manifest_test.go
This enhancement came about as I wrote a bundle that had a use for passing the bundle name to a mixin action (via templating in the porter manifest).
If this feature gets the go ahead, do we also want to add similar for a dependency bundle name, such that one could also reference/interpolate `bundle.dependency.name` at some point in a porter manifest?
=> feat(manifest): enable bundle name interpolation

scripts/install/install-mac.sh
This PR shows users the explicit command to add `$PORTER_HOME` to their path.
=> scripts/install: make exporting easier for users

scripts/install/install-linux.sh, scripts/install/install-mac.sh, scripts/install/install-windows.ps1
Add instructions to the remaining install scripts for how to add porter to the path. Also fixed a bash escape goof, so that the variable name, instead of the contents, are printed out for the user to copy.
This is a follow-up to #281.
=> Show how to add porter to the path in install scripts

scripts/install/install-linux.sh, scripts/install/install-mac.sh, scripts/install/install-windows.ps1
* Use `porter mixin install` to install the default set of mixins
* Use new filename for runtime in install script, we now publish using `porter-linux-amd64` instead of `porter-runtime-linux-amd64`
* Refresh script a bit, it was still making a templates directory, putting porter in a mixins directory, etc.
=> Install mixins using new install command

cmd/porter/mixins.go, mixin.mk, pkg/mixin/feed/feed.go, pkg/mixin/feed/generate.go, pkg/mixin/feed/generate_test.go, pkg/mixin/feed/template.go, pkg/mixin/feed/template_test.go, pkg/mixin/feed/templates/atom-template.xml, pkg/mixin/feed/testdata/atom-template.xml, pkg/mixin/feed/testdata/atom.xml, pkg/porter/mixins.go
This adds two commands to porter as a build up to supporting mixin feeds. All alone they aren't really enough to add new docs or anything yet though.
Note: This doesn't update an existing atom.xml file yet. I plan on doing that in a follow-up PR.
```console
$ porter mixins feed template --help
Create an atom feed template in the current directory
Usage:
porter mixins feed template
```
```console
$ porter mixins feed generate --help
Generate an atom feed from the mixins in a directory.
A template is required, providing values for text properties such as the author name, 
base URLs and other values that cannot be inferred from the mixin file names. You 
can make a default template by running 'porter mixins feed template'.
The file names of the mixins must follow the naming conventions …
```
=> Generate a mixin feed based on a directory

pkg/mixin/feed/feed.go, pkg/mixin/feed/generate.go, pkg/mixin/feed/generate_test.go, pkg/mixin/feed/load.go, pkg/mixin/feed/testdata/atom-existing.xml, pkg/mixin/provider/install.go, pkg/porter/mixins.go
=> Update an existing feed when generating a mixin feed from a directory

scripts/install/install-linux.sh, scripts/install/install-mac.sh, scripts/install/install-windows.ps1
The install scripts should succeed when run a second time. If the home directory already exists, that shouldn't cause a failure.
=> Make install scripts rerunnable

build/testdata/bundles/wordpress/porter.yaml
Adding a couple non-string set values to our test bundle (installed via `make test-cli`) to ensure porter-helm mixin support.  
Will fail until https://github.com/deislabs/porter-helm/pull/30 is merged/released.
=> feat(test-cli): add integer and boolean sets to wordpress example/test bundle

examples/azure-mysql-wordpress/porter.yaml
Turns out that `azureuser ` is not a valid username! 
The example had a space in the param template, so this fixes that up.
=> Fixed up a whitespace error

docs/content/authoring-bundles.md, docs/content/docs.md, docs/content/quickstart.md
Now that we have porter install/uninstall implemented, we should tell people to use that instead of duffle in our docs.
=> Use porter install in our docs

Makefile
The packr temp files were throwing off the vendor check locally. This removes them using `packr2 clean` first before we check.
=> Clean packr files before verifying vendor

CONTRIBUTING.md, Makefile
* Ensure `PORTER_HOME` is set to `bin` for all applicable make targets (not yet setup to run with other, user-defined values)
* Remove `build` target prerequisite from `install` (shortens dev loop for, say, only building the porter binary and installing locally, as in `make build-porter install`)
=> ref(Makefile): mandate PORTER_HOME value for make; no build prereq for install

cmd/porter/bundle.go
Since we have no way to have secure bundles, default insecure to true.
=> Default insecure to true for now

Gopkg.lock, Gopkg.toml, pkg/porter/list.go, vendor/github.com/carolynvs/datetime-printer/LICENSE, vendor/github.com/carolynvs/datetime-printer/pretty.go, vendor/github.com/dustin/go-humanize/LICENSE, vendor/github.com/dustin/go-humanize/big.go, vendor/github.com/dustin/go-humanize/bigbytes.go, vendor/github.com/dustin/go-humanize/bytes.go, vendor/github.com/dustin/go-humanize/comma.go, vendor/github.com/dustin/go-humanize/commaf.go, vendor/github.com/dustin/go-humanize/ftoa.go, vendor/github.com/dustin/go-humanize/humanize.go, vendor/github.com/dustin/go-humanize/number.go, vendor/github.com/dustin/go-humanize/ordinals.go, vendor/github.com/dustin/go-humanize/si.go, vendor/github.com/dustin/go-humanize/times.go
Use relative times for claims modified recently
When the claim has been touched in the last day, instead of showing the
datetime stamp, just show "1 min ago" or "5 hours ago". Otherwise if
it's been more than a day, just show the date, 2019-10-03.
Also sort the list with the most recently modified claims at the top.
Here is the sample output:
```console
$ porter bundle list
NAME    CREATED          MODIFIED         LAST ACTION   LAST STATUS
farts   29 minutes ago   29 minutes ago   install       success
HELLO   2019-05-10       2019-05-10       install       success
```
=> Use relative times for claims modified recently 

brigade.js
The `duffle` cli doesn't appear to be used by the integration tests any longer, so removing.
=> ref(brigade.js): remove duffle download from testIntegration

Makefile, mixin.mk, pkg/mixin/feed/feed_test.go, pkg/mixin/feed/generate_test.go, pkg/mixin/feed/testdata/atom.xml
An entry for the canary version (the permalink not the funky version
number) needed to be in the mixin feed but wasn't being added because it
wasn't in a directory in bin/mixins/exec/canary before we ran porter
mixin feed generate.
I also noticed that we lost uploading the mixin binaries to the latest
directory in azure storage. That is a nice thing to have in case someone
needed to download them directly using the permalink. So that is fixed
too.
Fixes #337
=> Fix canary publish

examples/README.md, examples/aks-spring-music/.gitignore, examples/aks-spring-music/README.md, examples/aks-spring-music/cnab/app/Dockerfile.base, examples/aks-spring-music/cnab/app/charts/spring-music/Chart.yaml, examples/aks-spring-music/cnab/app/charts/spring-music/templates/deploy.yaml, examples/aks-spring-music/cnab/app/charts/spring-music/templates/service.yaml, examples/aks-spring-music/cnab/app/charts/spring-music/values.yaml, examples/aks-spring-music/cnab/app/manifests/rbac-config.yaml, examples/aks-spring-music/cnab/app/run, examples/aks-spring-music/porter.yaml
This adds the AKS (Azure) + Exec + Kuberentes + Helm mixin that @chzbrgr71 and @jschluchter
put together, using a Docker base image.
Don't merge this until we cut a release of Porter and the Azure mixin.
Co-authored-by: Brian Redmond <chzbrgr71@gmail.com>
Co-authored-by: Joey Schluchter <jschluchter@gmail.com>
=> Add spring music example

brigade.js
Adding ability to handle issue/PR comment events, which utilizes a recent [Brigade-Github-App feature](https://github.com/brigadecore/brigade-github-app/pull/56).  This is still a pre-release feature, so hoping to help test/dogfood in this Porter project.
This feature may perhaps be most useful as a way to trigger CI for PRs that aren't automatically approved to run.  (Note that the comment author must be in the approved list for an action to actually take place.)
This can serve as an exercise on how we may do the same in other deislabs projects.  See also the [issue_comment_checks.js](https://github.com/brigadecore/brigade-github-app/blob/master/docs/examples/issue_comment_checks.js) example.
=> feat(brigade.js): handle issue comment events

pkg/config/manifest.go, pkg/config/manifest_test.go
Since Porter generates a Dockerfile during porter build, the template
used for the Dockerfile should not be named Dockerfile (or dockerfile
because case-insensitive file systems...) so that the template isn't
overwritten.
Fixes #355
=> Prevent using Dockerfile as the template name

cmd/porter/bundle.go, docs/content/authoring-bundles.md, docs/content/build-image.md, docs/content/porter-or-duffle.md, pkg/porter/build.go, pkg/porter/publish.go, pkg/porter/publish_test.go
This PR migrates the image push functionality to a new command `porter publish` (the command doesn't actually publish the bundle itself to OCI yet). Now when you do a `porter build` the invocation image is still _built_, but it is not pushed to a registry. The bundle.json is generated with whatever tag is present in the `porter.yaml`. 
To push the image and regenerate the bundle.json, you now do a `porter publish`. 
Command outputs below:
```
porter build
Copying dependencies ===>
Copying porter runtime ===>
Copying mixins ===>
Copying mixin kubernetes ===>
Generating Dockerfile =======>
FROM quay.io/deis/lightweight-docker-go:v0.2.0
FROM debian:stretch
COPY --from=0 /etc/ssl/certs/ca-certificates.crt /etc/ssl/certs/ca-certificates.crt
RUN apt-get update && \
apt-get install -y …
```
=> Migrate invocation image push to `porter publish`

cmd/porter/bundle.go, cmd/porter/credentials.go, pkg/porter/build.go, pkg/porter/build_test.go, pkg/porter/cnab.go, pkg/porter/credentials.go, pkg/porter/install.go, pkg/porter/uninstall.go, pkg/porter/upgrade.go
As part of #320, during `porter build` bundle.json is written to cnab/ now, and the cnab actions and publish look for it in cnab/.
=> Write bundle.json to cnab/

Gopkg.lock, Gopkg.toml, pkg/config/config.go, pkg/config/stamp.go, pkg/config/stamp_test.go, pkg/porter/build.go, pkg/porter/build_test.go, vendor/github.com/deislabs/cnab-go/bundle/bundle.go
We are only stamping with the on disk representation of the porter.yaml,
not the dirty in-memory representation. We don't care about in-mem, this
digest will be used later to determine if a rebuild is needed because
the porter.yaml on disk is out of sync with the bundle.json.
=>  Stamp bundle.json with a digest of porter.yaml

cmd/porter/bundle.go
Don't specify the exact files generated by create, they may change over time (they already have) and they are all explained now in the README generated at the root of the bundle.
=> Fix create helptext

Gopkg.lock, cmd/porter/credentials.go, pkg/credentialsgenerator/generator.go, pkg/credentialsgenerator/generator_test.go, pkg/porter/credentials.go, pkg/porter/credentials_test.go, pkg/porter/testdata/good-and-bad-test-creds/bad-creds.yaml, pkg/porter/testdata/good-and-bad-test-creds/good-creds.yaml, pkg/porter/testdata/test-creds/kool-kreds.yaml, vendor/github.com/deislabs/cnab-go/credentials/credentialset.go
* adds a credentials list command for porter
* renames porter's credentials generator pkg from `credentials` to `credentialsgenerator` to avoid naming confusion with duffle's/cnab-go's `credentials` pkg.  ping @jeremyrickard on this change for thoughts, etc.
A few TODOs remain, but I wanted to get early feedback on this one.
(Note: planning on tackling the table printing revamp TODO either in https://github.com/deislabs/porter/issues/371 or a separate ticket, as this will affect multiple pre-existing commands.)
Closes https://github.com/deislabs/porter/issues/366
=> feat(credentials): add credentials list command

pkg/porter/credentials.go, pkg/porter/credentials_test.go
This adds a call to MkdirAll with the credentials path before we attempt to write the credential file. This will ensure that the credential directory exists before we try and write the file. If the directory exists already, it's a NO-OP. 
Fixes #377
=> Add a call to MkdirAll for the credentials directory path.

pkg/cnab/provider/upgrade.go
We were accidentally were calling upgrade twice back-to-back. This fixes #386.
=> Remove double call to upgrade

pkg/config/helpers.go
Don't copy the binaries from the real bin on the local file system.
Instead just touch the files that we expect to exist, since they aren't
going to be executed anyway.
This avoid problems where a dirty dev bin/ directory causes unit tests
to fail because of unexpected directories and files existing when they
shouldn't.
=> Improve unit test setup of porter home

cmd/porter/bundle.go, pkg/context/context.go, pkg/porter/build.go, pkg/porter/contextOptions.go
The verbose flag hides all the extra output printed by the docker build
command, and also the contents of the dockerfile.
I tried to write unit tests for this but really build isn't easy to write tests for (the part that I modified, where we call out to docker). Not sure it's worth it, or if we do want to get tests for this, may require some more refactoring than I want to put into this PR.
=> Add verbose flag to build

Makefile, azure-pipelines.yml, brigade.js, cmd/porter/bundle.go, cmd/porter/credentials.go, pkg/config/config.go, pkg/config/helpers.go, pkg/config/stamp.go, pkg/config/stamp_test.go, pkg/mixin/provider/filesystem_test.go, pkg/porter/build.go, pkg/porter/build_test.go, pkg/porter/cnab.go, pkg/porter/cnab_test.go, pkg/porter/credentials.go, pkg/porter/helpers.go, pkg/porter/install.go, pkg/porter/install_test.go, pkg/porter/options.go, pkg/porter/publish.go, pkg/porter/publish_test.go, pkg/porter/stamp.go, pkg/porter/uninstall.go, pkg/porter/upgrade.go, tests/rebuild_test.go, tests/testdata/bundle-with-credentials.yaml
Introduce --cnab-file flag
All commands that supported a --file flag now have a --cnab-file flag,
and --file is now just for specifying the porter.yaml file. When they
need to work with a non-porter bundle, they use the --cnab-file flag to
pass in a bundle.json file.
---
Check hash and rebuild bundle if necessary
When the hash of the porter manifest doesn't match the hash found in the
bundle.json, rebuild the bundle before performing an action that uses
the bundle.json file.
---
Add programmatic integration test for rebuild
This is the start of testing with Go instead of Bash. What do you think?
=> Smart rebuild

pkg/porter/credentials.go, pkg/porter/options.go, tests/rebuild_test.go
I forgot to load the manifest first before calling the logic to do the
smart build. The integration test didn't catch it because the manifest
doesn't get nuked between calls. So I need to do more work to get the
integration tests to match how the CLI works.
=> Fix credentials generate smart build

cmd/porter/bundle.go, pkg/cache/cache.go, pkg/porter/helpers.go, pkg/porter/install.go, pkg/porter/install_test.go, pkg/porter/lifecycle.go, pkg/porter/lifecycle_test.go, pkg/porter/porter.go, pkg/porter/pull.go, pkg/porter/pull_test.go, pkg/porter/testdata/cache/887e7e65e39277f8744bd00278760b06/cnab/bundle.json, pkg/porter/uninstall.go, pkg/porter/upgrade.go
This adds --tag to upgrade and install. Since the functionality is used in a couple
places and Install/Upgrade/Delete currently have their own Opts that embed the same things,
I actually just made a new struct called LifecycleOpts that has a logic to deal with tag
if it's present (fetch the bundle, update the opts to use it)
Also refactored cache a little bit to make it easier to use a Mock and not actually use the
cache during a unit test
=> Added --tag to upgrade and install

docs/content/distributing-bundles.md, pkg/porter/publish.go
A very minor update to the log message around pushing the bundle tag (as opposed to the invocation image).  I thought it might be nice to print the bundle tag as differentiation from the image pushed prior.
=> feat(publish.go): print ref (bundle tag) on successful publish

Makefile, brigade.js, build/testdata/bundles/mysql/porter.yaml, build/testdata/bundles/terraform/porter.yaml, build/testdata/bundles/wordpress/porter.yaml, examples/aks-spring-music/porter.yaml, examples/azure-ark/porter.yaml, examples/azure-mysql-wordpress/porter.yaml, examples/kubernetes-mixin-example/porter.yaml, scripts/test/test-hello.sh, scripts/test/test-terraform.sh, scripts/test/test-wordpress.sh
Proposed implementation for https://github.com/deislabs/porter/issues/396
Note that I started off misinterpreting the original issue - I was thinking about the test bundles that we test in CI.  So, the first commit comprises changes to publish the test bundles while the second commit adds logic for publishing the example bundles.  We can either go with both or I can remove that first commit if we'd rather not publish the test variants.
=> ci(*): publish test and example bundles

pkg/porter/credentials.go, tests/rebuild_test.go
When I hooked up smart build I hadn't updated the existing Validate
method to use the new Validate method that handles validating and
defaulting in the proper order for --file and --cnab-file.
I've fixed the integration tests so that they catch the problem now,
they weren't checking the error from Validate.
Fixes #410
=> Fix smart build for credentials generate

docs/content/authoring-bundles.md, pkg/config/manifest.go, pkg/porter/build.go, pkg/porter/build_test.go
This adds manual support for image map. The data can be defined in the porter.yaml and porter will populate it in the generated bundle.json file, so that it is made available at runtime per the spec.
However porter and the mixins do not have any explicit behaviors based on the presence of the data. When a user populates the image map, they must also add scripts to the bundle to use it at runtime.
=> Add ImageMap

brigade.js
Proposed implementation for https://github.com/deislabs/porter/issues/409
Collabo with @krancour, who was of crucial assistance around some of the finer points of setting up the golang env in the alpine-based `docker:stable-dind` base image.
Uses https://github.com/vdice/go-dind currently, but we can amend/port/etc.  This image currently comes in at `814MB`, so at least chops some weight off of our golang image (the previous `deis/go-dev` image comes in at `1.86GB`)
=> ref(brigade.js): update applicable jobs to run via DinD

docs/content/authoring-bundles.md, docs/content/slides/pack-your-bags/index.md, pkg/cnab/config_adapter/adapter.go, pkg/cnab/config_adapter/adapter_test.go, pkg/cnab/config_adapter/testdata/porter-with-parameters.yaml, pkg/config/manifest.go, pkg/config/manifest_test.go, workshop/wordpress/porter.yaml
Improve json schema support
* allowed values -> enum
* minValue/maxValue -> minimum/maximum
* Added exclusiveMinimum/exclusiveMaximum
* Add tests for manifest->bundle.json parameters definitions
* Added tests for number
* Added documentation on what we support
---
Move parameter schema into a separate type in preparation for later
---
Inline location on credentials. Previously we had duplicated the fields for location but I think it may com in handy to start treating them a bit more similarly, so I put a location on them.
Closes #346
=> CNABify Parameters a bit

pkg/config/config.go, pkg/config/config_test.go, pkg/config/manifest.go, pkg/config/manifest_test.go, pkg/config/testdata/porter.yaml, pkg/porter/build.go, scripts/test/test-cli.sh
This removes the old dependency implementation that relied upon merging
the manifests from dependencies with the current manifest. It is going
to be quickly replaced with executing dependencies in their own bundle
runtime and relying upon outputs.
Closes #431
=> Remove old dependency implementation

pkg/cnab/config_adapter/adapter.go, pkg/cnab/config_adapter/adapter_test.go, pkg/cnab/config_adapter/testdata/porter-with-deps.yaml, pkg/cnab/config_adapter/testdata/porter.yaml, pkg/cnab/extensions/dependencies.go, pkg/cnab/extensions/dependencies_test.go, pkg/cnab/extensions/testdata/bundle.json, pkg/config/manifest.go, pkg/config/manifest_test.go, pkg/config/testdata/porter.yaml, pkg/porter/dependencies/dependencies.go, pkg/porter/dependencies/dependencies_test.go
Writes any dependencies in porter.yaml to bundle.json when the bundle is built. 
There are three forms of specifying a dependency:
1. You can just say exactly which bundle, including the tag, that you depend upon, `deislabs/azure-mysql:5.7`
2. You can rely on a named bundle, but not say which version, `deislabs/azure-mysql`. Basically any version of the bundle is ok. You can specify if prereleases are allowed or not (default is false).
3. You can specify a set of version ranges to allow `deisalbs/azure-mysql` + `5.7 - 6.x, 7.1 - 7.5.x`
Closes #429
=> Populate dependencies in bundle.json

Makefile
This fixes an error encountered in CI whilst attempting to publish bundles.  The job to do so first runs `make build install` to install porter, but the `install` command was attempting to copy in `bin/bundles` which was not populated:
```
...
mkdir -p /root/.porter
cp -R bin/bundles /root/.porter/
cp: can't stat 'bin/bundles': No such file or directory
make: *** [Makefile:155: install] Error 1
```
The bug was intro'd via myself in a recent PR 😅, wherein I tried to select only the subdirs of `bin` that should be copied over, having realized that with the previous method (`cp -R bin/*`), we were copying `credentials`, `claims` and other subdirs generated by cli tests, etc., into our local home, which we might not want.
=> fix(Makefile): rm copying bin/bundles into porter home on install

cmd/porter/bundle.go, cmd/porter/credentials.go, cmd/porter/mixins.go, pkg/porter/credentials.go, pkg/porter/credentials_test.go, pkg/porter/list.go, pkg/porter/mixins.go, pkg/porter/mixins_test.go, pkg/porter/outputs.go, pkg/porter/show.go, pkg/porter/show_test.go, pkg/printer/printer.go, pkg/printer/printer_test.go
Refactor stemming from https://github.com/deislabs/porter/pull/451#discussion_r303459986
* DRYs out applicable commands to use an updated `PrintOptions` struct now containing both `RawFormat` and `Format` values
=> ref(*): DRY print options via updated PrintOptions struct

Makefile
This removes those extra packr files after a standard build, i.e. `make build`.
=> Cleanup packr after a build

cmd/porter/bundle.go, cmd/porter/credentials.go, pkg/porter/credentials.go, pkg/porter/credentials_test.go, pkg/porter/list.go
In some places we were directly using the printer options instead of the parent operations struct when calling an operation. Eventually the list operation is going to have more parameters, so I wanted to switch to using the operation's struct now and follow the existing pattern of passing the entire operation's struct around instead of individual parameters to operations.
=> Use operation's options struct instead of print opts

pkg/porter/install.go, pkg/porter/invoke.go, pkg/porter/invoke_test.go, pkg/porter/lifecycle.go, pkg/porter/uninstall.go, pkg/porter/upgrade.go
Install, Upgrade, Uninstall and Invoke all used the same code for Validate and ToDuffleArgs. I've moved that duplicated code to BundleLifecycleOptions.
=> Move shared code to BundleLifecycleOptions

pkg/cnab/cnab-to-oci/registry.go, pkg/porter/porter.go, pkg/porter/publish.go, pkg/porter/pull.go, pkg/porter/registry.go
I needed the logic for pull in a reusable function that I could test in preparation for the dependencies feature. So I've taken PullBundle and its mate PublishBundle and extracted them into an interface, Registry.
=> Extract push/pull into a registry interface/pkg

pkg/config/config.go, tests/install_test.go
- Ensures GetPorterHome() returns the absolute path to porter home
Fixes https://github.com/deislabs/porter/issues/460
=> fix(config.go): ensure porter home path is absolute

examples/azure-tf-example/.dockerignore, examples/azure-tf-example/.gitignore, examples/azure-tf-example/README.md, examples/azure-tf-example/porter.yaml, examples/azure-tf-example/terraform/cosmos-db.tf, examples/azure-tf-example/terraform/eventhubs.tf, examples/azure-tf-example/terraform/main.tf, examples/azure-tf-example/terraform/outputs.tf, examples/azure-tf-example/terraform/variables.tf
This adds an example to the examples directory that leverages the `porter-azure` and `porter-terraform` mixins to install, upgrade and uninstall some infrastructure.
=> Add Porter Terraform Example

build/testdata/bundles/terraform/porter.yaml, pkg/cnab/config_adapter/adapter.go, pkg/cnab/config_adapter/adapter_test.go, pkg/cnab/config_adapter/testdata/porter-with-parameters.yaml, pkg/cnab/provider/install.go, pkg/cnab/provider/invoke.go, pkg/cnab/provider/parameters.go, pkg/cnab/provider/parameters_test.go, pkg/cnab/provider/uninstall.go, pkg/cnab/provider/upgrade.go, pkg/config/manifest.go, scripts/test/test-terraform.sh
- adds `applyTo` to the Parameter definition, per the CNAB Spec
- updates `loadParameters` in `pkg/cnab/provider/parameters.go` accordingly
- adds `loadParameters` unit tests
- fixes subtle bug around populating the bundle.json's Definitions struct; adds test (there were cases where we were overriding a pre-existing Definition if used by both an Output and a Parameter)
Depends on https://github.com/deislabs/porter/pull/473 (Would like to get 473 in first and then rebase accordingly)
Closes https://github.com/deislabs/porter/issues/439
=> feat(*): add applyTo for parameters; update loadParameters logic accordingly

pkg/cnab/provider/duffle.go
This fixes a null reference error in WriteClaimOutputs when a bundle doesn't have any outputs.
=> Skip writing outputs when there are none

pkg/cnab/config_adapter/adapter.go, pkg/cnab/config_adapter/adapter_test.go
Fixes https://github.com/deislabs/porter/issues/482
=> fix(adapter.go): don't add empty outputs section to generated bundle

scripts/install/install-windows.ps1
updates the Windows/PowerShell install script to remove iex (invoke-expression).
Replace with the call operator &.
iex is considered a code smell, with some well known security implications.
=> removed iex (invoke-expression) from windows install script

workshop/docker-image/Dockerfile.workshop
Adding a Dockerfile for the workshop so people don't need to install anything. This also fixes the issue that some people dont want to login to DockerHub with paly with Docker as it is not secure. 
To run the image `docker run -d --privileged --name workshop <img name>/workshop && docker exec -it workshop sh`
This will give the users a full isolated Docker engine and Porter.
=> Adding Dockerfile for the workshop

docs/config.toml, docs/content/mixins/_index.md, docs/content/mixins/gcloud.md
Doc available at https://porter.sh/mixins/gcloud
=> Document the gcloud mixin

pkg/cnab/provider/dockerdriver_test.go, pkg/cnab/provider/duffle.go, pkg/cnab/provider/install.go, pkg/cnab/provider/parameters.go, pkg/cnab/provider/upgrade.go, pkg/outputs/outputs.go
Fixes bug where Porter would attempt to read/write an output without checking to see if the output applied to the current action.  Now, if the output does not apply to the current action, Porter does not attempt to read/write.
Note some TODOs exist around https://github.com/deislabs/cnab-go/pull/99
=> fix(duffle.go): add check for output's applyTo before attempting to read

pkg/porter/templates/create/.gitignore
I forgot to update the default `.gitignore` entry when I renamed `cnab` to `.cnab`.
=> Fix ignore of .cnab

pkg/cnab/provider/invoke.go
This is a follow-on to #507. I noticed during the review that it was missing writing the claim outputs during the new invoke action.
=> Write claim outputs on invoke

pkg/porter/build_test.go, pkg/porter/templates/build/Dockerfile
Install ca-certificates using apt instead of copying from another base image to not have to download multiple base images.
=> Use debian only for base image

Gopkg.lock, Gopkg.toml, vendor/github.com/deislabs/cnab-go/action/action.go, vendor/github.com/deislabs/cnab-go/bundle/bundle.go, vendor/github.com/deislabs/cnab-go/claim/claim.go, vendor/github.com/deislabs/cnab-go/credentials/credentialset.go, vendor/github.com/deislabs/cnab-go/driver/docker/docker.go
This pulls in the fix from cnab-go for always fetching outputs even when none are defined https://github.com/deislabs/cnab-go/pull/111
=> Fix outputs error

pkg/cnab/config_adapter/adapter.go, pkg/cnab/config_adapter/adapter_test.go, pkg/cnab/config_adapter/testdata/porter-with-parameters.yaml
Sensitive means that we should *** out the value when printing to the console. WriteOnly means that the value shouldn't be printed out either, as established in https://github.com/deislabs/cnab-spec/issues/164#issuecomment-487060780.
Closes #440
=> Map sensitive to writeOnly when converting to bundle.json

brigade.js
We've been seeing many false-negative Brigade pipeline failures due to Brigade giving up on the longer-running checks (integration, cli tests, example bundle publishing, etc.), even though they may (usually) end up passing.  Therefore, I propose we set a very generous job timeout for the standard `GoJob` that we re-use in our `brigade.js` file.
=> fix(brigade.js): set generous default timeout for GoJob

pkg/cnab/provider/duffle.go, pkg/config/outputs.go, pkg/config/outputs_test.go, pkg/porter/outputs.go, pkg/porter/outputs_test.go, pkg/porter/run.go, pkg/porter/run_test.go
I was getting a lot of cyclical import problems because I kept wanting to use the very useful outputs package from other packages. Since it is operating on files in the config directory, it seems like a natural fit to move it into the config package. Hopefully the applies to logic will move into cnab-go soon anyway.
=> Move outputs pkg into config

Makefile, pkg/mixin/helpers.go, pkg/mixin/provider/filesystem_test.go, pkg/mixin/runner_integration_test.go, pkg/mixin/runner_test.go, pkg/porter/mixins_test.go
I've made two changes:
1. `make test-unit` doesn't do a build before running `go test`. This will make them faster to run, and also safer to run in a one-off fashion from an IDE or command-line using go test directly.
2. Cleanup tests usage of filesystem
Some tests used the filesystem (bin) but didn't really need it, so I fixed them so that they could run as unit tests now that we aren't building before running the tests. 
Other tests really do need to hit the file system and need a properly populated bin, so I promoted them to integration tests.
=>  Don't build before running unit tests 

Makefile, pkg/porter/schema.go
* Add troubleshooting hook to porter schema
When porter.json is present in PORTER_HOME, the porter schema command will return it, instead of generating a schema. This is intended to assist with troubleshooting VS Code. It will allow someone to tweak the schema without modifying porter or the mixins and quickly iterate inside of VS Code, and then we can update the Go code to match the desired schema later.
* Make porter schema more robust
* When an error occurs generating a schema, return the template so that we at least have the basic schema available at all times.
* When an error occurs injecting a mixin, always skip and continue to the next, never error out so that an out of date mixin doesn't cause the entire command to fail.
=> Improve the schema command

docs/content/mixins/aws.md, docs/content/mixins/gcloud.md
The gcloud and aws mixins now use the exec mixin to support the jsonPath output.
Previews at:
* https://deploy-preview-568--porter.netlify.com/mixins/aws/
* https://deploy-preview-568--porter.netlify.com/mixins/gcloud/
=> Update mixin docs for gcloud and aws

docs/content/cli/version.md
A PR to modify this command was merged near the same time that I automated the docs for the site and this file was missed.
=> Sync doc for porter version

examples/exec-outputs/generate-config.sh
The example was concatenating the config file instead of overwriting it. So when the user reran the bundle, the config file had multiple lines of the same example config.
=> Fix example exec output

pkg/context/context.go, pkg/mixin/runner_integration_test.go, pkg/mixin/testdata/exec_input_with_whitespace.yaml
Adds a safeguard to ensure we don't attempt to mask empty strings, in the off-chance that they show up as a sensitive value.
Before
```
=== RUN   TestRunner_RunWithMaskedOutput
--- FAIL: TestRunner_RunWithMaskedOutput (0.34s)
logger.go:11: *******H*******e*******l*******l*******o******* ***************************************************************
*******
runner_integration_test.go:69:
Error Trace:	runner_integration_test.go:69
Error:      	"*******H*******e*******l*******l*******o******* ***************************************************************
*******" does not contain "Hello *******"
Test:       	TestRunner_RunWithMaskedOutput
```
After
```
=== RUN   TestRunner_RunWithMaskedOutput
--- PASS: TestRunner_RunWithMaskedOutput (0.18s)
logger.go:11: Hello *******
```
=> fix(context.go): ensure censored writer does not replace empty strings

Makefile
Now that the bundle schema [references](https://github.com/deislabs/cnab-spec/blob/master/schema/bundle.schema.json#L219) the new [definitions.schema.json](https://github.com/deislabs/cnab-spec/blob/master/schema/definitions.schema.json), we need to fetch this referenced schema and supply it to the `ajv` cli for validation.  (This manual step is needed until https://github.com/deislabs/cnab.io/issues/15 is closed.)
=> fix(Makefile): fix bundle validation by fetching/supplying definitions schema

Makefile
For some reason compiling packr2 suddenly broke with errors about envy:
`bash: [ENVY]: command not found`
and
`[ENVY] unable to load env file(s) on init: open .env: no such file or directory`
I opened https://github.com/gobuffalo/packr/issues/237 to figure out what changed but until then switching to binary installs.
=> Fix installation of packr2

cmd/porter/mixins.go, docs/content/cli/mixins_install.md, docs/content/install.md, docs/content/mixins/aws.md, docs/content/mixins/azure.md, docs/content/mixins/exec.md, docs/content/mixins/gcloud.md, docs/content/mixins/helm.md, docs/content/mixins/kubernetes.md, docs/content/mixins/terraform.md, docs/content/slides/pack-your-bags-msp/index.md, docs/content/slides/pack-your-bags/index.md, pkg/mixin/install.go, pkg/mixin/install_test.go, scripts/install/install-linux.sh, scripts/install/install-mac.sh, scripts/install/install-windows.ps1, workshop/aws-bucket/README.md, workshop/gcloud-compute/README.md
* Unless the user specifies `--url` or `--feed-url`, use the atom feed for deislabs
* Update all the install instructions for the mixins to not specify `--feed-url`
* Update stray references of --feed-url to not use it unless strictly necessary
=> Default the mixin feed url to DeisLabs

cmd/exec/main.go, cmd/exec/version.go, cmd/kubernetes/version.go, cmd/porter/version.go, docs/content/mixin-commands.md, pkg/exec/version.go, pkg/exec/version_test.go, pkg/kubernetes/version.go, pkg/kubernetes/version_test.go, pkg/mixin/main_test.go, pkg/mixin/metadata.go, pkg/mixin/provider/filesystem.go, pkg/mixin/provider/install.go, pkg/mixin/runner.go, pkg/mixin/runner_test.go, pkg/porter/helpers.go, pkg/porter/mixins.go, pkg/porter/mixins_test.go, pkg/porter/version.go, pkg/porter/version/version.go, pkg/porter/version/version_test.go, pkg/porter/version_test.go
* Extract common version package 
* Implement `version --output json` for exec and kuberentes
* Update `porter mixins list` to include the mixin version and author if available
* Updated mixin authoring documentation for the version command is available at https://deploy-preview-588--porter.netlify.com/mixin-commands/#version
```console
$ porter mixins list
Name         Version                     Author
az
azure
exec         v0.13.1-beta.1-7-g37f3637   DeisLabs
gcloud
helm
kubernetes   v0.13.1-beta.1-7-g37f3637   DeisLabs
terraform
```
Closes #263
=> Include mixin version in porter mixins list output

pkg/dep/dep.go
Move the file into a package that no one imports. That way consumers of dep aren't forced to pick up dependencies listed in that file.
=> Move dep override file

cmd/porter/credentials.go, docs/content/cli/credentials_generate.md, pkg/porter/cnab.go, pkg/porter/credentials.go
This PR adds the --tag option to credentials generate so people can install from a tag without any unpleasant work arounds. It reuses the lifecycle methods, maybe we should rename? Although I feel like generating a credential is kind of related to the lifecycle of the bundle. Ideally, we can link this in automagically to the `invoke` actions next. No credential specified? GENERATE THE HECK OUT OF ONE!!!
This also does a small fix to the help text. 
Fixes #492
=> Add --tag to porter credentials generate

Makefile, azure-pipelines.yml
Do not install porter to build and validate example bundles, instead reference porter from the bin.
Fixes #513
=> Enable example bundle validation in azure pipelines

cmd/porter/aliases.go, cmd/porter/bundle.go, docs/content/cli/archive.md, docs/content/cli/bundles_archive.md, pkg/porter/archive.go
This adds the scaffolding for the new Porter archive command. It's currently hidden, but I wanted to open a PR that introduced it so we could figure out if these options/command experience are correct.
=> Add scaffolding for new porter archive command

docs/config.toml
We aren't consistent about when we join paths with a slash. For now
use a trailing slash but later we should cleanup the theme and wherever we use
site.baseurl, always join with a /.
=> Use trailing slash on baseurl

docs/content/authoring-bundles.md, docs/content/wiring.md, pkg/cnab/config_adapter/adapter.go, pkg/cnab/config_adapter/adapter_test.go, pkg/config/manifest.go, pkg/config/runtime-manifest.go, pkg/config/runtime-manifest_test.go, pkg/config/testdata/porter-images.yaml, workshop/porter-tf-aci/azure/bundle/porter.yaml
This PR adds image map wiring / interpolation into Porter's bag of tricks. It changes the `imageMap` part of the porter.yaml to `images` to match the issue comments and does some various cleanup. 
Closes #501
Since mustache template interpolation is case sensitive, I decided to use `reflect` to iterate the MappedImage struct and `strings.ToLower` the name of the field, that way it matches up against the yaml. Otherwise, we ended up with references like `{{bundle.images.thing.Repository}}`, which bugged me.
=> Add image map wiring

docs/content/authoring-bundles.md, docs/content/mixin-commands.md, pkg/build/dockerfile-generater.go, pkg/build/dockerfile-generator_test.go, pkg/build/testdata/multiple-mixins.yaml, pkg/config/manifest.go, pkg/config/manifest_test.go, pkg/config/runtime-manifest_test.go, pkg/config/testdata/mixin-with-bad-config.yaml, pkg/config/testdata/mixin-with-config.yaml, pkg/mixin/buildInput.go
Passes context to mixins when we ask them to build Dockerfile lines to inject into the invocation image. The mixin always gets the usage of the mixin in the manifest. Also if the mixin declaration contains any configuration data, then that is passed along as well.
The context is sent via stdin when we call `mixin build` just like we do with the other mixin commands like `mixin install`.
```yaml
mixins:
- exec
- az:
extensions:
- iot
install:
- az:
description: Login
arguments:
- login
uninstall:
- exec:
description: "Uninstall stuff"
command: "bash"
arguments:
- echo bye
```
The `az build` command would receive this on stdin:
```yaml
config:
extensions:
- iot
actions:
install:
- az:
arguments:
- login
description: Login
uninstall: []
upgrade: []
```
The `exec build` command would receive …
=> Pass build context to mixins

Gopkg.lock, Gopkg.toml, pkg/cnab/config_adapter/adapter.go, pkg/cnab/config_adapter/adapter_test.go, pkg/cnab/config_adapter/testdata/porter-with-parameters.yaml, pkg/cnab/provider/parameters.go, pkg/cnab/provider/parameters_test.go, pkg/cnab/provider/testdata/file-param, pkg/config/manifest.go, pkg/config/manifest_test.go, pkg/config/runtime-manifest.go, pkg/config/runtime-manifest_test.go, pkg/config/testdata/file-param, pkg/porter/run.go, pkg/porter/testdata/porter.yaml, tests/install_test.go, tests/testdata/bundle-with-file-params.yaml, tests/testdata/myfile, vendor/github.com/deislabs/cnab-go/bundle/definition/schema.go, vendor/github.com/deislabs/cnab-go/bundle/definition/validation.go, vendor/github.com/deislabs/cnab-go/bundle/definition/validators.go, vendor/github.com/deislabs/cnab-go/claim/claim.go
Enables Porter manifest parameters of type `file`.  Ref https://github.com/deislabs/porter/issues/480
TODO:
~~Note: validation broken pending https://github.com/deislabs/porter/pull/581~~
=> feat(*): enable parameters of type file in Porter manifest

pkg/build/dockerfile-generater.go, pkg/mixin/buildInput.go
When I implemented build context I imported `pkg/config` into a package used by all the mixins. This makes them have to depend on a bunch of unnecessary packages.
I really didn't need to import config.Step so I undid that change so that mixins don't need to have a bunch more dependencies.
N/A
N/A
=> Do not import pkg/config from pkg/mixins

build/testdata/bundles/terraform/porter.yaml, docs/content/mixins/terraform.md, examples/azure-tf-example/README.md, examples/azure-tf-example/porter.yaml, workshop/porter-tf-aci/azure/bundle/porter.yaml, workshop/porter-tf/azure/porter.yaml
Removes the unnecessary/deprecated `autoApprove` property from examples utilizing the `terraform` mixin, per https://github.com/deislabs/porter-terraform/pull/22
N/A
N/A
=> chore(*): remove autoApprove property in tf examples

workshop/azure-cli/Dockerfile.tmpl
This fix is for issue #652 to allow `porter build` to succeed in `azure-cli` workshop exercise.
Adds missing Dockerfile stanza required for `porter build` to succeed.
Closes #652
=> Added missing BUILD_DIR arg to Dockerfile.tmpl

pkg/exec/builder/execute.go, pkg/kubernetes/execute.go, pkg/kubernetes/install.go, pkg/kubernetes/kubernetes.go, pkg/kubernetes/uninstall.go, pkg/mixin/provider/runner.go
https://github.com/deislabs/porter/blob/7da5cffdf3581c27dfab03af88df2df005baa02d/pkg/exec/builder/execute.go#L72-L75
`cmd.Path` is including application name, and the first argument of `cmd.Args` is also apps name , So it change to `cmd.Dir` and get rid of space of `%s%s`
Closes #651 
Nil
=> Get rid of command name in prettyCmd #651

examples/kubernetes-mixin-example/porter.yaml
Removes `exec` step from kube example that shouldn't have been merged
The kube example got updated because I forgot to throw away a temporary change while helping someone debug. 
=> Fix kube example

Gopkg.toml, pkg/cnab/provider/action.go, pkg/cnab/provider/bundle.go, pkg/cnab/provider/claims.go, pkg/cnab/provider/credentials.go, pkg/cnab/provider/dockerdriver_test.go, pkg/cnab/provider/install.go, pkg/cnab/provider/invoke.go, pkg/cnab/provider/parameters.go, pkg/cnab/provider/parameters_test.go, pkg/cnab/provider/runtime.go, pkg/cnab/provider/uninstall.go, pkg/cnab/provider/upgrade.go, pkg/porter/cnab.go, pkg/porter/dependencies.go, pkg/porter/helpers.go, pkg/porter/install.go, pkg/porter/invoke.go, pkg/porter/lifecycle.go, pkg/porter/list.go, pkg/porter/porter.go, pkg/porter/uninstall.go, pkg/porter/upgrade.go
We used to rely on duffle and have some internal classes and comments that still use the name. I've gone through and renamed them, and updated comments to prevent any confusion.
N/A
https://www.youtube.com/watch?v=Eo-KmOd3i7s
=> Rename things from Duffle since we don't use it anymore

README.md
When I split up the build into separate pipelines, the build badge on the readme broke. This fixes it.
N/A
N/A
=> Fix build status badge on readme

pkg/config/manifest.go, pkg/config/manifest_test.go, pkg/config/testdata/mixin-with-config.yaml, pkg/config/testdata/with-credentials.yaml
This PR adds a method, `UnmarshalYAML` to the CredentialDefinition struct to always mark a credential's definition as required i.e. `true` when unmarshaling from a YAML to create a manifest file. This makes credentials required by default.
[#577](https://github.com/deislabs/porter/issues/577)
[1]: https://github.com/deislabs/porter/blob/master/CONTRIBUTING.md#when-to-open-a-pull-request
- In the spec for this issue, it's mentioned that `THERE IS NO WARNING. The bundle just fails in odd places with unexpected errors because the bundle was written assuming credentials would be there, and they aren't.` Can this be solved within this issue?
- Also, I was not sure on how to exactly test the change made and what I did was to create a YAML file `with-credentials.yaml` with some credentials …
=> Made credentials required by default by adding UnmarshalYAML method to CredentialDefinition type

scripts/test/test-terraform.sh
Removes a fragile check (based on literal text output which is subject to change) in the terraform portion of the cli test.  It is now redundant as we've since added `porter instance outputs list` checks to verify the expected file contents value.  
Fixes the `test-cli` target in CI.
N/A
=> fix(test-terraform.sh): remove fragile, redundant file contents check

docs/content/best-practices/gke.md, docs/themes/porter/layouts/_default/section.html
* There was an extra ] on the [GKE doc page](https://deploy-preview-674--porter.netlify.com/best-practices/gke/#create-a-service-account) in the second step.
> Assign the account access to GKE]
* On the [Best Practices listing page](https://deploy-preview-674--porter.netlify.com/best-practices/), it was showing a "..." after the GKE description because the layout relied on Truncated even though we weren't using the summary, just the description.
> How to connect to a GKE cluster inside a Porter bundle.... 
N/A
N/A
=> Cleanup gke doc

Makefile
Fix packr2 failed to install while running make
Closes #667
=> Fix packr2 failed to install while running make

build/testdata/bundles/mysql/porter.yaml
Porter's integration tests started to [fail](https://dev.azure.com/deislabs/porter/_build/results?buildId=3557) around upgrading the MySQL bundle:
```
...
Upgrade MySQL
Tiller version (v2.12.3) does not match client version (v2.14.3); downloading a compatible client.
/usr/local/bin/helm helm upgrade porter-ci-mysql-wwwvyhwuab stable/mysql
Error: UPGRADE FAILED: Deployment.apps "porter-ci-mysql-wwwvyhwuab" is invalid: spec.selector: Invalid value: v1.LabelSelector{MatchLabels:map[string]string{"app":"porter-ci-mysql-wwwvyhwuab", "release":"porter-ci-mysql-wwwvyhwuab"}, MatchExpressions:[]v1.LabelSelectorRequirement(nil)}: field is immutable
Error: exit status 1
Error: mixin execution failed: exit status 1
```
My hunch is that since we didn't specify a chart version for the upgrade step …
=> fix(mysql/porter.yaml): use same chart version in upgrade step

docs/content/authoring-bundles.md, pkg/config/manifest.go, pkg/config/manifest_test.go, pkg/config/testdata/missing-invocation-image.porter.yaml
Adds a function `SetDefaults`, that is called after we load the manifest from the filesystem. It checks if `invocationImage` is empty and defaults it to `tag`-installer. For example, if `manifest.Tag` is `deislabs/porter-hello:latest`, then `manifest.InvocationImage` will be defaulted to `deislabs/porter-hello-installer:latest`.
Closes #383
N/A
=> Set Default InvocationImage

pkg/cnab/config_adapter/adapter.go
Updates schema version for generated bundles to reflect the [v1.0.0 release](https://github.com/deislabs/cnab-spec/releases/tag/cnab-core-1.0)
N/A
N/A
=> chore(adapter.go): update schema version for generated bundles

cmd/porter/docs.go, cmd/porter/main.go, pkg/docs/generator.go, pkg/docs/generator_test.go
As part of validation, `porter docs` checks if the destination folder exists. If the destination doesn't exist, execution is canceled and a proper error message is presented to the user.
Closes #685 
- [ X ] Documentation Not Impacted
=> feat(docs): Validate if destination exists before invoking command

.vscode/settings.json, docs/content/authoring-bundles.md
Fixes broken permalink of [images](https://porter.sh/authoring-bundles/#image-map) section in [Authoring bundles](https://porter.sh/authoring-bundles)
* visit https://porter.sh/authoring-bundles/
* click on "Image Map" link
* Nothing will happen
Clicking on "Image Map" link should navigate to "Images" section
=> Fix broken permalink in docs

pkg/mixin/provider/install.go, pkg/mixin/provider/install_test.go
This PR adds the ability to save mixin source when it is installed. It saves this info to a file located at `$PORTER_HOME/mixins/cache.json`
Closes #610 
First PR  :-)
=> updated mixin install process to save info

Gopkg.lock, Gopkg.toml, pkg/cnab/cnab-to-oci/registry.go, vendor/github.com/docker/cnab-to-oci/converter/convert.go, vendor/github.com/docker/cnab-to-oci/converter/types.go, vendor/github.com/docker/cnab-to-oci/relocation/types.go, vendor/github.com/docker/cnab-to-oci/remotes/fixup.go, vendor/github.com/docker/cnab-to-oci/remotes/fixuphelpers.go, vendor/github.com/docker/cnab-to-oci/remotes/fixupoptions.go, vendor/github.com/docker/cnab-to-oci/remotes/pull.go, vendor/github.com/docker/cnab-to-oci/remotes/push.go
This PR updates [`cnab-to-oci` to v0.2.0-beta1](https://github.com/docker/cnab-to-oci/releases/tag/v0.2.0-beta1), which stores the entire bundle in the OCI registry.
The behaviour of `porter publish` is not changed.
=> Update cnab-to-oci to v0.2.0-beta1

pkg/build/dockerfile-generater.go, pkg/build/dockerfile-generator_test.go
This change adds a method `readAndValidateDockerfile` to the `type` `*DockerfileGenerator` in order to check for `ARG BUILD_DIR` in the Dockerfile during the building of a bundle. If `ARG BUILD_DIR` is not found, an error message is returned.
Closes [#655](https://github.com/deislabs/porter/issues/655)
[1]: https://github.com/deislabs/porter/blob/master/CONTRIBUTING.md#when-to-open-a-pull-request
=> Check dockerfile for ARG BUILD_DIR

Gopkg.lock, Gopkg.toml, pkg/porter/cnab.go, pkg/porter/install_test.go, vendor/github.com/deislabs/cnab-go/driver/command/command.go
Adds support to Porter for Command Driver.
Updates cnab-go dependency to v0.7.0-beta1
=> Command driver support

CODE_OF_CONDUCT.md
The link to Slack on the Code of Conduct was broken.
N/A
🤷‍♀️
=> Fix link to Slack on CoC

build/README.md, build/azure-pipelines.release.yml
Splits up the release pipeline into stages.
Closes #673 
🏎
=> Split release pipeline into stages

pkg/exec/action.go, pkg/exec/builder/execute.go, pkg/exec/builder/flags.go, pkg/exec/builder/flags_test.go, pkg/exec/builder/output_jsonpath_test.go
Adds a `GetDashes()` method to the `ExecutableStep` interface such that implementations can modify the dashes appended to flags.
As proposed in https://github.com/deislabs/porter/pull/681#issuecomment-539102454
N/A, but used by https://github.com/deislabs/porter-terraform/pull/25
Is there a way to have this new method be "optional"? Or will we need to add implementations of the method in the other mixins that implement `ExecutableStep`?
=> feat(exec/builder): add GetDashes method to ExecutableStep interface

build/azure-pipelines.release.yml
I can't type and testing the release pipeline is hard...
https://dev.azure.com/deislabs/porter/_build/results?buildId=3774&view=logs&jobId=8561663e-1bfb-5abd-6b97-f5ad2d809477
* The job where we publish porter binaries uses porter, so we need to do a normal `make build`
* The job where we publish example bundles was missing a call to make before `publish-bundle`
=> Fix release pipeline

pkg/instance-storage/filesystem/plugin.go, pkg/instance-storage/provider/provider.go
When I merged the plugin work, I accidentally still had the plugin logging set to debug. This puts it to error where it belongs.
N/A
N/A
=> Set plugin logging to error

CONTRIBUTING.md
Lot of directories are now not in root level. They moved to `pkg` directory. This change syncs doc with repo layout
I hope we don't need extra whitespaces :)
=> Sync code layout section in doc with repo layout

Makefile, build/azure-pipelines.release.yml
* Fix release permalink
if a tag has been made before the build then theold way of detecting canary picked up the tag and reported a relative ref, e.g. v0.18.0-beta.1~1 This tests for an exact tag on the current commit.
* Publish tagged builds
Accidentally excluded tags when trying to prevent publishes from kicking on a PR
Need to update mixin makefiles with the permalink fix
=> Fix publish

Makefile, docs/content/install.md, scripts/install/install-linux.sh, scripts/install/install-mac.sh, scripts/install/install-windows.ps1, scripts/prep-install-scripts.sh, scripts/test/test-linux-install.sh, scripts/test/test-mac-install.sh, scripts/test/test-windows-install.ps1
Install an older version of porter
Closes #729 
I think I can test this change out in a single PR. 🤞
=> Support installing a specific version of porter

pkg/cnab/cnab-to-oci/registry.go, pkg/porter/publish.go, pkg/porter/publish_test.go, pkg/porter/registry.go
Refreshes Porter's bundle cache with a newly published bundle, if it existed previously.
Closes https://github.com/deislabs/porter/issues/678
This is one approach to fixing https://github.com/deislabs/porter/issues/678.  Here we actually refresh the cache so that the next pull of the bundle with the same tag will use the refreshed cache.
Another approach would be to just remove the cached entry on publish.  Then, a subsequent pull would actually need to pull from remote.  The benefit here would be simplified logic, though again, would be forced to re-pull.
=> feat(publish): refresh local cache if newly published bundle exists

cmd/porter/bundle.go, docs/content/cli/bundles_install.md, docs/content/cli/bundles_invoke.md, docs/content/cli/bundles_uninstall.md, docs/content/cli/bundles_upgrade.md, docs/content/cli/install.md, docs/content/cli/invoke.md, docs/content/cli/uninstall.md, docs/content/cli/upgrade.md, pkg/porter/dependencies.go
This adds a `--force` flag to the standard action commands (install, upgrade, uninstall, --invoke) to enforce pulling a bundle (and all dependency bundles, if applicable).
A potential complement to https://github.com/deislabs/porter/pull/741
N/A
=> feat(cmd): add --force flag to action commands

pkg/porter/publish.go
As the process of pushing new images for a bundle may take some time prior to the standard output from the `PushBundle(...)` call later on, I wanted to add a simple status message and not just have the command sit there blank, potentially for quite a bit.  Idea shamelessly copied from https://github.com/deislabs/porter/pull/745
N/A
N/A
=> feat(publish.go): print initiation status to console for publishing from an archive

cmd/porter/aliases.go, cmd/porter/bundle.go, cmd/porter/copy.go, docs/config.toml, docs/content/authoring-bundles.md, docs/content/cli/bundles.md, docs/content/cli/bundles_copy.md, docs/content/cli/copy.md, docs/content/cli/porter.md, docs/content/copying-bundles.md, pkg/porter/copy.go, pkg/porter/copy_test.go
This PR adds a new `bundle copy` command that will copy a bundle and it's images from one registry to another.
Also added a side bar link for distributing bundles, since we didn't have that.
```
$ porter copy --source jeremyrickard/porter-do-bundle:v0.4.6 --destination jrrporter.azurecr.io/do-music-bundle:v1.0.0
Beginning bundle copy to jrrporter.azurecr.io/do-music-bundle:v1.0.0. This may take some time.
Starting to copy image jeremyrickard/porter-do:v0.4.6...
Completed image jeremyrickard/porter-do:v0.4.6 copy
Starting to copy image jeremyrickard/spring-music@sha256:8f1133d81f1b078c865cdb11d17d1ff15f55c449d3eecca50190eed0f5e5e26f...
Completed image jeremyrickard/spring-music@sha256:8f1133d81f1b078c865cdb11d17d1ff15f55c449d3eecc …
```
=> Bundle Copy

REVIEWING.md
This way canary doesn't look like it's lagging behind latest which confuses people.
=> Wait for the canary build before tagging a release

cmd/porter/plugins.go, pkg/instance-storage/filesystem/plugin.go, pkg/instance-storage/provider/provider.go, pkg/plugins/server.go, pkg/porter/plugins.go, pkg/porter/plugins_test.go
When we run a plugin, pass the full key so that it knows which implementation to host
`INTERFACE.BINARY.IMPLEMENTATION`
=> Pass full plugin key to plugins

cmd/porter/bundle.go, docs/config.toml, docs/content/archiving-bundles.md, docs/content/distributing-bundles.md
Unhides the `archive` command and adds documentation around `archive` and `publish -a`
This just flips the hidden on archive and adds some docs, so mostly a docs PR. Mostly
- [*] Documentation
=> Unhide the archive command, add some docs about archvice/publish -a

cmd/porter/aliases.go, cmd/porter/bundle.go, cmd/porter/inspect.go, docs/config.toml, docs/content/cli/archive.md, docs/content/cli/bundles.md, docs/content/cli/bundles_archive.md, docs/content/cli/bundles_explain.md, docs/content/cli/bundles_inspect.md, docs/content/cli/inspect.md, docs/content/cli/porter.md, docs/content/distributing-bundles.md, docs/content/examining-bundles.md, docs/content/inspect-bundle.md, pkg/porter/explain.go, pkg/porter/inspect.go
Introduces an `inspect` command that builds on the existing `explain` command, adding the image information so that it's clear what images will be used for a bundle. 
```
$ porter inspect --tag jeremyrickard/porter-do-bundle:v0.5.0
Name: spring-music
Description: Run the Spring Music Service on Kubernetes and Digital Ocean PostgreSQL
Version: 0.5.0
Credentials:
Name               Description                                       Required
do_access_token    Access Token for Digital Ocean Account            true
do_spaces_key      DO Spaces API Key                                 true
do_spaces_secret   DO Spaces API Secret                              true
kubeconfig         Kube config file with permissions to deploy app   true …
```
=> Introduce `inspect` command

pkg/porter/testdata/schema.json, pkg/templates/templates/schema.json
Include customAction definitions in schema.
Closes https://github.com/deislabs/porter-vscode/issues/18
=> Include customAction definitions in schema

pkg/build/build.go, pkg/build/dockerfile-generater.go, pkg/build/dockerfile-generator_test.go, pkg/mixin/helpers.go
This change gives users more control over the generated `Dockerfile` if the local `Dockerfile.tmpl` contains the `# PORTER_MIXINS` instruction, it will be replaced with all mixin docker lines.
If the custom `Dockerfile.tmpl` doesn't container the `INJECT_PORTER_MIXINS_TOKEN`, mixin docker lines will be appended at the end.
Closes #707 
I struggled a bit with the unit test, I wasn't sure how to put a mixin (that will generate docker lines) in the test context. However, the existing test "somehow" validates the implementation because the `INJECT_PORTER_MIXINS_TOKEN` will be replaced with nothing - which turns out to be correct if mixin doesn't specify docker lines.  I'd love to hear someone's feedback regarding my changes to improve my still very basic golang skills 😄 👼
=> Control mixins dockerlines

pkg/build/dockerfile-generator_test.go, pkg/templates/templates/build/Dockerfile, pkg/templates/templates/create/Dockerfile.tmpl
By default inject the mixin dockerfile lines before we copy the bundle files to avoid longer docker build times.
This adds the `# PORTER_MIXINS` line before `COPY . $BUNDLE_DIR` in both the **Dockerfile.tmpl** generated during `porter create` and the **Dockerfile** used during `porter build` when a custom dockerfile wasn't specified.
Follow-up to #707 making the default behavior most likely what the user wanted.
I am writing up full documentation for how to use a custom dockerfile in a separate PR.
=> Inject mixins dockerfile lines before copying bundle files

pkg/kubernetes/build.go
Bumps the kubectl version installed via the kubernetes mixin to the latest (v1.15.x) [v1.15.5 release](https://github.com/kubernetes/kubernetes/releases/tag/v1.15.5)
N/A
N/A
=> chore(pkg/kubernetes): bump kubectl version for k8s mixin

Gopkg.lock, Gopkg.toml, pkg/config/datastore.go, pkg/instance-storage/provider/provider.go, pkg/plugins/plugins.go, vendor/github.com/hashicorp/go-plugin/client.go
Reads optional configuration from the porter configuration file and passes it to the plugin on stdin as json. 
It is not sent as part of the plugin interface/contract because each plugin may or may not have config, it may look completely different or be loaded from other places, and I'd like to have the plugin contract mimic the cnab contracts. For example the interface for claims is the CrudStore.
```toml
default-instance-store = "porterci"
[[instance-store]]
name = "porterci"
plugin = "azure.blob"
[instance-store.config]
env = "PORTERCI_AZURE_STORAGE_CONNECTION_STRING"
```
N/A
This relies on a patch: https://github.com/hashicorp/go-plugin/pull/127
This is the first step in getting a general framework in place for plugins. Next steps after this will be to make the pluginProvider generic …
=> Pass plugin config via stdin

cmd/porter/copy.go, docs/content/cli/bundles_copy.md, docs/content/cli/copy.md
Fixes the whitespace in the long desc for the copy command. It was indented too much and looked bad during a demo last week.
=> Fix whitespace in the copy help text

docs/config.toml
Fix the links for the command navigation in the docs. When we started generating docs, the link format changed.
Closes #789
See https://deploy-preview-792--porter.netlify.com/docs/
=> Fix command nav

docs/content/wiring.md
And a free `bubdle` into the bargain
=> Fix typo in example of image attribute references

cmd/porter/bundle.go, docs/content/cli/publish.md
This just replaces a few tabs with spaces to make the formatting align.
Fix help text spacing for `porter publish -h`
Signed-off-by: Matt Butcher <matt.butcher@microsoft.com>
=> fix: fix spacing to assuage my compulsiveness

docs/content/authoring-bundles.md
We now have support for using all the json schema properties and have for a while. This updates the doc to explain how to use them.
N/A
Preview at https://deploy-preview-798--porter.netlify.com/authoring-bundles/#parameter-and-output-schema
=> Add examples of using json schema with params

docs/content/dependencies.md, pkg/porter/dependencies.go, tests/dependencies_test.go
Until we have access to the manifest consistently across both file based installs and tag based, stop accessing the manifest when installing dependencies since it's not available for tag based installs from the porter client.
Closes #799
This is a temporary fix to avoid the panic. I want the defaulting functionality so will come back and figure out a way to get access to the data in the manifest and put this back in place.
See #800 to turn the feature back on and #801 to figure out how.
=> Temporarily disable parameter defaults for deps

pkg/mixin/feed/generate.go, pkg/mixin/feed/generate_test.go
The heart of this change is that we should always be skipping files that already exist in the feed. Duplications can occur if the first file in the feed, of the same version, were created before the next duplicated file in the `for each`. We can split up the conditional to guarantee duplication are always skipped.
Additionally, changed `.After()` to `.Before()`, as we really only want to update the time if the current file in the feed was modified _before_ the file we're currently looking at in the `for each`.
I also took some liberties with how we were adding `Fileset`s to the collection to (hopefully) make it more readable. We were mixing up value/pointer semantics, and it took a bit to digest.
Let me know if anything needs changing!
Closes #749
=> Fix adding duplicate files

docs/config.toml, docs/content/compatible-registries.md
Document which registries are compatible with CNAB and which ones have been explicitly tested with porter.
Preview at https://deploy-preview-811--porter.netlify.com/compatible-registries/
Part of #809 
This is a bit of an ongoing issue that we will need to keep working on. I've documented what we know so far, but we should test porter with the others and figure out why it doesn't work with some, like quay, and make sure it's not something we can change on our end.
=> List which registries are compatible

Makefile, build/README.md, build/images/README.md, build/images/client/Dockerfile, build/images/workshop/Dockerfile, docs/config.toml, docs/content/docker-images/_index.md, docs/content/docker-images/client.md, docs/content/docker-images/workshop.md, scripts/publish-images.sh
When we cut releases of porter, publish docker images of the porter client and also of our workshop docker image for people to use as well.
Preview at https://deploy-preview-812--porter.netlify.com/docker-images/
The makefile changes are only executed on releases but I did a manual publish so that you can run through the docs to see what the images look like. We publish `latest`, `canary` and `VERSION`.
None, just something that came up in slack.
🦃
=> Publish Docker images during CI

build/azure-pipelines.release.yml
When I added `publish-images` to the `publish` target, I forgot to ensure that we were logged into docker on the CI server so the master release build has been failing for a bit.
=> Do docker login before push docker images on release

mixin.mk
This got missed when I switched to the vanity import path
=> Fix porter version

pkg/cnab/provider/invoke.go, pkg/cnab/provider/invoke_test.go
This PR updates Porter's internal invoke logic to support running stateless actions *without* having claim
```
jeremyrickard@MININT-1L9PE4A:stateless$ rm ~/.porter/claims/*
jeremyrickard@MININT-1L9PE4A:stateless$ porter invoke --action preflight whatsup
invoking custom action preflight on whatsup...
executing preflight action from HELLO (bundle instance: whatsup)
Check the world
The world is good
execution completed successfully!
jeremyrickard@MININT-1L9PE4A:stateless$ tree ~/.porter/claims/
/Users/jeremyrickard/.porter/claims/
0 directories, 0 files
jeremyrickard@MININT-1L9PE4A:stateless$ porter install
installing HELLO...
executing install action from HELLO (bundle instance: HELLO)
Install Hello World
Hello World
execution …
```
=> Update invoke logic to support running stateless actions without a claim

pkg/cnab/config-adapter/adapter.go
Set the output path using Unix path conventions.
Closes https://github.com/deislabs/porter/issues/761
I'm still trying to get a Windows VM set up for testing.  If a Windows user is able to test, this would be very helpful!
=> fix(pkg/cnab): be sure output path uses unix conventions

pkg/build/dockerfile-generater.go, pkg/build/dockerfile-generator_test.go, pkg/templates/templates/build/Dockerfile, pkg/templates/templates/create/Dockerfile.tmpl
This standardizes the contents of the default and template Dockerfile generated by Porter. It also has Porter treat both the same, instead of having conditional logic based on if the user has a template or not.
None, I just noticed in another PR, https://github.com/vdice/porter-packer/pull/1/files/c9b3d6ef73a4212ae2fbfb5f267a6e831cbb2885#diff-39844b97085b014640182ce3ec1e1282, that we were still using an old base image that I had thought that I had removed. Turns out the default Dockerfile and the template are using different base images. It's confusing and I wanted to make it easier for us and users to understand what Porter is doing.
We don't have to merge this, it's just a suggestion to think about.
=> Standardize default and template dockerfiles

pkg/porter/archive.go, tests/archive_test.go
Sets file mode appropriately for archive file and parent directory.  (Neither should be executable.)
Closes #838 
N/A
=> fix(archive.go): update mode on archive file

pkg/porter/outputs.go, pkg/porter/outputs_test.go, pkg/porter/show.go, tests/outputs_test.go
Sets the `Value` field of the `DisplayOutput` object.
Previously, the displayed output in json or yaml would show:
```
$ p instance outputs list basic-tf-example -o yaml
- name: a
definition:
type: string
value: null
displayvalue: |
a
type: string
```
Whereas now it will show:
```
$ p instance outputs list basic-tf-example -o yaml
- name: a
definition:
type: string
value: |
a
displayvalue: |
a
type: string
```
=> fix(outputs.go): set displayOutput.Value

pkg/runtime/runtime-manifest.go, pkg/runtime/runtime-manifest_test.go, pkg/runtime/runtime.go
Improve the error messages when a step fails to render
Print out the yaml that couldn't be marshaled
Dump the step data that couldn't be turned into a step
Use error wrapping properly
Here's the new info dumped when a step can't render:
```
DEBUG: defaulting action to CNAB_ACTION (install)
executing install action from HELLO (bundle instance: HELLO)
Error: unable to resolve step: invalid step yaml
exec:
command: bash
description: Install Hello World
flags:
c: echo "&#34;{&#34;test&#34;: &#34;test&#34;}&#34;"
: yaml: line 5: mapping values are not allowed in this context
```
When I was troubleshooting #846 I needed more info to troubleshoot the problem.
=> Improve step troubleshooting

Makefile, docs/content/archive-bundles.md, docs/content/author-bundles.md, docs/content/dependencies.md, docs/content/faq.md, docs/content/mixin-dev-guide/architecture.md, docs/content/wiring.md, docs/themes/porter/layouts/index.html, pkg/cnab/config-adapter/adapter.go, pkg/cnab/extensions/dependencies.go, workshop/scratch/azure/README.md
Updates the URL for the [CNAB Spec](https://github.com/cnabio/cnab-spec) repository.
Not immediately urgent, as GitHub still handles redirects, but should be updated nonetheless.
N/A
N/A
=> chore(*): update url for cnabio/cnab-spec

docs/config.toml, docs/content/troubleshooting.md, pkg/runtime/runtime-manifest.go, pkg/runtime/runtime-manifest_test.go
Do not encode HTML entities such as quotes when rendering the manifest. I've added some additional debug output and am using the force raw rendering option to ensure that whatever template string the user has defined in the manifest is preserved when we render it.
I've added a troubleshooting page that explains a bug that I keep running into until we fix #851. See https://deploy-preview-852--porter.netlify.com/troubleshooting/
Closes #846 
I've made a follow-up issue, #851, to address how we lose wrapping quotes when we read in the porter manifest. So if they had wrapped their line with `>-` or single quotes or double quotes, we lose it when we read it in and then write it back out.
=> Render manifest template with raw entities

docs/content/custom-dockerfile.md, docs/content/troubleshooting.md
Document requirements for the base image that you may use in your custom Dockerfile.
Closes #844 
🐱
=> Doc that custom dockerfiles must have apt

pkg/cnab/provider/action.go, pkg/config/config.go, pkg/runtime/runtime-manifest.go, pkg/runtime/runtime-manifest_test.go, pkg/runtime/runtime.go, tests/outputs_test.go, tests/testdata/bundles/porter-outputs/Dockerfile, tests/testdata/bundles/porter-outputs/dump-config.sh, tests/testdata/bundles/porter-outputs/porter.yaml
Note: ~~**Do not merge yet**~~ - ~~Blocked by~~/Depends on https://github.com/cnabio/cnab-spec/pull/300
- Adds logic to enable using bundle output values in a Porter manifest via the supported templating language
- As an example, `{{ bundle.outputs.foo }}` can now be used in a step for action `next`, which will pull `foo`'s value from the claim, assuming the action that produced the current claim (say, `install`) produced an output of `foo`.
One caveat here is that currently, until work is done to address https://github.com/deislabs/porter/issues/836, interpolation of these values will only be possible if the previous action supplied the output needed.  Otherwise, outputs don't yet span more than one action _if the actions spanned don't also produce the same output_.
Closes …
=> feat(*): add logic to resolve/interpolate output values in a Porter manifest

Makefile, build/atom-template.xml, build/images/client/Dockerfile, build/images/workshop/Dockerfile, cmd/porter/mixins.go, docs/content/cli/mixins_install.md, docs/content/install.md, docs/content/mixin-dev-guide/commands.md, docs/content/mixin-dev-guide/distribution.md, pkg/exec/version.go, pkg/exec/version_test.go, pkg/kubernetes/version.go, pkg/kubernetes/version_test.go, pkg/mixin/feed/testdata/atom-existing.xml, pkg/mixin/feed/testdata/atom-template.xml, pkg/mixin/feed/testdata/atom.xml, pkg/mixin/install.go, pkg/mixin/provider/install_test.go, scripts/install/install-linux.sh, scripts/install/install-mac.sh, scripts/install/install-windows.ps1
- Updates the cdn url to `https://cdn.porter.sh`
- Updates the mixin author to `Porter Authors`
Ref https://github.com/deislabs/porter/issues/824
Similar to other PRs contributing towards #824, I avoided changes to the `docs/content/slides` and `workshop/` directories.
PRs in the associated mixin repos forthcoming, though this shouldn't necessarily need to block on them.
=> chore(*): update cdn url and mixin author name

build/testdata/bundles/mysql/porter.yaml
- Updates the mysql test/sample bundle to install the latest `stable/mysql` chart (by removing a version override)
- Sets a default value for the `mysql-user` parameter
When testing the bundle (prior to this change) on a k8s cluster of v1.17.0, I was greeted with the following error:
```
...
/usr/local/bin/helm helm install --name porter-ci-mysql stable/mysql --version 0.10.2 --replace --set mysqlDatabase=mydb --set mysqlUser=admin
Error: validation failed: unable to recognize "": no matches for kind "Deployment" in version "extensions/v1beta1"
Error: exit status 1
Error: mixin execution failed: exit status 1
```
Would also be open to just bumping the version to a semver release that fixes the issue mentioned above, if we are hesitant to default to the latest version.  WDYT?
=> ref(mysql/porter.yaml): use latest chart; set mysql-user default

Makefile, docs/content/wiring.md, examples/aks-spring-music/README.md, examples/aks-spring-music/arm/aks.json, examples/aks-spring-music/arm/cosmosdb.json, examples/aks-spring-music/porter.yaml, examples/azure-terraform/README.md, examples/azure-terraform/arm/storage.json, examples/azure-terraform/porter.yaml, examples/azure-terraform/terraform/cosmos-db.tf, examples/azure-terraform/terraform/eventhubs.tf, examples/azure-terraform/terraform/main.tf, examples/azure-terraform/terraform/outputs.tf, examples/azure-wordpress/arm/mysql.json, examples/azure-wordpress/params.ini, examples/azure-wordpress/porter.yaml, workshop/porter-tf-aci/azure/README.md, workshop/porter-tf-aci/azure/bundle/arm/storage.json, workshop/porter-tf-aci/azure/bundle/porter.yaml, workshop/porter-tf-aci/azure/bundle/terraform/main.tf, workshop/porter-tf-aci/azure/bundle/terraform/mysql.tf, workshop/porter-tf-aci/azure/bundle/terraform/outputs.tf, workshop/porter-tf-aci/azure/bundle/terraform/params.tf, workshop/porter-tf/azure/README.md, workshop/porter-tf/azure/arm/storage.json, workshop/porter-tf/azure/porter.yaml, workshop/porter-tf/azure/terraform/main.tf, workshop/porter-tf/azure/terraform/mysql.tf, workshop/porter-tf/azure/terraform/outputs.tf, workshop/porter-tf/azure/terraform/params.tf
Updates/refactors all example and workshop bundles that had previously used the deprecated `azure` mixin to use the `arm` mixin.
In doing so and testing the subsequent bundles, I also sometimes made some tweaks to other aspects of the bundles, for instance, updating terraform and terraform provider versions (and corresponding usage), updating some ARM template values, aligning parameter name formats (usually updating hyphenated params to snake case as the majority dictated), etc.
Closes https://github.com/deislabs/porter/issues/861
Please call out any changes/updates that we don't wish to make at this time.
=> Update bundles per arm mixin usage

build/testdata/bundles/mysql/porter.yaml, docs/content/slides/pack-your-bags-msp/index.md, pkg/porter/outputs.go, pkg/porter/show_test.go, workshop/porter-tf-aci/azure/README.md
Now that outputs aren't stored in porter home anymore, displaying the path inside the bundled runtime to the output doesn't seem helpful for sensitive outputs.
Here is what someone sees when they list outputs in table format:
```
-----------------------------------------------
Name                 Type    Value (Path if sensitive)
-----------------------------------------------
IP_ADDRESS           string  40.88.49.175
STORAGE_ACCOUNT_KEY  string  /cnab/app/outputs/STORAGE_ACCOUNT_KEY
```
Back when the path was a local path to porter home, e.g. ~/.porter/outputs/BUNDLE/STORAGE_ACCOUNT_KEY, it made more sense. They could choose to go look and see if they had permission to view that file. But now that we display a path that is inaccessible, /cnab/app/... isn't available after a bundle has …
=> Show value instead of paths for sensitve outputs

docs/content/how-credentials-work.md, docs/content/use-mixins.md, docs/content/wiring.md
Add documentation on how credentials work internally
Related #854
=> Add documentation on how credentials work internally

pkg/credentialsgenerator/generator.go
Updated the credential generator to ask if a credential should come from a secret.
I have created an issue to better handle this long term, see #875 but for now this will allow people to create credentials backed by the azure plugin (keyvault).
```console
$ porter credentials generate
Generating new credential plugins-demo from bundle plugins-demo
==> 1 credentials required for bundle plugins-demo
? How would you like to set credential "db-password" secret
? Enter the secret that will be used to set credential "db-password" password
$ porter credentials list
NAME           MODIFIED
HELLO          0001-01-01
aws            2019-08-02
plugins-demo   10 seconds ago
$ porter credentials show plugins-demo
Name: plugins-demo
Created: 18 seconds ago
Modified: 18 seconds ago …
```
=> Support generating credentials backed by secrets

docs/content/design/kubernetes-mixin.md, docs/content/faq.md, examples/exec-outputs/create-cluster.sh, examples/kubernetes/README.md
This fixes Issue #886. I originally found this when reading the FAQ.
I was a little confused, and then went searching for other areas
that it might be spelled the same way in the repository, and then
in other projects.
It seems like this is super common. Rather than leave any confusion for 
new project contributors, I'm creating this PR to repair. I couldn't see an 
example spelling PR inthe closed PRs either, so this might be a reasonable
example for future PRs when correcting spelling to add to the contributing doc 
(or as areas where it could be improved.)
Cleans up spelling in documentation and examples
Closes #886
=> Cleaning up the spelling in documentation

CONTRIBUTING.md, README.md, docs/content/contribute.md
Prominently link to our project board from the:
* readme
* contributing guide
* [new contributor guide](https://deploy-preview-893--porter.netlify.com/contribute/#where-should-you-start)
I also threw in what label to _avoid_ in case someone is just looking around the project board for something to do.
None this came up in the dev call today
🐳
=> Link to project board

docs/content/author-bundles.md, pkg/cnab/config-adapter/adapter.go, pkg/cnab/config-adapter/adapter_test.go, pkg/cnab/config-adapter/testdata/porter-with-custom-metadata.yaml, pkg/manifest/manifest.go, pkg/manifest/manifest_test.go, pkg/manifest/testdata/porter.yaml
* [Added] support for a `custom` top-level porter.yaml key
Effect: `custom` accepts a k/v map of [custom extension](https://github.com/cnabio/cnab-spec/blob/master/101-bundle-json.md#custom-extensions) data. Supplied `custom` data is applied first to the bundle and will be overwritten by porter custom extensions.
Closes #888
Example:
```yaml
name: hello
description: "An example Porter configuration"
version: 0.1.0
tag: getporter/porter-hello:v0.1.0
custom:
foo: bar
install:
- exec:
description: "Say Hello"
command: bash
flags:
c: echo Hello World
```
=> Support for CNAB Custom Extensions

pkg/porter/credentials.go, pkg/porter/credentials_test.go
porter credentials show HELLO should query the backend credentials store for a credential set named "HELLO" and not force it to lower-case. The CNAB spec allows for credential sets that use upper-case, and when you generate credential sets for bundles with upper-case letters, it
defaults to the name of the bundle. So we end up with credential sets that depending on the backing store, cannot be read due to forcing to lower-case.
I checked and the other only place we do this is for mixins. I'm going to leave that as-is for now, since perhaps limiting mixins to all lower case is useful? I'll make a follow-up issue to consider if we need to change that too.
https://github.com/deislabs/porter/pull/889/files#r377707582
I've created #897 to look into the mixin question
=> Preserve name casing in credentials show

build/README.md
Link to our azure pipelines pages from the build documentation page so that it's easier for people to find them.
=> Link to azure pipelines from build doc page

docs/content/install.md, pkg/porter/mixins.go, pkg/porter/mixins_test.go, pkg/porter/plugins.go, pkg/porter/plugins_test.go, scripts/install/install-linux.sh, scripts/install/install-mac.sh, scripts/install/install-windows.ps1, scripts/prep-install-scripts.sh, scripts/test/test-linux-install.sh, scripts/test/test-mac-install.sh, scripts/test/test-windows-install.ps1
* Install the azure plugin by default
*  Fix missing newline when installing packages
We lost the \n when printing the success message after installing a mixin or plugin. It wasn't obvious until I went to update the install script and saw the messages printing all on the same line.
*  Update install page
* Include information about plugins
* Do not list each mixin/plugin included in the install script, link to the index page instead.
Closes #772
I need to do a stable release of the azure plugin before this will pass, otherwise `porter plugins install azure` will fail because it doesn't have a `latest` stable release to install.
=> Install azure by default

docs/content/learning.md, docs/themes/porter/layouts/index.html, docs/themes/porter/layouts/partials/nav.html
When I was talking with @karenhchu yesterday she mentioned having a page called learning, and I thought this was a much better name for what we already had with Resources. We can make this page a collection of where to start learning about Porter.
https://deploy-preview-903--porter.netlify.com/ (top nav and scroll down)
https://deploy-preview-903--porter.netlify.com/learning/
None, Karen is a precog. 🤖
I've put in a redirect so that any old links keep working
=> Rename resources to learning

build/README.md, build/azure-pipelines.pr-automatic.yml, build/azure-pipelines.pr-manual.yml, build/doc-only-build.sh
When only documentation files have been modified, skip running jobs for code so that the build completes quickly.
Closes #623
* The porter and porter-integration pipelines will report back but all the jobs inside will have skipped. So they should come back pretty quickly after checking out the code and detecting that it's a doc only change.
* I originally wrote this to compare master..HEAD but azure pipelines checks out the repo in such a way that it doesn't find master. I spent too much time trying to figure that out so I fell back to comparing HEAD~..HEAD instead since on the CI server it's always going to be a merge commit. If you run the script locally it won't work the same. That is something we could improve later if it becomes a problem.
* Once this is merged we can test it out on …
=> Detect documenation only builds

build/doc-only-build.sh
I originally wrote the script to return 0/1 depending on if the build should do a full run or not. Then when I switched to setting azure pipeline variables, forgot to take out the exit statements. 🤦‍♀
=> Always return 0 from doc build check

docs/content/wiring.md
Adds docs/usage around use of file parameters in a Porter bundle.
N/A
N/A
=> docs(wiring.md): add docs/example around file parameter usage

tests/dependencies_test.go
We accidentally were seeding with a constant, so the "random" release names we were generating for our tests actually were the same from test run to test run. Oops...
None, I saw this come up with the CI integration tests failed because it collided with a local integration test run.
Narp
=> Generate unique helm test release names

.github/pull_request_template.md, CONTRIBUTING.md, README.md, docs/content/architecture-buildtime.md, docs/content/architecture-runtime.md, docs/content/contribute.md, docs/content/dependencies.md, docs/content/finding-bundles.md, docs/content/learning.md, docs/content/mixin-dev-guide/distribution.md, docs/content/package-search.md, docs/content/signing-bundles.md, docs/content/use-mixins.md, docs/static/_redirects
The URLs are kind of long and these will help us out if we ever need to change them in the future.
* project board, /board
* label queries on project board, like linking to good first issues and help wanted, e.g. /board/LABEL
* linking back to source code from our website, we can now use `/src/PATH`, e.g. `/src/CONTRIBUTING.md`
* roadmap board
Me typing too much
We can test these url's out on the netlify preview
=> Add redirects for our project boards

pkg/porter/packages_test.go
* Fixes the tests that rely on fetching full package lists for comparison
N/A - Thanks to @carolynvs for spotting and notifying!
=> fix(packages_test.go): sort full list before comparison

pkg/exec/builder/execute.go, pkg/exec/builder/execute_test.go, pkg/pkgmgmt/client/runner_integration_test.go, pkg/pkgmgmt/client/testdata/exec_input.yaml, pkg/pkgmgmt/client/testdata/exec_input_with_whitespace.yaml
Some mixin commands have whitespace and right now we are passing them in as packed into a single array element when executing the command
`exec.Cmd("aws", []string{"ec2", "run-instances", "--security-group-ids group1 group2"})`
When the debug command is printed, we can't tell that this has happened, and why the command failed. What needs to happen is that when there is a space, and it's not enclosed in double quotes, it should be split into its own array element
`exec.Cmd("aws", []string{"ec2", "run-instances", "--security-group-ids", "group1", "group2"})`
I think this will help with https://github.com/deislabs/porter-aws/issues/15
Here is how it would work
```yaml
install:
- aws:
description: "Provision VM"
service: ec2
operation: run-instances
flags:
image-id: ami-xxxxxxxxxxxxxxxxx …
```
=> Split mixin command args by whitespace

cmd/porter/credentials.go, docs/content/cli/credentials_generate.md
Was reading through the docs on the site today and got caught up on "porter bundle credentials generate" then realized its supposed to be "porter credentials generate"
=> Fix help text for porter credentials

docs/content/best-practices/exec-mixin.md, docs/content/mixins/exec.md, examples/exec-outputs/README.md, examples/exec-outputs/cluster.sh, examples/exec-outputs/dump-config.sh, examples/exec-outputs/generate-config.sh, examples/exec-outputs/porter.yaml
Explain how to use the exec mixin without shooting yourself in the foot.
Follow-up to #931
😝
=> Add best practice for the exec mixin

build/azure-pipelines.pr-automatic.yml, build/azure-pipelines.pr-manual.yml, pkg/cnab/provider/invoke.go, pkg/cnab/provider/invoke_test.go
* During invoke, when we cannot find the requested claim, and it is required for the action, stop immediately and report the error to the user.
* I updated the error message so that it matches what is returned by upgrade when the claim doesn't exist.
* Run CI against release candidate PRs
Because we have changes in master that aren't ready to go in a release, I am making this a patch against the last release. Note that the branch this PR is open against is`release-0.24.1-beta.1` which is the desired next version (I branched off of `v0.24.0-beta.1`).
To facilitate this PR, I updated our azure pipelines to run against PRs targeting `release-*` branches.
Closes #948 
What the user was really doing was this
```
porter uninstall mybuns
porter invoke --action uninstallCleanup
```
Where the …
=> Stop invoke when claim not found

docs/config.toml
Link to top level command resources, e.g. bundle, credentials
instead of to each individual command from the side bar. This keeps the
side nav more manageable to navigagte and to keep updated.
https://deploy-preview-957--porter.netlify.com/docs/
Keeping the side-bar up-to-date and not scrolling forever on small screens.
Do you think this is a good change?
=> Simplify porter command navigation

pkg/build/provider/docker.go, tests/build_test.go
* Adds appropriate exclusions to the Docker build context per the `.dockerignore` in the working directory
Closes https://github.com/deislabs/porter/issues/960
N/A
=> fix(docker.go): read .dockerignore file for appropriate build exclusions

docs/content/mixins/exec.md
Document how to use the supress-output field for the exec mixin.
https://deploy-preview-963--porter.netlify.com/mixins/exec/#suppress-output
Follow-up to #956 
Once we implement this and release it for other mixins, let's make sure to document it on their READMEs on the repo and include similar instructions on the mixin documentation on the porter website.
=> Document suppress-output for the exec mixin

docs/content/plugins/_index.md
People may come to the listing page for plugins /plugins to understand
what plugins are. Make sure we have some introductory text there that
leads them to the more detailed plugin types page and the plugins vs
mixins page as well.
https://deploy-preview-966--porter.netlify.com/plugins/
This is based on feedback given from users on the /plugins page.
🐱
=> Explain plugins on the listing page

docs/content/mixins/aws.md, docs/content/mixins/az.md, docs/content/mixins/exec.md, docs/content/mixins/gcloud.md
Document suppress-output for aws, az, and gcloud. Also updated exec to match the wording used by the other mixins for consistency.
https://deploy-preview-965--porter.netlify.com/mixins/aws/
https://deploy-preview-965--porter.netlify.com/mixins/az/
https://deploy-preview-965--porter.netlify.com/mixins/exec/
https://deploy-preview-965--porter.netlify.com/mixins/gcloud/
Final follow-up to #956.
🐶
=> Document suppress-output for mixins that support it

pkg/pkgmgmt/feed/generate.go, pkg/pkgmgmt/feed/generate_test.go
* Updates the mixin regex that `generate.go` uses to allow for alphanumeric mixin names
* `Generate(...)` now returns an error if no entries were created
@MChorfa noted that running `porter mixin feed generate ...` failed for a mixin named [helm3](https://github.com/MChorfa/porter-helm3):
```shell
~/go/src/github.com/porter-helm3 ϟ porter mixins feed generate -d bin/mixins -f bin/atom.xml -t build/atom-template.xml
panic: runtime error: index out of range [0] with length 0
```
It appears that this mixin name did not match the previous version of the regex (it precluded numeric characters), so we ended up with an empty list of entries when we tried to save the generated feed.  Therefore, a bit of logic has been added to fail faster if no entries are generated in the `Generate(...)` method. …
=> fix(generate.go): update mixin regex; add tests

pkg/pkgmgmt/feed/generate.go, pkg/pkgmgmt/feed/generate_test.go
* Updates the mixin regex that the feed generate logic uses to allow for hyphens
Say, for a forthcoming `docker-compose` mixin!
N/A
N/A
=> feat(generate.go): update the mixin regex to support hyphens

pkg/cache/cache.go, pkg/cache/cache_test.go, pkg/cnab/config-adapter/stamp.go, pkg/cnab/config-adapter/stamp_test.go, pkg/porter/dependencies.go, pkg/porter/lifecycle_test.go
v0.26.0-beta.1 (specifically #976) caused a regression where an error aborted actions that relied on the bundle instance name to identity and retrieve the bundle.
* Some porter bundles will have a stamp, but not an embedded manifest. Gracefully handle this when caching the bundle, and return hard errors when people try to read the manifest out of the cache.
* Previously we were accidentally ignoring errors when bundle load failed in the dependencies code. This helped cover up not handling when the bundle was supplied through just an instance name. In the latest release, I fixed the lack of error handling but didn't catch that the
code wasn't loading bundles from the claim name too (just from the file or tag). This adds in logic to also load the bundle from an instance name.
Closes #981 …
=> Fix regression in loading bundle from claim

pkg/cnab/extensions/docker.go, pkg/cnab/extensions/docker_test.go, pkg/cnab/provider/driver.go, pkg/porter/testdata/schema.json, pkg/templates/templates/schema.json
*  Default docker extension config to empty, not nil
When reading the docker required extension config from the porter.yaml,
when none is specified, return an empty docker config, not nil. Also
I've changed the signature so that the docker config is a struct not
pointer, to make it clear it's required and avoid a nil reference
exception.
* Fix schema for docker required extension
Allow for an entry that is just the name
```
required:
- docker
```
and for a required extension with config
```
required:
- docker:
privileged: true
```
Closes #983
🥧
=> Fix docker required extension schema and processing

pkg/porter/testdata/schema.json, pkg/templates/templates/schema.json
The invocationImage field in porter.yaml is now optional, so remove it from the required list in the schema.
Closes #383 
=> Update schema to set invocation image optional

pkg/claims/migrateClaimsWrapper_test.go
Apparently, this particular test may fail in [CI](https://dev.azure.com/deislabs/porter/_build/results?buildId=5777&view=logs&j=dc3bdf25-abe2-53a3-4b0b-7fee357bcfdc&t=0e2fdf7b-745b-5b2f-40e5-29886a6d1e8c).
In the test, we were adding each claim in order and checking the list against that order, but perhaps there's a race if we rely on the stock list order (by date).  Let me know if the quick fix of sorting by name and checking against that order isn't desired.
N/A
N/A
=> fix(migrateClaimsWrapper_test.go): sort list before validation

pkg/build/dockerfile-generator_test.go, pkg/mixin/helpers.go, pkg/mixin/query/query.go, pkg/pkgmgmt/client/helpers.go, pkg/porter/run_test.go
* updates logic in `query.go` to return mixin errors
It appears we hadn't actually been returning mixin errors if they occurred during mixin build invocations (e.g. when assembling the mixin section of the invocation image Dockerfile).  This makes sure we capture such errors and halt the bundle build appropriately.
N/A
Note the changes in order to cover under test.  Open to suggestions on a different way.
=> fix(query.go): actually propogate mixin runErr

pkg/cache/cache.go, pkg/cache/cache_test.go
When we refresh the cached files for a bundle, delete the old directory so that any files that would not be overwritten, for example the updated bundle doesn't have a relocation mapping file or manifest, are removed.
Fixes #991
As a follow-up I am working on #992 since per the original issue, they are using `porter explain` which doesn't have a `--force` flag to make it easy for them to repull the bundle and use this fix.
=> Remove old cached bundle on refresh

cmd/porter/bundle.go, cmd/porter/credentials.go, cmd/porter/explain.go, cmd/porter/inspect.go, docs/content/cli/archive.md, docs/content/cli/bundles_archive.md, docs/content/cli/bundles_explain.md, docs/content/cli/bundles_inspect.md, docs/content/cli/credentials_generate.md, docs/content/cli/explain.md, docs/content/cli/inspect.md, pkg/cnab/cnab-to-oci/helpers.go, pkg/cnab/cnab-to-oci/provider.go, pkg/cnab/cnab-to-oci/registry.go, pkg/porter/porter.go, pkg/porter/resolver.go, pkg/porter/resolver_test.go
* Add --force flag to commands that pull tags
Any command that pulls a bundle using --tag also needs its buddy flag --force so that it can repull when the bundle has been repushed, and the bundle needs to be repulled (the cached bundle refreshed).
This adds --force to the following commands:
* inspect
* explain
* credentials generate
* archive
* Skip cache query on --force
When --force is specified do not query the cache at all, immediately skip to pulling the bundle again. This helps avoid any errors that could arrise from an invalid cached bundle.
Closes #992 
🍰
=> Add --force flag to commands that pull tags

CONTRIBUTING.md, CONTRIBUTION_LADDER.md, docs/content/contribute.md
Split up the mega contributing guide a bit, by moving the contribution ladder into its own document.
Also removed references to dep, since we are using go mods now.
None
Maybe want to do the same for the development, but I wanted to start small.
=> Move contribution ladder into separate document

go.mod, go.sum, pkg/cnab/provider/parameters.go, pkg/cnab/provider/parameters_test.go
* Removes custom logic to supply a zero/empty or default value for parameters when they don't apply to a given action.  This had been added to appease cnab-go validation.  However, said validation is proposed to be changed in https://github.com/cnabio/cnab-go/pull/204.
Depends on https://github.com/cnabio/cnab-go/pull/204
TODO:
Unintended behavior may result from populating parameters with zero/empty values even if not applicable to a given action.
One of the subtle effects of the previous behavior is parameter persistence.  Since zero or default values (the default may originate from a previous claim value) are no longer being provided for parameters that don't apply to a particular action, these values will no longer 'persist' across actions.  
For example, if a value of 'foo' was …
=> ref(parameters.go): remove zero value/default param logic

docs/content/compatible-registries.md
Updates documentation on supported registries. GitHub Packages has limited support currently. porter publish will fail to GitHub Packages. This just updates the documentation to reflect this.
Source: https://help.github.com/en/packages/publishing-and-managing-packages/about-github-packages
Closes #695
=> Document GitHub Package Registry failure

.github/workflows/assign-issues.yaml, .github/workflows/assign-pr.yaml
Automatically assign new issues and pull requests to our main project board, https://github.com/orgs/deislabs/projects/2
This will save us time adding issues to the board. Existing issues are not added but this should help going forward.
It was tested on https://github.com/deislabs/porter-test/issue
=> Assign issues and PRs to our project board

CONTRIBUTING.md, CONTRIBUTION_LADDER.md
Incorporate review feedback from https://github.com/deislabs/porter/pull/1001#issuecomment-616718612
=> Fix missing slack link

pkg/build/provider/docker.go
Remove immediate containers after innovation image built in docker provider's build action.
Make `Remove` flag true for using docker provider to build invocation image. This parameter will make docker remove all immediate containers after invocation image built, and this will reduce disk usage.
This flag is same with `docker build --rm`
=> remove immediate containers after innovation image built in docker provider's build action

build/testdata/bundles/terraform/terraform/main.tf, build/testdata/bundles/terraform/terraform/outputs.tf
A wee PR to update pertinent `.tf` files in the terraform bundle per the mixin terraform version (`0.12.17` at time of writing):
```
Warning: Interpolation-only expressions are deprecated
on main.tf line 2, in resource "local_file" "foo":
2:     content  = "${var.file_contents}"
Terraform 0.11 and earlier required all non-constant expressions to be
provided via interpolation syntax, but this pattern is now deprecated. To
silence this warning, remove the "${ sequence from the start and the }"
sequence from the end of this expression, leaving just the inner expression.
Template interpolation syntax is still used to construct strings from
expressions when the template includes multiple interpolation sequences or a
mixture of literal strings and interpolations. This deprecation applies only …
```
=> ref(bundles/terraform): update terraform bundle

docs/content/author-bundles.md
* Fix formatting for required docker extension. The heading/text was ending up on the same line.
* Also tweak the text to improve clarity and make sure people understand the default value (false).
N/A
Just found this while writing up a blog post about our docker support.
=> Fix formatting for required docker extension

build/testdata/bundles/terraform/porter.yaml, pkg/manifest/manifest.go, pkg/runtime/runtime-manifest.go, pkg/runtime/runtime-manifest_test.go
* Do not inject parameters into the manifest template that do not apply to
the current action.
* Do not process file type parameters that do not apply to the current
action.
Closes #1016 
I looked around in the cnab/provider actions and the usages of the manifest parameters but couldn't think of where else we should be limiting by appliesTo.
I have a follow-up https://github.com/deislabs/porter/issues/1018 to have the linter catch people using `{{bundle.parameters.foo}}` in actions where it doesn't apply.
=> Skip params at runtime that don't apply

go.mod, go.sum
* Removes branch override of cnab-go dep
* Bumps to latest tag
N/A
N/A
=> chore(go.mod): bump cnab-go dep

CONTRIBUTING.md
In the initial setup, I was getting an error following
```
go get -u  get.porter.sh/porter
package get.porter.sh/porter: no Go files in /Users/sigje/go/src/get.porter.sh/porter
```
This commit cleans up the documentation around initial setup to match what I think
is going on more closely.
Closes #1020 
A couple of issues to think about:
* get.porter.sh url versus GitHub
* meta around what install does and whether more process documentation is needed around setup. 
I'm not sure whether there is a get.porter.sh url that would work for cloning directly. 
This
```Cloning into 'porter'...
fatal: unable to update url base from redirection:
asked for: https://get.porter.sh/porter/info/refs?service=git-upload-pack
redirect: https://github.com/deislabs/porter
```
didn't work and maybe there is a …
=> Cleaned up documentation for initial setup for developer tasks.

pkg/manifest/manifest.go, pkg/manifest/manifest_test.go, pkg/manifest/testdata/missing-invocation-image-tag-has-port.porter.yaml
* Updates default invocation image naming to allow for registries of the domain:port pattern
N/A, but discovered via investigation into https://github.com/deislabs/porter/issues/1030
N/A
=> fix(manifest.go): update default invocation image naming

docs/content/copy-bundles.md
The link had the markdown syntax for links flipflopped
See https://deploy-preview-1048--porter.netlify.app/copy-bundles/
N/A
N/A
=> Fix link on copy bundles page

build/azure-pipelines.pr-automatic.yml, build/azure-pipelines.pr-manual.yml, build/azure-pipelines.release.yml, build/azure-pipelines.setup-go-workspace.sh
Azure Pipelines has changed how go is set up on their environments. Instead of using a script to configure GOROOT, we should now use the GoTool task. We still need an extra script to add GOPATH/bin to PATH since we rely on using tools installed there, like packr.
Our builds were failing because as part of this GOROOT moved from `/usr/local/go1.13` to `/usr/local/go1.13.PATCH` which since we don't actually specify patch, was a bit hard to intuit. 😅
https://docs.microsoft.com/en-us/azure/devops/pipelines/ecosystems/go?view=azure-devops&tabs=go-current#set-up-go
=> Use GoTool Task

docs/content/author-bundles.md, docs/content/wiring.md
* Adds documentation around a few additional configuration options for parameters
Closes https://github.com/deislabs/porter/issues/934
=> docs(*): add a few missing parameters config items

docs/content/distribute-bundles.md
* Amends a few typos and/or areas of text
N/A, discovered after revisiting docs
=> docs(distribute-bundles.md): minor amendments

cmd/porter/bundle.go, docs/content/cli/archive.md, docs/content/cli/bundles_archive.md
* Updates `archive` cmd usage to show that a destination filename is currently mandatory
N/A, noticed while reading docs in this area.
It could be neat to file an enhancement wherein the destination filename could be optional.  If not provided, it could perhaps be auto-derived from the provided manifest or bundle.json?  Thoughts?
=> fix(cmd/porter/bundle.go): update archive cmd text

docs/content/distribute-bundles.md, pkg/porter/publish.go, pkg/porter/publish_test.go
Don't use a string replace because when the same text is used in the org
and the image name and the registry, it can end up changing more text
than it should.
Don't replace the org when there isn't one present. Some registries
embed the org in the domain, e.g. getporter.azurecr.io, in which case
the path of the tag is the name of the bundle, and we shouldn't be
appending that to the images.
Closes #1040 
=> Selectively replace the org when moving images

build/azure-pipelines.pr-manual.yml
I'm not sure why this was implicitly running a build before... Let's make it explicit since a minor change to the Makefile caused the implicit run of the build target to go away and break CI.
We don't make it a hard dependency in the Makefile because this lets you iterate on just the test without doing a full rebuild inbetween.
I am hoping this fixes the weird broken integration test run for #1028 🤞
=> Run build before integration test

pkg/cnab/provider/credentials.go, pkg/cnab/provider/credentials_test.go, pkg/cnab/provider/helpers.go, pkg/cnab/provider/testdata/db-creds.json
When credentials were refactored to support secret stores, there was a regression around loading credentials by path. This allowed people to supply a one-off credential set when running a bundle and has now been corrected.
e.g. `porter install -c ./mycreds.json`
Closes #988 
🐶
=> Fix specifying credentials by path

docs/content/author-bundles.md, docs/content/distribute-bundles.md, examples/airgap/.dockerignore, examples/airgap/charts/whalegap/.helmignore, examples/airgap/charts/whalegap/Chart.yaml, examples/airgap/charts/whalegap/templates/NOTES.txt, examples/airgap/charts/whalegap/templates/_helpers.tpl, examples/airgap/charts/whalegap/templates/deployment.yaml, examples/airgap/charts/whalegap/templates/ingress.yaml, examples/airgap/charts/whalegap/templates/service.yaml, examples/airgap/charts/whalegap/templates/serviceaccount.yaml, examples/airgap/charts/whalegap/templates/tests/test-connection.yaml, examples/airgap/charts/whalegap/values.yaml, examples/airgap/porter.yaml
Add an example of shoving a bundle over an airgap. 🐳 💨🚜 
TODO:
Needed it for a demo and people asked a lot about it in Slack.
* As I wrote this I realized that our docs don't explain how to do this, so there will be follow-up PRs.
* Found a bug in how we rename images when we copy them to another registry, need to split that out into another PR. It's in here because it broke my demo...
=> Add airgap example

docs/config.toml, docs/content/wiring.md
* Adds sidebar links to relevant Parameters documentation
* Fixes link typo
Docs preview: https://deploy-preview-1093--porter.netlify.app/
n/a
n/a
=> docs(*): add parameters links to config; fix typo

cmd/porter/credentials.go, cmd/porter/parameters.go, docs/content/cli/credentials_generate.md, docs/content/cli/parameters_generate.md
removes dry-run flag from `porter credentials generate` and `porter parameters generate`
Closes #1086 
Very tiny fix but working my way throughout the project and can contribute saner PRs in the future :)
=> remove dry-run flags

pkg/porter/credentials.go, pkg/porter/parameters.go
This removes the dry-run implementation that was backing the --dry-run flags for parameters and credentials. Now that the flag is gone, we don't need it anymore.
Follow-up to #1094 
Delete ALL THE CODE 🔥
=> Remove dry-run backend implementation

docs/content/archive-bundles.md, docs/content/examine-bundles.md, docs/content/plugin-tutorial.md, pkg/porter/explain.go, pkg/porter/testdata/explain/expected-json-output.json, pkg/porter/testdata/explain/expected-table-output.txt, pkg/porter/testdata/explain/expected-yaml-output.yaml
Don't show internal params in output of `explain`
Closes #1091 
=> Remove internal params in `explain` output

.github/pull_request_template.md, CONTRIBUTING.md, CONTRIBUTORS.md, README.md
This works around a bug/limitation in GitHub where you lose your contributor status to the project when you disassociate the email that you contributed with from your GitHub profile. Basically when you change jobs, it looks like you never contributed which is unacceptable to us.
So we will ensure contributors are acknowledged and thanked via a Contributors file and properly link it so people know to use it.
INJUSTICE  ✊ 
* let's make sure all my new links work
=> Add contributors file

build/azure-pipelines.pr-automatic.yml, build/azure-pipelines.pr-manual.yml
We are using release/VERSION instead of release-VERSION, to take advantage of tooling that collapses releases.
Allow for triggering tests against other gitflow named branches as well.
Being able to run tests against non-main branches.
Reduce/Reuse/Recycle
=> Put release branches in a "directory" structure

pkg/plugins/pluggable/loader.go, pkg/storage/filesystem/store.go
The integration tests don't use the PORTER_HOME env var, they programmatically set the porter home directory on the porter app. So when Porter creates a plugin, we need to explicitly set the home dir on the plugin when it's instantiated since it won't get PORTER_HOME automatically.
Running integration tests and having it act against your real porter install. 😱 
I have heartburn right now. 🚒
=> Set PORTER_HOME in integration tests on plugins

pkg/cnab/extensions/solver_test.go
We were relying on an array order that was generated from iterating upon a map. So it was unreliable in our tests. This ensures that we are looking at the correct elements when evaluating the test results.
Closes #1119
Oops, sorry I wrote this test. 🤦‍♀️
=> Fix TestDependencySolver_ResolveDependencies Flake

cmd/porter/main.go, cmd/porter/version_test.go, docs/content/cli/porter.md
People never know if a CLI supports --version or a version command. So let's just support both so whatever they try will work. MAGIC!
Fighting muscle memory
Inspired by https://twitter.com/michellenoorali/status/1280517451550199808
=> Add --version flag to porter

pkg/manifest/manifest.go, pkg/manifest/manifest_test.go, pkg/porter/publish.go
* Updates `porter publish` logic such that the invocation image name is updated when a bundle tag value (via `--tag`) is provided.  The updated image name inherits the registry and docker tag from the provided bundle tag value.
* A bit of refactoring was introduced to consolidate this image naming logic for use by multiple areas (in this case, publish as well as setting defaults on the manifest)
Closes https://github.com/deislabs/porter/issues/1123
=> feat(publish.go): update invocation image per bundle tag on publish

pkg/porter/publish.go, pkg/porter/publish_test.go
When we go to update an invocation image based on a bundle tag, there were some cases when the resulting image had an incorrect or unexpected name.  This logic currently is used by `archive` but may also come in handy for `publish` if/when https://github.com/deislabs/porter/pull/1127 is merged.  As a bonus, this area of code has been simplified while implementing the fix.
One obvious case of brokenness was when the invocation image had a registry but no org:
```
t.Run("has registry, no org", func(t *testing.T) {
newInvImgName, err := getNewImageNameFromBundleTag("localhost:5000/apache-installer", "example.com/neworg/apache:v0.1.0")
require.NoError(t, err, "getNewImageNameFromBundleTag failed")
assert.Equal(t, "example.com/neworg/apache-installer", newInvImgName.String())
})
```
Yielded: …
=> fix(publish.go): fix certain cases around image name updating

pkg/cnab/config-adapter/stamp.go, pkg/cnab/config-adapter/stamp_test.go, pkg/porter/build_test.go
* Adds the in-memory manifest image name to the data to digest
A bit of a follow-up to https://github.com/deislabs/porter/pull/1127.  We now update the image name on-the-fly on `porter publish` if/when a different bundle tag is supplied.  However, to properly trigger a rebuild prior to publishing, we need to capture this update which doesn't exist in the manifest file itself (and won't be saved there, either).
N/A; described above
=> feat(stamp.go): add image name to manifest digest

build/azure-pipelines.pr-automatic.yml, build/azure-pipelines.release.yml, build/run-integration-tests.sh
* Updates the test-integration steps in corresponding azure pipelines to call out to script
Follow up to https://github.com/deislabs/porter/pull/1138, per https://github.com/deislabs/porter/pull/1138/files#r456589804
=> fix(build): update azure pipelines to call integration test script

docs/content/author-bundles.md
* Adds a field listing and other clarifications to the Images section of the Author Bundles doc
Closes https://github.com/deislabs/porter/issues/1037
Closes https://github.com/deislabs/porter/issues/1036
=> docs(author-bundles.md): add field listing and clarifications to images section

docs/content/author-bundles.md, docs/content/build-image.md, docs/content/distribute-bundles.md, docs/content/mixin-dev-guide/architecture.md, pkg/cnab/config-adapter/stamp_test.go, pkg/manifest/manifest.go, pkg/manifest/manifest_test.go, pkg/manifest/testdata/porter-with-image.yaml, pkg/porter/publish.go, pkg/porter/testdata/porter.yaml, pkg/porter/testdata/schema.json, pkg/templates/templates/schema.json
* Removes ability to specify an invocation image name in the Porter manifest
Closes https://github.com/deislabs/porter/issues/1132
A couple questions:
- The current approach explicitly errors out if the `invocationImage` is present in the manifest.  What do we think?
- Did I visit all of the known places where logic can be simplified now that this value can't be user-specified?
=> ref(*): remove invocation image from the Porter manifest

docs/content/mixins/exec.md, pkg/exec/action.go, pkg/exec/exec_test.go, pkg/exec/schema/exec.json, pkg/exec/testdata/suffix-args-input.yaml, pkg/porter/testdata/schema.json
Implement the HasOrderedArguments interface on the exec mixin supporting @Nunix's scenario of using suffix arguments with the exec mixin.
example:
```yaml
install:
- exec:
description: "Run uname via ssh"
command: ssh
arguments:
- somehost
flags:
l: username
p: port
suffix-arguments:
- uname
```
Closes #806
NA
=> Add suffix arguments to exec mixin

cmd/porter/installations.go, pkg/porter/list.go, pkg/porter/show.go, pkg/porter/show_test.go, pkg/printer/table.go
* Show installation history
Print out the history of what has happened to a bundle installation, instead of just the last action when you run `porter show`. I've added a new printer method that prints out a table section and I'll follow up and redo other sections so that they use it too.
*  Hold open plugin connection during schema migration
Make sure we don't open/close the plugin connection during the schema migration check. Then Bubble through the Connect call to the wrapped backing store.
Closes #1064
I removed the "last action" and "last status" from the show fields since we now display that data in the History table.
=> Show installation history

pkg/porter/cnab.go, pkg/porter/cnab_test.go, pkg/porter/install.go, pkg/porter/invoke.go, pkg/porter/lifecycle_test.go, pkg/porter/options.go, pkg/porter/parameters.go, pkg/porter/testdata/paramset-with-file-param.json, pkg/porter/testdata/porter-with-file-param.yaml, pkg/porter/uninstall.go, pkg/porter/upgrade.go, tests/install_test.go, tests/testdata/bundle-with-file-params.yaml, tests/testdata/myotherfile, tests/testdata/parameter-set-with-file-param.json
* Adds support for sending in parameters designated as type `file` in the Porter manifest via Parameter Sets
Closes https://github.com/deislabs/porter/issues/1130
📁 
=> fix(*): update parameter set logic to support file types

cmd/porter/installations.go, go.mod, pkg/claims/claimStorage.go, pkg/claims/helpers.go, pkg/claims/migrateClaimsWrapper.go, pkg/claims/migrateClaimsWrapper_test.go, pkg/credentials/credentialStorage.go, pkg/credentials/helpers.go, pkg/porter/credentials_test.go, pkg/porter/helpers.go, pkg/porter/list.go, tests/claim_migration_test.go
* Make sure we don't open/close the plugin connection during the schema migration check.
* Bubble through the Connect call to the wrapped backing store.
* Use the same backing store for the manual data access and the claim store.
Reduces unnecessary connection open/close caused by wrapping our claims data access with the migration data structure.
Required a PR to cnab-go, so that will need review first. https://github.com/cnabio/cnab-go/pull/225
=> Hold open plugin connection during schema migration

build/azure-pipelines.pr-automatic.yml, tests/claim_migration_test.go
I messed up the syntax for triggering a build for any branch name. This should get integration tests running when the branch name has a `/` in it, e.g. `release/0.28.0`
The broken integration test build on https://github.com/deislabs/porter/pull/1145
Regex is hard
=> Trigger build all branches

.github/invite-contributors.yml, CONTRIBUTING.md
Automatically add new contributors to our Porters team so that they can have issues assigned to them and generally interact with our repos/org later. Right now I do this by hand and sometimes miss people.
This uses the https://github.com/erickzhao/invite-contributors GitHub app.
Me missing people...
NA
=> Add new contributors to Porter team

pkg/porter/archive.go, pkg/porter/archive_test.go
* Adds logic to error out if the parent directory for the provided archive filepath does not exist
Closes https://github.com/deislabs/porter/issues/1169
I first placed the logic in the `Validate` function with a direct `os` call but I then remembered that we probably want to use Porter's filesystem from its config; therefore, the logic was placed in `Archive` itself.
=> fix(archive.go): return error if parent dir of dest file does not exist

pkg/cnab/extensions/parameter_sources.go, pkg/cnab/extensions/paramter_sources_test.go
I am using append when listing parameter sources but then forget to set the array size to 0...
I found this when helping MChorfa with the same code for dependencies.
N/A
=> Fix listing of parameter sources in order

pkg/porter/build_test.go, pkg/templates/templates/create/porter.yaml
This updates the porter.yaml template that is used with porter create:
* Give example for parameters and link in comments https://porter.sh/author-bundles/#parameters
* Link to documentation for customizing the dockerfile within the sample porter.yaml template
* Link to updated credentials page https://porter.sh/author-bundles/#credentials
This cleans up the testing and documentation that includes the sample template in a number of pages. This includes 
* Removing hard-coded version in the manifest tag
* Removes invocationImage from manifest examples related #1140
None, just noticed that we could do better when reviewing #1171  💪 
Fixes Issue #1146
NA
=>  Update porter.yaml template and clean up documentation and test data that use manifest template

CONTRIBUTING.md, Makefile, build/azure-pipelines.pr-automatic.yml, build/azure-pipelines.release.yml, build/brigade.js, build/run-integration-tests.sh
* Adds logic to run the necessary local registry targets when running the CLI and integration tests
N/A
N/A
=> fix(Makefile): wire up local registry targets for cli and int tests

Makefile
Updates check in make file for GOPATH/bin in PATH to use =~ rather than extglob which when turned off results in the issue reported in #1169
=> fix check for GOPATH/bin

go.mod, go.sum
Update cnab-go to get fix for [#226 - Fix error listing outputs when bundle definition changed](https://github.com/cnabio/cnab-go/pull/226)
Closes #1164
The fix and test is in cnab-go, we just needed to get the latest version.
=> Bump cnab-go v0.13.3

Makefile
* Updates the `sed` command (used by the `init-porter-home-for-ci` make target) to be Mac OSX/BSD-friendly
N/A
Hoping for confirmation that this works by @donmstewart when convenient :)
=> fix(Makefile): update sed command for compat w/ Mac/BSD sed

cmd/porter/bundle.go, docs/content/archive-bundles.md, docs/content/cli/archive.md, docs/content/cli/bundles.md, docs/content/cli/bundles_archive.md, docs/content/cli/porter.md, pkg/porter/archive.go, pkg/porter/archive_test.go, tests/archive_test.go
* Updates the archive command to require a bundle tag (and remove the local options)
Closes https://github.com/deislabs/porter/issues/1100
Closes https://github.com/deislabs/porter/issues/697
* Do we want to add further color in the documentation around why publishing is required first?  (e.g. CNAB Spec requires contentDigests for all images)
=> ref(archive): update archive command to require --tag

cmd/porter/bundle.go, cmd/porter/credentials.go, cmd/porter/explain.go, cmd/porter/inspect.go, cmd/porter/main.go, cmd/porter/parameters.go, docs/content/cli/archive.md, docs/content/cli/bundles_archive.md, docs/content/cli/bundles_explain.md, docs/content/cli/bundles_inspect.md, docs/content/cli/bundles_install.md, docs/content/cli/bundles_invoke.md, docs/content/cli/bundles_uninstall.md, docs/content/cli/bundles_upgrade.md, docs/content/cli/credentials_generate.md, docs/content/cli/explain.md, docs/content/cli/inspect.md, docs/content/cli/install.md, docs/content/cli/invoke.md, docs/content/cli/parameters_generate.md, docs/content/cli/publish.md, docs/content/cli/uninstall.md, docs/content/cli/upgrade.md, pkg/cnab/cnab-to-oci/registry.go
All commands that have --tag should also have --force and --insecure-registry (except publish which doesn't have --force because it's not pulling). Define the flags in a single location so that we can make sure they are consistntly applied to commands that support --tag.
Closes #1092 
I updated the examples to move the --tag examples higher up since that's much more common than --file or --cnab-file and demo how to use --insecure-registry and --force.
=> Ensure tag flags are applied consistently

docs/content/best-practices/github-workflow.md
This doc explains how to set up a GitHub workflow in your repository to test your bundle. This is needed to complement the Porter GH action and make it more usable. It shows how you can use the Porter GH action in conjunction with more steps to create a pipeline for your bundle.
=> doc to explain github workflow

docs/content/docker-images/client.md, docs/content/mixins-vs-plugins.md, docs/content/plugins/_index.md, docs/content/plugins/azure.md, docs/content/plugins/types/_index.md, pkg/cnab/provider/parameters_test.go, pkg/config/config.go, pkg/porter/cnab.go, pkg/porter/lifecycle_test.go, pkg/porter/list.go, pkg/porter/options.go, pkg/porter/outputs.go, pkg/porter/show.go, pkg/runtime/runtime.go
* Updates code, comments and docs where appropriate re: updated installation record structure
Closes https://github.com/deislabs/porter/issues/1105
=> ref(*): misc code, comment, docs updates around claims

Makefile
I was running into errors running the integration tests because the local docker registry container was already stopped so kill was failing. This improves the `stop-local-docker-registry` target to handle when the container is already stopped (I think my computer went to sleep or something).
N/A
N/A
=> Handle removing stopped local registry in  stop-local-docker-registry

pkg/porter/cnab.go, pkg/porter/lifecycle.go, pkg/porter/lifecycle_test.go
if `--tag` passed, porter still tries to validate local manifest file. This PR skips validating manifest file if `--tag` present
Closes #1180
N/A
=> 🐛 Skip bundle defaults if --tag passed

cmd/porter/bundle.go, cmd/porter/installations.go, docs/content/cli/bundles_uninstall.md, docs/content/cli/installations.md, docs/content/cli/installations_delete.md, docs/content/cli/uninstall.md, pkg/cnab/provider/helpers.go, pkg/context/helpers.go, pkg/porter/delete.go, pkg/porter/delete_test.go, pkg/porter/dependencies.go, pkg/porter/helpers.go, pkg/porter/install.go, pkg/porter/invoke.go, pkg/porter/lifecycle.go, pkg/porter/uninstall.go, pkg/porter/uninstall_test.go, pkg/porter/upgrade.go, tests/dependencies_test.go, tests/testdata/drivers/exit-driver-fail.sh, tests/testdata/drivers/exit-driver.sh, tests/uninstall_test.go
* Adds logic to enable deleting an installation, either via `porter uninstall` or `porter installation delete` (as designed in https://github.com/deislabs/porter/issues/1163)
Closes https://github.com/deislabs/porter/issues/1163
- Do we want any additional docs besides the auto-gen'd CLI docs?
- Suggestions for simplifying logic around uninstall +/- delete +/- force-delete welcome.
- Note how we are swallowing errors around the execution of the uninstall action if force-delete is true -- do we like this approach?  Or should we continue to return any/all execution errors after we force delete the installation? …
=> feat(*): add installation delete options/flags to relevant commands

pkg/context/context.go, pkg/context/context_test.go, pkg/exec/builder/execute.go, pkg/kubernetes/kubernetes.go, pkg/porter/cnab.go, pkg/porter/cnab_test.go, pkg/porter/install_test.go, pkg/porter/lifecycle_test.go, pkg/porter/options.go
* Ensure that --debug sets PORTER_DEBUG bundle parameter at runtime when a bundle is executed.
* Print the command when --debug is set for the exec and kubernetes mixin, i.e. use --debug just like some of the other mixins do already.
* Improve how we detect and set context.Debug at runtime and add tests. What we had was only accidentally working.
* Removed extra logic we had for if the user had already set a parameter named "porter-debug". At this point, that is a reserved parameter for Porter and we shouldn't be jumping through hoops to let Authors make parameters named after our internal parameters. That should fail `porter build` if they create a parameter that shadows our internal parameters. I'll make an issue for that.
None, I just noticed this when troubleshooting today.
NA
=> Porter debug

pkg/cnab/config-adapter/adapter.go, pkg/manifest/manifest.go, pkg/manifest/manifest_test.go, pkg/runtime/runtime-manifest.go
* Adds logic to update a parameter's `applyTo` section under certain conditions, as described in https://github.com/deislabs/porter/issues/1159
Closes https://github.com/deislabs/porter/issues/1159
I'm not entirely happy with the approach of needing to explicitly call `UpdateApplyTo` both when converting a manifest to a bundle and when converting a manifest to its runtime variant when running an action.  (Basically, on build and during runtime).  But it does appear that the manifest is loaded anew in each place, hence the two places to update.
=> fix(manifest): update applyTo on a param, if needed

pkg/runtime/runtime-manifest.go, pkg/runtime/runtime-manifest_test.go
* Updates logic around masking output values.  We still regard step outputs as sensitive by default, but this updates step outputs that are also bundle-level outputs to inherit the bundle-level output setting.  (Note that bundle-level outputs are _not_ sensitive by default.)
N/A
=> fix(runtime-manifest): defer to bundle-level output def sensitivity

docs/content/storage-migrate.md
Add migration instructions for the azure plugin, e.g. copying the porter container to a new storage account that has blob index preview enabled.
NA
Merge like Vaughn is out sick and I already cut the release!
=> Add migration instructions for azure plugin

pkg/exec/builder/flags.go, pkg/exec/builder/flags_test.go
Fixes non strings yaml keys of flags causing panic
Closes #1215
=> 🐛 Fix non-string yaml keys of flags causing panic

pkg/plugins/pluggable/loader.go, scripts/test/test-linux-install.sh, scripts/test/test-mac-install.sh, scripts/test/test-windows-install.ps1
When running a plugin, I was setting PORTER_HOME improperly. Windows was having none of it and was refusing to run the plugin with an improperly formatted env var, returning
```
The parameter is incorrect
```
Closes #1154
As a follow-up I'm looking at https://docs.microsoft.com/en-us/azure/devops/pipelines/get-started-multiplatform?view=azure-devops to change our build to run on more than one OS. At first we can just run the CLI tests until we can build on all operating systems (not sure if building on windows is at 100% yet).
In the meantime, I've added a `porter list` call to our install script e2e test which does run on all OSs. This seems like a good thing to do anyway, make sure that Porter is not only installed but can run our most basic command without error.
=> Fix setting PORTER_HOME on plugins

Makefile, examples/kubernetes/porter.yaml, pkg/kubernetes/kubernetes.go, tests/outputs_test.go
* Removes wrapping single quotes from the `-o jsonpath` flag when retrieving outputs from Kubernetes
All credit for the fix goes to @carolynvs 🙇 (see https://github.com/deislabs/porter/pull/1211#issuecomment-679299614)
Closes #1210 
* I opted for an integration test since we have the pre-existing kubernetes example bundle... which brings the added benefit of testing the example... but I can understand if we don't wish to introduce this overhead.
* Some auto-formatting changes came in to `kubernetes.go`, I guess from my VS Code IDE/golang extension(s)... if we feel strongly, I can see about keeping those out. …
=> fix(kubernetes.go): remove jsonpath quotes

pkg/porter/dependencies.go
* Adds a check to be sure the manifest dep matches the current dep being processed before validating param def and setting param value
Previously, we'd erroneously validate param definitions on the processed dep _against every dep listed in the manifest_ via the for loop, so we'd naturally hit errors.
=> fix(dependencies.go): verify dep match before checking params

CONTRIBUTING.md, pkg/context/context.go, pkg/context/helpers.go, pkg/context/plugindebugcontext.go, pkg/plugins/pluggable/loader.go, pkg/plugins/pluggable/loader_nix.go, pkg/plugins/pluggable/loader_windows.go
Adds the ability to have porter start delve and attach it to a plugin.
The following variables are required/used:
`PORTER_RUN_PLUGIN_IN_DEBUGGER` should be set to the name of the plugin to be debugged (e.g. secrets.azure.keyvault to debug the azure secrets plugin)
`PORTER_DEBUGGER_PORT` should be set to the port number where the delve API will listen, if not set it defaults to 2345
`PORTER_PLUGIN_WORKING_DIRECTORY` should be the path to the source code for the plugin being executed. (e.g. for the Azure plugin this value would be <PATH>/porter-azure-plugins/cmd/azure
The plugin to be debugged should be compiled and placed in porters plugin path (e.g. in the Azure plugin case the plugin should be copied to $PORTER_HOME/plugins/azure/.
A process will then be started using [delve …
=> Adds support for debugging plugins

CONTRIBUTING.md
* Adds section around forthcoming DCO check
(DCO bot is added; will hold off on making it a mandatory check until this PR is approved and merged.)
Ref https://github.com/deislabs/porter/issues/1250
Do we want the full section inline'd how it is currently?  Or perhaps link from CONTRIBUTING to a new (DCO?) markdown doc?
=> docs(CONTRIBUTING.md): add DCO section

Makefile.kind
* bumps Kind to [v0.9.0](https://github.com/kubernetes-sigs/kind/releases/tag/v0.9.0), allowing us to remove the Mac OSX/Darwin workaround
N/A
N/A
=> ref(Makefile.kind): bump kind and remove darwin workaround

pkg/exec/schema/exec.json, pkg/porter/testdata/schema.json
* adds missing `suppress-output` field entry to the `exec` mixin schema
N/A, noted when running an audit of applicable schemas after https://github.com/deislabs/porter-az/issues/17 was issued.
=> fix(schema/exec.json): add missing suppress-output entry

docs/content/mixins/docker-compose.md, docs/content/mixins/docker.md
* adds missing `:` in similar sections of docker-compose and docker mixin pages
n/a, noticed when reviewing an associated PR
n/a
=> docs(*): add missing colon where needed

pkg/porter/publish.go
* removes the `InsecureRegistry` field from the publish opts, now that the same field is added by `BundlePullOptions`
n/a
n/a
=> fix(publish.go): remove shadow InsecureRegistry field

docs/content/wiring.md, pkg/runtime/runtime-manifest.go, pkg/runtime/runtime-manifest_test.go
* Template installation name
* Template custom metadata
Closes #1035
We need to redo the wiring page. It really is a page about how to do porter templating but I don't think we have a page that documents that? I think the page should be renamed and tweaked, removing how to define parameters, etc moving that into authoring bundles leaving just how to do templating.
=> Template installation name and custom metadata

CONTRIBUTING.md, Makefile, scripts/setup-dco/prepare-commit-msg, scripts/setup-dco/setup.sh
* Add signoff hook, prepare-commit-msg to the repo that will append the signoff automatically when it's not present
* Add a make target, make setup-dco, that configures the hook
* Explain the new target in the contributing guide
Follow-up to adding the DCO requirement
It would help if you would try it out locally
=> Add automatic signoff hook

CONTRIBUTING.md, Makefile
* Fix bad link in contributing guide when we mention hugo again. Also moved the first step into the general description since it's not a step per-se.
* Added a wait so that the docs do not open until the website is ready to preview.
N/A
You may want to try it out locally yourself.
```
git fetch upstream pull/<number>/HEAD:pr<number>
git checkout pr<number>
make docs-preview
```
=> Improve documentation preview experience

docs/content/mixins/exec.md, pkg/exec/builder/output_jsonpath.go, pkg/exec/builder/output_jsonpath_test.go
In debug mode, print the full captured document and the query we are using to match output so that the user can troubleshoot when the output's format or contents do not contain the expected output value.
Makes @squillace happy. I will update the az mixin to use this after it is merged.
N/A
=> Print the captured output for jsonPath outputs

GOVERNANCE.md
This explains how the project governs itself today without attempting to introduce any language that we didn't already have existing. Over time we can iterate and improve upon it in follow-on pull requests. I want to get this in without modifying our existing goverance for our inclusion into the CNCF.
Closes #1256 
N/A
=> Add GOVERNANCE file

docs/content/blog/cncf.md, docs/content/mixins/docker-compose.md, docs/content/mixins/docker.md
Top secret blog post announcing that we are in the CNCF
https://deploy-preview-1303--porter.netlify.app/blog/cncf/
Tell people who obviously don't follow our GitHub pull requests 😉 
Here was some of the guidance I was given for the announcement:
example of previous announcement: https://openservicemesh.io/blog/open-service-mesh-osm-accepted-into-cncf-as-a-sandbox-project/
General Structure of Announcements:
* the announcement
* a little bit of history
* where you hope to go from here
* maybe some acknowledgements
* call to actions if any
=> CNCF Announcement

pkg/cnab/config-adapter/adapter_test.go, pkg/cnab/config-adapter/testdata/porter-with-custom-metadata.yaml, pkg/manifest/manifest.go, pkg/manifest/manifest_test.go, pkg/manifest/testdata/porter-with-custom-metadata.yaml, pkg/unmarshallyaml/custom_definitions.go
Updates marshalling of customdata YAML in order that the data can be serialised to JSON. See https://github.com/go-yaml/yaml/issues/139
Closes #1292
=> fix custom metadata serialisation

docs/content/community.md
Use a html link instead of a markdown link so it renders properly. When I switched that part of the page to HTML it broke the link because you can't embed markdown inside of HTML (usually).
On the live site
Preview of change @ https://deploy-preview-1317--porter.netlify.app/community/
N/A
N/A
=> Fix link to open an issue on community page

CONTRIBUTING.md
=> 🐛 Fix md syntax in CONTRIBUTING.md

docs/content/docs.md
Cleans up the Porter Docs landing page. 
Documentation update.
=> Update the landing page for Porter Docs removing the porter CLI commands

CONTRIBUTING.md
Signed-off-by: nhcarrigan <nhcarrigan@gmail.com>
- Moves the links for the `good first issue` and `help wanted` labels from the first paragraph to the bullet list below. 
- Adds a statement to the first paragraph that clarifies the global scope of the project board.
Closes #1031 
_Put any questions or …
=> docs: move links, add project clarification

pkg/cnab/cnab-to-oci/registry.go
Don't bubble-up error messages directly from cnab-to-oci, they don't provide enough context to know what just failed, e.g.
```
Error: unexpected status: 400 Bad Request
```
Troubleshooting for #1332
=> Indicate where publish failed in error message

cmd/porter/bundle.go, pkg/porter/action.go, pkg/porter/archive.go, pkg/porter/cnab.go, pkg/porter/cnab_test.go, pkg/porter/credentials.go, pkg/porter/dependencies.go, pkg/porter/dependencies_test.go, pkg/porter/explain.go, pkg/porter/inspect.go, pkg/porter/install.go, pkg/porter/install_test.go, pkg/porter/invoke.go, pkg/porter/invoke_test.go, pkg/porter/lifecycle.go, pkg/porter/lifecycle_test.go, pkg/porter/parameters.go, pkg/porter/uninstall.go, pkg/porter/upgrade.go, tests/dependencies_test.go, tests/install_test.go, tests/invoke_test.go, tests/outputs_test.go, tests/rebuild_test.go, tests/suppress_output_test.go, tests/uninstall_test.go
Parse parameters after bundle is loaded
* ExecuteAction performs any action but uninstall since that operation is performed backwards.
* Move resolution of parameters later, when we convert the options into cnab arguments, so that we have the bundle definition available
* Only validate that --param values are in the proper format, PARAM=VALUE
Fixes #1320
I'd appreciate feedback on if this is an improvement or not. I was trying to have us parse parameters once, and move towards reuse with our new BundleAction interface.
=> Refactor when parameters flags are parsed

pkg/manifest/manifest.go, pkg/manifest/manifest_test.go
* Updates text around manifest deprecation warnings, both to encourage use of the new `registry` field and to link to the appropriate section of the docs.
A follow-up to https://github.com/getporter/porter/pull/1343
N/A
N/A
=> ref(manifest.go): update manifest field deprecation warnings

scripts/install/install-mac.sh
When we moved the location of porter-runtime to runtimes/porter-runtime, the macOS script was typo-d. This fixes the script so that it works again.
Follow-up to #1329 
NA
=> Fix mac install script

pkg/manifest/manifest.go
We were accidentally using filepath when joining components of a docker reference, which creates an invalid value registry\bun (wrong slash).
The exiting unit tests would have caught this but we don't (yet) run CI on windows. I just hit this bug when adding CI on Windows so this will have coverage soon.
Fixes #1354 
I have manually tested on Windows.
=> Fix defaulting of reference on windows

docs/content/author-bundles.md, pkg/cnab/config-adapter/adapter.go, pkg/cnab/config-adapter/adapter_test.go, pkg/manifest/manifest.go, pkg/manifest/manifest_test.go, pkg/porter/testdata/schema.json, pkg/runtime/runtime-manifest.go, pkg/runtime/runtime-manifest_test.go, pkg/runtime/testdata/porter-images.yaml, pkg/templates/templates/schema.json
This undoes an accidental change from https://github.com/getporter/porter/pull/1308 that changed the manifest
field images.NAME.digest to images.NAME.contentDigest. This is a breaking regression for anyone previously using images. There wasn't any need to change the field name in the manifest, we only needed the bundle.json to use the term contentDigest.
I have changed the manifest field back to digest, and ensured that the user documentation for that field is up to date.
Closes #1355 
I've made a follow-up issue to look at tag again. https://github.com/getporter/porter/issues/1357
=> Revert images.contentDigest back to digest

CONTRIBUTING.md
It deletes the line on the `initial setup` from the CONTRIBUTING.md file where it said that porter needs to reside at GOPATH.
This does not needed anymore since go module is introduced and enabled.
I tried this on my local machine to run `make build install` from a directory outside of the GOPATH and it produces the porter binary. Screenshot is attached below.
Closes #1286
=> Delete instruction to use GOPATH from the CONTRIBUTING's setup tutorial

build/azure-pipelines.release.yml
Fix release build, it was missing bin/porter so it failed to index and publish the atom.xml file
Follow up to #1321 
🤞
=> Make porter binary available during publish

go.mod, go.sum
Bumps cnab-go to v0.14.1 which includes image digest verification.
Meet cnab spec requirements to verify image digests.
N/A
=> Bump cnab-go to v0.14.1

pkg/build/dockerfile-generator_test.go, pkg/templates/templates/build/Dockerfile, pkg/templates/templates/create/Dockerfile.tmpl
Edited template dockerfiles to use debian:stretch-slim instead of debian:stretch
The template dockerfiles are located in pkg/templates.
Closes #1049 
This is my first contribution
=> Edited template dockerfiles to use debian:stretch-slim instead of debian:stretch

CONTRIBUTORS.md, docs/content/blog/docker-mixin-blog-post.md, docs/content/blog/using-docker-in-bundles.md, docs/content/custom-dockerfile.md, docs/content/slides/pack-your-bags-msp/index.md, docs/content/slides/pack-your-bags/index.md, examples/aks-spring-music/Dockerfile.tmpl, examples/azure-terraform/README.md, examples/docker/Dockerfile.tmpl, examples/exec-outputs/Dockerfile.tmpl, examples/gke-example/Dockerfile.tmpl, examples/hello/Dockerfile.tmpl, examples/porter-discourse/Dockerfile.tmpl, tests/testdata/bundles/outputs-example/Dockerfile
Updated references to debian:stretch with debian:stretch-slim
Closes #1380 
=> Updated references to debian:stretch with debian:stretch-slim

Makefile, examples/service-fabric-cli/Dockerfile.tmpl
* Fix for a build failure for this example bundle as seen in (unrelated PR) https://github.com/getporter/porter/pull/1387
* Once the above was fixed, we hit an issue wherein we hadn't pinned the json validator cli (`ajv-cli`) to a version and were hence pulling latest.  There are breaking changes in the latest (perhaps we can look into this at a later date); for now, we pin to a known quantity (3.3.0)
N/A
N/A
=> fix(examples/service-fabric-cli): fix Dockerfile build

magefile.go
We were assuming a linux agent with /home/vsts/go/bin. We should have been using the discovered location using GOAPTH/bin instead.
We are getting `'mage' is not recognized as an internal or external command,` on our windows build when running `mage TestE2E` because GOPATH/bin is not in PATH.
I think this was passing before because the windows agent was "dirty" and had local changes I had made when debugging. When I reimaged and we had a fresh agent, this popped up.
=> Set GOPATH/bin on PATH properly

Makefile, magefile.go
* You only see messages from log.Println when you call mage with -v. I have gone through our magefile and switched any output lines that should always be printed, like the messages about waiting for the docker service to start on the windows agent, to use fmt.Println.
* Start docker first, then start the local docker registry
* Handle the local docker registry container being stopped when attempting to start the docker registry for tests
* Execute the DockerDesktop.exe command differently so that we don't try to wait for that process to exit. (Fixes hang)
Related to #1389
~I am not sure why the build got stuck for an hour on this. I just tested my polling logic and it should only be waiting a minute. I'm going to just get this logging fixed and then we'll have more info if it happens …
=> Improve starting docker and local registry before running tests

Makefile, build/azure-pipelines.pr-automatic.yml, build/images/workshop/Dockerfile, scripts/build-images.sh, scripts/publish-images.sh
* Helm versions lower than v2.17.0 point to the deprecated helm repositories.
* Validate docker images during PR builds (the build broke on release but we can catch this sooner)
Fixes broken release build.
=> Bump helm to supported version in our workshop image

Makefile, magefile.go
The build right now doesn't stop when we can't install a mixin into the build. This allows the build to get all the way to the end before something fails because it needs that mixin. Fail fast.
* Move the get-mixins target to mage
* Fail the target if any mixins fail to install
* Only install the mixin if it's not present in the bin
Makes broken build fail faster
We really need to fix how we use our CDN so that we don't overwrite existing files. I'm not sure why it's so flaky but that is probably part of it.
=> Stop build if we can't install a mixin

go.mod, go.sum, pkg/cnab/provider/action.go, tests/install_test.go, tests/invoke_test.go, tests/suppress_output_test.go
This contains the fix so that docker writes to op.Out instead of stdout directly. This will let us better capture and only display bundle output (instead of all the logging too) like we want to for #1353. It also fixes our test output when in verbose mode or when tests fail, so the lines print in order.
NA
=> Bump cnab-go to v0.15.0

docs/content/compatible-registries.md
I have just tested GitHub Container Registry ghcr.io with Porter and it worked fine.
https://deploy-preview-1406--porter.netlify.app/compatible-registries/
N/A
N/A
=> Document GHCR is CNAB compatible

docs/content/contribute/tutorial.md
- Adds missing link anchor for the Mage page 🔮 (See the `We are transitioning from Make to [Mage]` section.)
N/A
N/A
=> docs(tutorial.md): add mage link

pkg/porter/credentials.go, pkg/porter/explain.go, pkg/porter/lifecycle.go, pkg/porter/parameters.go, pkg/porter/pull.go, pkg/porter/pull_test.go
- Adds fallback for setting reference to the deprecated tag value in commands missed previously
Closes https://github.com/getporter/porter/issues/1418
=> fix(*): no really, set reference off of deprecated tag value pls

pkg/cnab/config-adapter/adapter.go, pkg/cnab/config-adapter/adapter_test.go, pkg/cnab/config-adapter/testdata/porter-with-deps.yaml, pkg/manifest/manifest.go, pkg/runtime/runtime-manifest_test.go
Alas, another area where we need to support the deprecated tag field for the time being:
- Adds the `tag` yaml tag back in (along with corresponding logic) so that older manifests still function if they use this field, until 1.0
=> fix(*): continue to support dependency tag use for time being

pkg/cnab/bundle.go, pkg/cnab/config-adapter/adapter.go, pkg/cnab/config-adapter/adapter_test.go, pkg/cnab/extensions/bundle.go, pkg/cnab/extensions/bundle_test.go, pkg/cnab/extensions/dependencies.go, pkg/cnab/extensions/dependencies_test.go, pkg/cnab/extensions/docker.go, pkg/cnab/extensions/extensions.go, pkg/cnab/extensions/extensions_test.go, pkg/cnab/extensions/file_parameter.go, pkg/cnab/extensions/file_parameter_test.go, pkg/cnab/extensions/parameter_sources.go, pkg/cnab/extensions/paramter_sources_test.go, pkg/cnab/extensions/required.go, pkg/cnab/extensions/required_test.go, pkg/cnab/extensions/solver_test.go, pkg/cnab/extensions/testdata/bundle.json, pkg/cnab/provider/parameters.go, pkg/cnab/provider/parameters_test.go, pkg/porter/explain.go, pkg/porter/explain_test.go, pkg/porter/outputs.go, pkg/porter/show.go, pkg/runtime/runtime-manifest_test.go
Previously we had checks throughout the codebase checking if a parameter is Porter's special "file" type. Which lead to #1417 where `porter explain` shows the underlying string type for a file parameter instead of "file".
I have made the file type a custom extension under the porter namespace, and centralized the logic for the parameter type. I will submit this to the CNAB spec as a well-known extension since I think it is useful beyond Porter.
I also made our extension constants consistent.
Fixes #1417 
Sorry this isn't split up into two commits! 😝 
=> Use a custom extension for File type

docs/themes/porter/layouts/index.html
As reported by @joshuabezaleel, the picture for helm charts on the homepage is a broken link.
https://deploy-preview-1424--porter.netlify.app/
https://cloud-native.slack.com/archives/CN8NA4F8V/p1610810762002200
NA
=> Fix helm chart image on homepage

CONTRIBUTING.md, docs/content/contribute/tutorial.md, docs/content/quickstart.md, magefile.go
* Explain the tests and how to use mage to run them.
* Add details for other shells
* Clarified how to use the local porter build
* Link to contributing guide
https://deploy-preview-1423--porter.netlify.app/contribute/tutorial
https://deploy-preview-1423--porter.netlify.app/quickstart/
Fixes #1400
None
=> Update contributing tutorial

examples/service-fabric-cli/Dockerfile.tmpl
Bump the base image and update the commands to match the updated instructions.
Broken builds
We should review our examples and consider moving them into a separate repo and build, triggered when new releases of porter are created. Some of the examples when they fail have nothing to do with if porter is working or not, and it's are slow build build them all.
=> Fix the service fabric example bundle

magefile.go
Change StarlDockerRegistry target to StartDockerRegistry in our magefile.
https://github.com/getporter/porter/pull/1423#discussion_r564221676
Sorry I can't type!
=> Fix typo in StartDockerRegistry target

examples/exec-outputs/cluster.sh, examples/exec-outputs/porter.yaml
When a bundle is executed on kubernetes, files are injected into the bundle using volume mounts. The mount point cannot be used in a move or remove operation. So while this bundle worked okay on Docker (because the docker driver injects files into the bundle using cp), the bundle fails with "device or resource busy" on the kubernetes driver.
Long term this is something that Porter can help workaround, but for now this fixes the bundle so that it doesn't try to move a file that was injected as a parameter or credential.
Gets this example to work with the Porter Operator.
N/A
=> Update exec-outputs example for the k8s driver

cmd/porter/main.go, docs/content/cli/archive.md, docs/content/cli/bundles_archive.md, docs/content/cli/bundles_explain.md, docs/content/cli/bundles_inspect.md, docs/content/cli/bundles_install.md, docs/content/cli/bundles_invoke.md, docs/content/cli/bundles_uninstall.md, docs/content/cli/bundles_upgrade.md, docs/content/cli/credentials_generate.md, docs/content/cli/explain.md, docs/content/cli/inspect.md, docs/content/cli/install.md, docs/content/cli/invoke.md, docs/content/cli/parameters_generate.md, docs/content/cli/publish.md, docs/content/cli/uninstall.md, docs/content/cli/upgrade.md
Use -r as a short flag for --reference because typing is hard, e.g. `porter install -r getporter/porter-hello:v0.1.1`
Closes #1436
=> Add a short flag for --reference

pkg/porter/publish.go, tests/publish_test.go
* Re-orders logic in publish to load the internal manifest prior to getting the original invocation image name (which may be updated and compared later on).
Closes https://github.com/getporter/porter/issues/1449
=> fix(publish.go): get original image value after loading internal manifest

docs/static/_redirects
Allows us to test from the cdn2.porter.sh URL as well.
=> Enable testing cdn from alt domain

Makefile
Originally we had only a single feed, just for mixins, and it was located at /atom.xml. When we introduced plugins, we changed the location of the feed to /mixins/atom.xml but for backwards compatibility reasons we continued to publish the file to /atom.xml and used a redirect for /mixins/atom.xml.
That was over a year ago and at this point, no one should be using clients that old. So this feels safe to move.
By publishing the file where it Porter looks for it when installing mixins, we don't need a rule on our CDN to do that rewrite which makes things less complicated for us.
None, but it helps with our current CDN issues.
N/A
=> Publish mixins feed to /mixins/atom.xml

cmd/porter/explain.go, docs/content/cli/bundles_explain.md, docs/content/cli/explain.md, pkg/porter/explain.go, pkg/porter/explain_test.go
Signed-off-by: joshuabezaleel <joshua.bezaleel@gmail.com>
Enable `--action <action>` flag on `explain` command and only print corresponding credentials and parameters according to the action.
Closes #1416 
Screenshot is shown below:
=> Add action option to explain command

mage/releases/publish.go
I had been testing changing where we publish our binaries and the test
container name snuck into one of my previous commits. This sets it back
to the production container, "porter".
=> Fix azure container name

docs/content/compatible-registries.md
In #1332 @iennae discovered that Google Cloud Registry does not support CNAB, however their new offering Google Artifact Registry does.
Closes #1332 
I will submit a PR to the cnab website as well with the same changes.
=> Mark GCR as unsupported, and Artifact Registry as supported

docs/content/learning.md
Last year I did a demo of using Porter with airgapped networks for SIG Application Delivery.
N/A
I owe the world 1 blog post on airgap.
=> Add airgap demo at SIG App delivery

Makefile, mage/releases/publish.go, magefile.go, mixin.mk, pkg/pkgmgmt/client/install.go, pkg/pkgmgmt/feed/generate.go, pkg/pkgmgmt/feed/generate_test.go
The file structure in the bin is used when generating the mixin feed. So
if there is a folder named "latest" then a version "latest" is put in
the atom.xml. A previous commit caused an untagged release to be in the
bin, instead of being renamed to canary and uploaded to our feed which
broke installing porter.
I have moved the directory prep into mage, calling it in make xbuild-all
so that it is guaranteed to happen. I have also added a check in the
atom feed generation to ignore those releases if found.
Now after you cross build, your bin looks like this
```
bin/
mixins/
exec/
canary/... OR
v1.2.3/...
```
The recent change in #1460 caused a regression in generating the mixin feed. I have already manually fixed the atom.xml (because it is appended to during publish, so we needed to get the …
=> Do not publish untagged or latest to mixin feed

mage/releases/publish.go
I had this line originally in my PR and then it got lost. We do not want to rename bin/v1.2.3 to bin/latest.
The release build
One day when I'm not underwater, let's come up with a way to test build/publish changes in PRs.
=> Do not rename v1.2.3 to latest in bin during publish

magefile.go
We just ran into a publish problem on the last build where the install
script (which hardcodes the latest version) was uploaded before the
binaries for that version. The upload for the binaries failed so the
install script was pointing at missing binaries.
I've changed the order so that we upload to /porter/VERSION/* first.
Then if that's successful, upload /porter/latest/install-*.
Closes #1467
=> Publish version binaries before install script

mixin.mk, scripts/install/install-linux.sh, scripts/install/install-mac.sh
We have been having intermittent problems with errors such as:
* 503 Service Unavailable
* HTTP_1_1_REQUIRED
Based on discussions in Azure forums (below), people are suggesting that this is caused by Azure CDN's use of HTTP/2 which can be unstable with some clients. Verizon's CDN has it enabled as well. I want to try turning it off to see if that reduces or eliminates the errors.
I am disabling HTTP/2 on the client and in our install scripts
* https://docs.microsoft.com/en-us/answers/questions/239978/intermittent-err-http2-protocol-error-http2-stream.html
* https://feedback.azure.com/forums/169385-web-apps/suggestions/9552936-enable-http-2-on-azure-web-apps (see comment from discodave and others)
* https://github.com/terraform-providers/terraform-provider-azurerm/issues/503
Maybe nothing, …
=> Do not use HTTP/2

mage/releases/publish.go, magefile.go
Create directories for latest/canary and version. It results in more files during publish but avoids us looking for binaries in the wrong spot. The mixin feed publish is smart now and will ignore extra directories.
=> Simplify publish

pkg/pkgmgmt/feed/generate.go, pkg/pkgmgmt/feed/generate_test.go
When we check for if a version should be included in the atom feed,
previously I assumed that the length of the sha is fixed. But it could
be multiple lengths. Just check that it looks like
vN.N.N-N-g(sha)+
I managed to accidentally add an untagged version into the  mixin feed because the sha length didn't match.
N/A
=> Relax check for untagged versions during feed generation

build/images/client/Dockerfile, build/images/workshop/Dockerfile, pkg/pkgmgmt/client/install.go, pkg/pkgmgmt/client/install_test.go, scripts/install/install-linux.sh, scripts/install/install-mac.sh
When we interact with cdn.porter.sh pass in extra flags so that if the command fails we can get a debug reference. When we download a file using porter, set the azure debug header and our own unique per request user agent string so that we can correlate errors on the client and server logs.
Also always set HTTP/1 when building the porter docker images, since it just failed with one of the errors we are tracking down:
Step 4/5 : RUN sh -c 'curl https://cdn.porter.sh/${PERMALINK}/install-linux.sh | sh' &&     ln -s /root/.porter/porter /usr/local/bin/porter
---> Running in b81a52ac1ca9
% Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
Dload  Upload   Total   Spent    Left  Speed
0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
0     0 …
=> Add debugging to porter downloads

build/images/client/Dockerfile, build/images/workshop/Dockerfile, scripts/install/install-linux.sh, scripts/install/install-mac.sh
I'm having trouble correlating failures when building the porter docker client or during check install so I'm adding a unique PORTER_TRACE agent value there as well.
=> Set a PORTER_TRACE agent value in install scripts

docs/content/author-bundles.md, pkg/porter/testdata/schema.json, pkg/templates/templates/schema.json
* Update porter schema so that intellisense works correctly in VS Code.
* Document the expected format, a map of strings, and how to read the values when the bundle is executing.
This was reported by Prasad @ Microsoft that there wasn't documentation or intellisense support.
NA
=> Document custom section in porter.yaml

.dockerignore, Makefile, build/azure-pipelines.pr-automatic.yml, build/azure-pipelines.release.yml, build/images/client/Dockerfile, build/images/workshop/Dockerfile, scripts/build-images.sh, scripts/publish-images.sh
* Split publish into two steps. The build is failing on building the docker images because of our CDN problems. This makes it easier to rerun just the docker image part, without retriggering the Azure bug.
* Build the docker images using local binaries. Copy the local binaries from the bin instead of running porter's install script. It will reduce build errors and is more accurate in case of the CDN lagging.
N/A
I am testing this on a special test release pipeline for porter so that I will know that it works before merging. I'll link to the passed build when ... it passes. https://dev.azure.com/getporter/porter/_build/results?buildId=973&view=results
I think using two pipelines based on the same yaml, that we can possibly have a single script instead of maintaining two versions, one for …
=> Bandaid on publish

ADOPTERS.md, README.md, docs/content/community.md
* Add adopters file. Encourage people to let us know if they use porter.
* Add links to the dev meeting
https://github.com/carolynvs/porter/tree/administrivia#do-you-use-porter
https://github.com/carolynvs/porter/blob/administrivia/ADOPTERS.md
https://deploy-preview-1493--porter.netlify.app/community/#dev-meeting
Just keeping our repo info up-to-date.
=> Add adopters and meeting to readme

build/azure-pipelines.release-template.yml, build/azure-pipelines.release.yml, build/azure-pipelines.test-release.yml
Standardize the registry names to be fully qualified to match what's defined in Azure DevOps.
=> Use explicit docker registry target names

build/azure-pipelines.release-template.yml
When I set a condition for publish, it lost the default logic for requiring that the previous stage suceeded...
=> Do not try to publish when build fails

go.mod, go.sum, pkg/plugins/pluggable/loader.go
When the plugins execute, there is a library (yamux) that is logging
directly to stderr things that don't appear to be errors. For example
when we disconnect the plugin, it sometimes logs "broken pipe".
```
2021/03/16 23:14:01 [ERR] yamux: Failed to write header: write unix @->/tmp/plugin968987118: write: broken pipe
2021/03/16 23:15:41 [ERR] yamux: Failed to write header: write unix @->/tmp/plugin806433500: use of closed network connection
```
These don't immediately appear to be real errors because the bundle
executes successfully and the data we expected to be persisted by the
plugin, is present. It's super hard to reproduce so I am not not 100%
confident that there may not be an underlying bug.
I have patched hashicorp/go-plugin to redirect yamux logs to the plugin
client's logger. …
=> Capture yamux errors from plugin execution

Makefile, build/azure-pipelines.release-template.yml, build/azure-pipelines.release.yml, build/azure-pipelines.test-release.yml, build/images/agent/Dockerfile, build/images/agent/run.sh, build/images/client/Dockerfile, build/images/workshop/Dockerfile, docs/content/docker-images/agent.md, docs/content/docker-images/client.md, docs/content/docker-images/workshop.md, mixin.mk, scripts/build-images.sh, scripts/publish-images.sh
* The porter-agent image is customized for running Porter in kubernetes as
part of the Porter Operator.
* Dual publish to ghcr.io/getporter and Docker Hub. Eventually we will migrate to just GHCR (since they won't expire our images).
https://deploy-preview-1494--porter.netlify.app/docker-images/agent/
No more building the operator agent locally on Carolyn's machine!
N/A
=> Build the porter-agent image for the operator

examples/gke-example/Dockerfile.tmpl
* Attempts to fix the build for the gke-example example bundle (recent failure seen [here](https://dev.azure.com/getporter/porter/_build/results?buildId=1074&view=logs&j=8303b19d-615e-53fa-4d31-74a5e3d2f9b8&t=72eea06a-ec19-5d67-fbd1-90227bdee65c)).  Removes the dependency on the quay image as well as the need for copying in certs -- I don't think this is necessary any longer (?)
=> fix(examples/gke-example): fix build

docs/content/author-bundles.md, go.mod, go.sum, pkg/cnab/config-adapter/stamp_test.go, pkg/cnab/extensions/solver.go, pkg/manifest/manifest.go, pkg/manifest/manifest_test.go, pkg/manifest/testdata/simple.porter.yaml, pkg/pkgmgmt/feed/feed.go, pkg/pkgmgmt/feed/generate.go, pkg/porter/build.go, pkg/porter/build_test.go
* Quietly strip off the leading v prefix when the user specifies a bundle version in the manifest or with --version during build.
* Convert + to _ when using the bundle version as an OCI tag.
Closes #1431 and #1432
We welcome all semver great and small
=> Improve semver defaulting when building a bundle

docs/content/credentials.md, docs/content/parameters.md, pkg/schema/credential-set.schema.json, pkg/schema/parameter-set.schema.json
This was asked for in Slack. We are working on normalizing a schema for parameter and credential sets in the CNAB spec but for now this documents what we use today.
N/A
* We could follow-up with an issue that validates parameter/credential sets that are passed in as a file with this schema.
* The links from the doc won't resolve until this PR is merged.
=> Store the schema for param/cred sets

docs/static/_redirects
Serve the install scripts through Netlify's CDN to avoid having a redirect in a user-facing curl command. The rest of our downloads are all redirected to workaround Netlify's 2MB limit for serving files.
=> Add Netlify redirects to GH release downloads

docs/static/_redirects
Use the packages repo to host the atom feeds for mixins and plugins. Originally I made a separate repo but it will be easier to have a single repo for this.
=> Host official atom feeds in packages repo

build/doc-only-build.sh, docs/content/install.md, workshop/docker-image/Dockerfile.workshop
Now that we are hosting on GitHub releases, our installation instructions need to use `curl -L` so that the redirect issued by GitHub is followed. Even using Netlify to rewrite URLs I wasn't able to make the installation URLs work without any redirects.
=> Update install commands to follow redirects

Makefile, build/azure-pipelines.release-template.yml, build/azure-pipelines.release.yml, build/azure-pipelines.test-release.yml, build/git_askpass.sh, go.mod, go.sum, mage/releases/publish.go, magefile.go, mixin.mk, scripts/prep-install-scripts.sh
Migrate away from Azure blob storage to attaching assets to a release. Non-release assets, such as mixin feeds, are now committed in the github.com/getporter/packages repository. Netlify handles redirecting
our cdn.porter.sh URLs to the underlying files wherever they may be.
=> Publish release assets to GitHub release

pkg/manifest/manifest.go, pkg/manifest/testdata/porter.yaml, pkg/runtime/runtime.go
This PR adds support for mixins without a description.
Closes #1480
If changed `testdata/porter.yaml` and removed a description for `install>exec`
=> Support mixins without descriptions

pkg/porter/explain.go, pkg/porter/explain_test.go
* When no action is set, show all parameters/credentials
* Filter credentials by applyTo and show AppliesTo in plaintext output
Closes #1539 
The issue only reported a problem for parameters but I realized that when I implemented applyTo for creds that I forgot to update porter explain, so I fixed them both.
=> Fix ApplyTo in porter explain

cmd/porter/mixins.go, cmd/porter/plugins.go, docs/content/install.md, examples/azure-terraform/porter.yaml, pkg/mixin/install.go, pkg/mixin/install_test.go, pkg/pkgmgmt/client/install.go, pkg/pkgmgmt/client/install_test.go, pkg/pkgmgmt/download_options.go, pkg/pkgmgmt/download_options_test.go, pkg/pkgmgmt/install.go, pkg/pkgmgmt/install_test.go, pkg/pkgmgmt/pkgmgmt.go, pkg/plugins/install.go, pkg/plugins/install_test.go, pkg/porter/packages.go, pkg/porter/packages_test.go, scripts/install/install-linux.sh, scripts/install/install-mac.sh, scripts/install/install-windows.ps1, workshop/porter-tf-aci/azure/bundle/porter.yaml, workshop/porter-tf/azure/porter.yaml
When installing, let the user override with PORTER_HOME and PORTER_MIRROR the location where porter should be installed, or the location from which it should be downloaded.
I have updated the porter CLI to understand the new configuration value PORTER_MIRROR, which and also be specified as a flag or config file setting.
This lets us test out alternate download infra from end-to-end, and also allows a user to set up a mirror of Porter's assets.
I am also getting rid of the troubleshooting I had added for Azure's storage and CDN now that we aren't using it anymore (e.g. dynamically generated PORTER_TRACE user agents).
Fixes https://groups.io/g/porter/message/30
N/A
=> Allow overriding home dir and download url during install

pkg/build/build.go, pkg/build/dockerfile-generator.go, pkg/build/dockerfile-generator_test.go, pkg/build/provider/docker.go, pkg/porter/build.go, pkg/porter/build_test.go
* Generate a Dockerfile at .cnab/Dockerfile instead of in the root of the bundle directory. This avoids us overwriting a file that isn't owned by the bundle (e.g. they have the bundle defined at the root of their repo and also have their own Dockerfile). It also keeps all the rando files generated by Porter in a single tidy location we can all ignore.
* Cleanup the entire .cnab/ directory between builds instead of just the Dockerfile. Otherwise we copy in old mixins that may not be used anymore and generally open ourselves up to non-repeatable builds.
Closes #1162
=> Generate Dockerfile into .cnab/ directory

pkg/porter/archive.go, tests/archive_test.go
* Adds logic to ensure identical archive shasums are produced, provided the same bundle is used
Uses the approach of zero-ing out the timestamps for all archive files to achieve this.  As seen in https://unix.stackexchange.com/questions/346789/compressing-two-identical-folders-give-different-result and suggested by @sebumd in the original issue https://github.com/getporter/porter/issues/1526
Closes https://github.com/getporter/porter/issues/1526
* The original timestamps for all files in an expanded archive will no longer be preserved
* For testing, I updated the archive integration test to _not_ use a randomized bundle name and reference, so that we get a deterministic archive hash for matching on
If this is your first pull request, please add your name to the bottom of our …
=> fix(archive.go): repeatable shasum on archive

docs/content/install.md
We need to export the configuration variable instead of setting it on the same line because the environment variable needs to be set for the command after the pipe. Setting it on the same line results in the config value being ignored.
N/A
N/A
=> Fix configuring install script

pkg/exec/action.go, pkg/exec/builder/execute.go, pkg/exec/builder/execute_test.go, pkg/exec/builder/output_jsonpath_test.go
This PR adds support to change the working directory per step
```yaml
install:
- exec:
description: "uname"
command: uname
dir: "/home"
```
Closes #1403
I wasn't sure how to verify modification of the working directory when running tests. That's why I create a draft PR before diving into docs and schema
=> add support for setting working directory per step

Makefile, build/azure-pipelines.pr-automatic.yml, build/azure-pipelines.release-template.yml
To help speed up PR turnaround, just lint example bundles and make sure
that they have a correct porter manifest. Nothing about the example
bundles really exercise edge cases, they aren't test and we just want to
make sure that when we change Porter, the examples don't get out-of-date
which linting will catch.
Part of #1546 
In a follow-up I will have the build conditionally build the bundle if it was modified.
=> Only lint example bundles for pull requests

CONTRIBUTING.md, Makefile, magefile.go, pkg/porter/schema_test.go
Some of the tests, notoriously the schema test, relies on a "golden"
test file. The test output is compared against that file to determine if
the command output of `porter schema` is correct.
Changing the schema is difficult because you have to know how to update
that test file.
I have updated the test to detect if the schema has changed and prompt
you to run this new target `mage updateTestfiles` if you intended to
change the schema. It will handle updating the golden file to match the
new output of the test for you.
This will make it easier for new contributors to make changes that touch the schema.
N/A
=> Add updatetestfiles target

.gitignore, CONTRIBUTING.md, Makefile, build/azure-pipelines.integration.yml, build/azure-pipelines.pr-automatic.yml, build/azure-pipelines.release-template.yml, cmd/exec/schema.go, cmd/porter/main.go, cmd/porter/main_test.go, docs/content/contribute/tutorial.md, go.mod, go.sum, pkg/exec/exec.go, pkg/exec/schema.go, pkg/exec/schema_test.go, pkg/pkgmgmt/feed/template.go, pkg/pkgmgmt/search.go, pkg/porter/porter.go, pkg/templates/templates.go
* Remove packr dependency
* Switch to go:embed
* Upgrade to Go 1.16. Consumers of porter will need to be on this version to compile.
Closes #1553 
Closes #1394
🚨 This relies on #1564. Only the last commit in this PR is from my branch. I'll rebase when it's merged.
=> Upgrade to Go 1.16 and use go:embed

pkg/templates/templates/create/.gitignore
* Removes the `Dockerfile` entry in the `.gitignore` file added to `porter create`'d bundles, per https://github.com/getporter/porter/pull/1545
=> fix(create/.gitignore): remove Dockerfile entry 

mixin.mk
* Removes the flags/opts to disable http2 when building mixins
I believe these were added to debug and/or improve stability when Porter used a different cdn/hosting setup.  We should be good to remove them.
=> ref(mixin.mk): remove disable http2 flags/opts

CONTRIBUTING.md, Makefile, mage/tools/install.go, magefile.go, mixin.mk
This updates our commands that interact with Go to not explicitly set GO111MODULE=on. Go mods are enabled by default in 1.16.
Before the build targets are executed, they check that you have Go 1.16+
Helps out contributors so they don't get odd build errors.
=> Remove GO111MODULE and require Go 1.16

.github/workflows/close-issues.yaml
GitHub only closes issues when the pull request is merged into the default branch (main). This github action will watch merges into another branch (in this case v1) and close issues for those pull requests as well.
It's super annoying to fix something and have to remember to manually close it.
N/A
=> Close issues when we merge into v1 branch

docs/content/author-bundles.md, pkg/cnab/config-adapter/adapter.go, pkg/cnab/config-adapter/adapter_test.go, pkg/cnab/config-adapter/stamp_test.go, pkg/cnab/config-adapter/testdata/porter-with-maintainers.yaml, pkg/manifest/manifest.go, pkg/manifest/manifest_test.go, pkg/manifest/testdata/simple.porter.yaml, pkg/porter/testdata/schema.json, pkg/templates/templates/schema.json
This PR adds support for specifying maintainers in porter.yml.
```yaml
maintainers:
- name: "John Doe"
email: "john.doe@mail.com"
url: "https://domain.com/a"
- name: "Jane Doe"
url: "https://domain.com/b"
- name: "Janine Doe"
email: "janine.doe@mail.com"
- email: "mike.doe@mail.com"
url: "https://domain.com/c"
```
Generated CNAB `bundle.json` will contain specified maintainers.
Both - maintainers and the nested fields - are optional.
Closes #1559
Had to update the simple manifest digest in `pkg/cnab/config-adapter/stamp_test.go`.
=> Add support for maintainers

docs/content/install.md, scripts/install/install-linux.sh, scripts/install/install-mac.sh, scripts/install/install-windows.ps1
Only the exec mixin should be installed by default with Porter. All other mixins and plugins should be managed separately.
Closes #1192 
N/A
=> Only install exec mixin with Porter

docs/config.toml, docs/content/quickstart/_index.md, docs/content/quickstart/parameters.md, workshop/hello-llama/helpers.sh, workshop/hello-llama/porter.yaml
Second part of the quickstart that walks through how to set parameters with a flag or parameter set.
N/A
Ideally there was be sub menus under quickstart but I'd rather get the content out first then work with @flynnduism to get our nav bar to do what we want.
=> QuickStart: Parameters

pkg/cnab/config-adapter/testdata/porter-with-maintainers.yaml, pkg/porter/parameters.go
Signed-off-by: div_bhasin <divbest99@gmail.com>
When using `porter parameters generate...`, we see only the number of parameters in the parameter set being generated now. Look at the "Porter Command and Output" screenshot in #1600 to see what was wrong before. For the same command, we now get:
Closes #1600 
For the "1 parameters declared for bundle..." in the above screenshot, should I change the "parameters" to "parameter(s)" to account for the above case where we might only have 1 parameter in the parameter set? Alternatively, we could also do a switch/if statement to be more precise.
=> Count only the parameters in the parameter set

docs/content/docker-images/agent.md, examples/porter-agent-manifest.yaml
This expands the doc on porter-agent docker image page to explain how it is used by the porter operator, and includes a sample set of manifests to run it outside of the operator so that people can understand what it does.
=> Document how to use the porter-agent image

go.mod, go.sum, pkg/cnab/config-adapter/adapter.go, pkg/cnab/config-adapter/adapter_test.go, pkg/cnab/provider/testdata/bundle-with-param-sources.json
Big bump energy
* jsonschema-lock is finally merged and we can get rid of our fork
* Allow numbers in bundle.json again
* Add support for params of type array
* Add ValidateSchema function
* Add output validation
* Validate parameter defaults
* Validate param regardless of if override or default
* Fix retrieval of outputs when characters in the result id are in the
output name
* Add support for params of object type in ConvertValue (#251)
* Use alternate canonical json library
* Bump docker libraries to newer version
=> Bump cnab-go to v0.20.0

pkg/porter/parameters.go
It is a followup to https://github.com/getporter/porter/pull/1608. To cover the case where we might have a single parameter, it is better to display "parameter(s)" instead of "parameters".
As noted above, it's a followup to a previous PR. That other PR closed #1600 
=> Small grammar fix

.github/pull_request_template.md
the absolute paths work great when looking at the template, but when the PR is opened, the links are absolute against github.com instead of our repo.
The links in the PR template don't work when the PR is opened.
N/A
=> Fix links in Pull Request Template

pkg/manifest/manifest.go, pkg/manifest/manifest_test.go
* Adds validation of the schema/definition itself for parameters and outputs
Follow-up validation now that v1 has the latest cnab-go release.
=> feat(manifest): add parameter/output schema validation

docs/static/schema/json-schema.json
Porter allows one additional type for paramters and outputs, "file". Make a custom json schema available for validating porter.yaml files that includes the custom type.
https://deploy-preview-1628--porter.netlify.app/schema/json-schema.json
=> Host custom json schema document for Porter 

CONTRIBUTING.md, Makefile, build/azure-pipelines.pr-automatic.yml, build/azure-pipelines.release-template.yml, go.mod, go.sum, mage/git.go, mage/releases/build.go, mage/releases/publish.go, magefile.go, tests/integration/outputs_test.go
This fixes a bunch of small problems that snuck into the v1 build:
* The v1 integration tests were broken because they weren't compiling after a struct was renamed. I have updated test-unit so that it compiles (doesn't run) the integration tests so that we catch that problem quickly in a PR next time.
* Remove unused target verify
* Move test-unit into mage
* The new cnab-go validation was validating things that it shouldn't (https://github.com/cnabio/cnab-go/pull/262)
* I see dead people but not typos
* Do not use the branch name for the permalink when building pull requests, just use "dev"
=> Fix v1 build

build/azure-pipelines.pr-automatic.yml, build/azure-pipelines.release.yml, magefile.go
* Install extra mixins used by examples
* Refine tag filter for release builds
Do not trigger release builds when we tag v1-latest or v1-canary in order to host binaries for those permalinks. They aren't real releases.
=> Fix v1 release build

mage/git.go, mage/releases/build.go, mage/releases/publish.go, magefile.go, pkg/pkgmgmt/feed/feed.go, pkg/pkgmgmt/feed/feed_test.go, pkg/pkgmgmt/feed/generate_test.go, pkg/pkgmgmt/feed/testdata/atom-existing.xml, pkg/pkgmgmt/feed/testdata/atom.xml
* Now that we will have prerelease versions of the exec mixin available, porter mixin install exec is failing, because it's resolving the mixin @ v1-canary. Latest should resolve to the most recent _stable_ version available, which excludes the -canary entries.
* I also fixed the sorting of the entries in atom.xml so that when two binaries have the same timestamp, they sort consistently by name and version.
* Fixed LoadMetadata typo
* Fixed appending the .exe file extension during cross compilation.
As soon as I published the exec mixin with v1-canary, it broke anyone who ran `porter mixins install exec --version latest`. The workaround is to pick a specific version until a new release is cut with this fix.
N/A
=> Do not resolve prerelease versions with latest

mage/git.go, mage/git_test.go
Don't assume the first branch name will work. Loop through matching refs, excluding tags, and look first for main and then for release/v*. This better accounts for how the git repo looks in CI.
=> Fix branch name detection

docs/config.toml, docs/content/credentials.md, docs/content/parameters.md, docs/content/quickstart/_index.md, docs/content/quickstart/credentials.md, docs/content/quickstart/parameters.md, docs/themes/porter/layouts/section/single.html, examples/credentials-tutorial/.dockerignore, examples/credentials-tutorial/.gitignore, examples/credentials-tutorial/Dockerfile.tmpl, examples/credentials-tutorial/README.md, examples/credentials-tutorial/helpers.sh, examples/credentials-tutorial/porter.yaml
* Add quickstart for credentials
* Clarify the credentials page based on questions we have received
* Add a crede faq about how to export and use a credential set
* Add an example bundle that demonstrates credential sets
https://deploy-preview-1651--porter.netlify.app/quickstart/credentials/
https://deploy-preview-1651--porter.netlify.app/credentials/
Other pages are affected, mostly to add links to the updated docs.
Part of #1513 
I feel like the docs need to be completely rewritten in a lot of places. But I don't have time to do that so I'm just filling in gaps based on the questions I'm getting on slack.
=> Improve credentials documentation

go.mod, go.sum
I submitted my fix upstream to the jsonschema library and had to rebase so the reference to the PR in our go.mod file changed.
Builds of porter where the local go mod cache is empty and doesn't have cached the old branch sha. After this is merged I'll immediately merge into v1.
N/A
=> Fix go.mod entry for jsonschema

pkg/manifest/manifest.go, pkg/porter/explain.go, pkg/porter/explain_test.go
I have consolidated the logic for checking if a scoped item: parameter, credential or output, should be included in the output of explain to avoid errors when duplicating the logic for each one.
There was also a copy/paste of the appliesTo logic for ParameterDefinition (our def of a parameter in the porter manifest) that
I updated to implement Scoped so that we can hopefully avoid more problems with this type of check.
Closes #1667
N/A
=> Fix applyTo check for outputs in porter explain

Makefile
Sometimes the example builds fail but without the docker output we can't tell why. I've added the --debug flags so that the next time it fails we can get a better idea of what is flaky inside some of our example bundles.
=> Debug why example build is failing

cmd/porter/main.go, cmd/porter/main_test.go
We should print help text in the following scenarios:
* porter
* porter help
* porter --help
The reason why this isn't happening by default is because our root command implements Run. This allows us to print the version for either:
* porter --version
* porter version
There are tests now for all of the behaviors above to catch regressions.
Closes #1673
=> Print help when no args are passed

mage/git.go, mage/git_test.go
BUILD_SOURCEBRANCH is populated for branches _and_ tags. Oops. This fixes how we use that variable to differentiate between a branch and tag build. This addresses the problem on the last release I did yesterday where the build didn't properly read the tag, and thought it was a branch build when it was a tag build.
I'm not happy with it either...
=> Fix tag detection on azure pipelines

docs/config.toml, docs/content/project/short-links.md, docs/static/_redirects
Add a shortlink /pull-requests to goes to all open pull requests in the getporter organization. I've also documented all of our shortlinks so that it's easier for people to discover them.
https://deploy-preview-1694--porter.netlify.app/board/pull-requests/
https://deploy-preview-1694--porter.netlify.app/project/short-links/
N/A
N/A
=> Add shortlink for all pull requests

docs/content/author-bundles.md, pkg/cnab/config-adapter/adapter.go, pkg/cnab/config-adapter/adapter_test.go, pkg/cnab/config-adapter/testdata/porter-with-parameters.yaml
When the type is omitted on a parameter or output declaration in porter.yaml, default the type. If a path is specified, default to file, otherwise default to string.
Closes #1691
N/A
=> Default parameter and output types

CONTRIBUTORS.md, docs/themes/porter/assets/sass/docs-layout.scss, docs/themes/porter/assets/sass/docs-responsive.scss, docs/themes/porter/assets/sass/foundation/components/_offcanvas.scss, docs/themes/porter/assets/sass/helm-home.scss, docs/themes/porter/layouts/partials/footer.html
Menu now scroll separately and finitely
https://user-images.githubusercontent.com/51229945/126903548-a8301981-1f28-4ada-a1ee-82f49d7c934c.mp4
Closes #1682 
In desktop the box shadow of `<a class="exit-off-canvas"></a>` interfaces ui of scroll bar
There are three options to fix this,
- Use custom scroll bar style
- Remove `<a class="exit-off-canvas"></a>` completly
-  Remove box shadow property, possibly this https://github.com/getporter/porter/blob/05332860d3ad92a05d30f740165e7609106c6c4e/docs/themes/porter/assets/sass/foundation/components/_offcanvas.scss#L280
Due to `<a class="exit-off-canvas"></a>` in my changes home page doesn't scroll when menu is open.
=> doc(styles): Scroll menu and main content separately

docs/themes/porter/assets/sass/docs-content.scss, docs/themes/porter/layouts/partials/js.html, docs/themes/porter/static/js/custom/copy_code.js
Adds copy button to every command in docs
Copy button can be used to quickly copy commands which saves time especially when commands are long
Closes #1688 
I have not tried to put the copy button to the right of the code since it takes space resulting in reducing the code view area.
The button in the top right looks nicer.
=> docs(code): Introduce copy code feature

cmd/porter/bundle_test.go, pkg/porter/install.go, pkg/porter/install_test.go, pkg/porter/lifecycle.go, pkg/porter/lifecycle_test.go
Install requires a bundle definition from either --reference, --file,
--cnab-file or from the bundle in the current directory. The other
commands can either use those or use the installation name to look up
the bundle definition.
I found a way to get install to execute without specifying a bundle
definition and it blew up later in code that execpted that this had
already been validated. The command was
porter install --creds aks
I didn't specify a --reference or anything and wasn't in a bundle
directory.
Hopefully this plugs the gaps in wher we check for this condition.
NA
I will merge this into v1 after it's merged into main.
=> Fix check for if a bundle was provided

build/images/workshop/Dockerfile
The workshop docker image has broken because it was using a deprecated URL to install helm. This is breaking all our builds.
=> Fix helm download in workshop image

cmd/porter/credentials.go, cmd/porter/installations.go, cmd/porter/parameters.go, docs/content/cli/credentials_list.md, docs/content/cli/installations_list.md, docs/content/cli/list.md, docs/content/cli/parameters_list.md, pkg/porter/credentials.go, pkg/porter/credentials_test.go, pkg/porter/list.go, pkg/porter/list_test.go, pkg/porter/parameters.go, pkg/porter/parameters_test.go, tests/smoke/hello_test.go
Add an `--all-namespaces` flag to porter installation|credential|parameter list commands. This is the equivalent of `list -n "*"`
Closes #1709 
Relies on #1701 and will need a rebase after that is merged.
=> All namespaces

cmd/porter/credentials.go, cmd/porter/parameters.go, docs/content/cli/credentials.md, docs/content/cli/credentials_apply.md, docs/content/cli/parameters.md, docs/content/cli/parameters_apply.md, docs/content/configuration.md, pkg/cnab/provider/credentials.go, pkg/credentials/credential_store.go, pkg/credentials/provider.go, pkg/parameters/parameter_store.go, pkg/parameters/provider.go, pkg/porter/credentials.go, pkg/porter/credentials_test.go, pkg/porter/parameters.go, tests/smoke/hello_test.go, tests/smoke/main_test.go, tests/smoke/testdata/config.toml, tests/testdata/creds/mybuns.yaml, tests/testdata/mybuns/Dockerfile.tmpl, tests/testdata/mybuns/porter.yaml, tests/testdata/params/mybuns.yaml
* Add a new command for credential and parameter sets which allow you toapply changes (or create net new) from a file.
* Fixes how we resolve params and credentials to allow referencing a global cs/ps from within a namespace during install.
This is part of #1703. Next up is for installations which is a bit more complex.
N/A
=> Add apply command for creds and params

cmd/porter/main.go, pkg/porter/credentials.go, pkg/porter/explain.go, pkg/porter/lifecycle.go, pkg/porter/parameters.go, pkg/porter/pull.go, pkg/porter/pull_test.go
--tag was used in the early days of porter and was replaced by --registry and --reference. In v1 it is no longer supported.
Part of #1717
=> Remove deprecated tag

cmd/porter/main.go, docs/content/cli/archive.md, docs/content/cli/build.md, docs/content/cli/bundles.md, docs/content/cli/copy.md, docs/content/cli/create.md, docs/content/cli/credentials.md, docs/content/cli/explain.md, docs/content/cli/inspect.md, docs/content/cli/install.md, docs/content/cli/installations.md, docs/content/cli/invoke.md, docs/content/cli/lint.md, docs/content/cli/list.md, docs/content/cli/logs.md, docs/content/cli/mixins.md, docs/content/cli/parameters.md, docs/content/cli/plugins.md, docs/content/cli/porter.md, docs/content/cli/publish.md, docs/content/cli/schema.md, docs/content/cli/show.md, docs/content/cli/storage.md, docs/content/cli/uninstall.md, docs/content/cli/upgrade.md, docs/content/cli/version.md
The old help text was using the porter emoji of old and also didn't describe itself well.
Let's use the same text that we have on the homepage to explain what the tool is.
https://deploy-preview-1722--porter.netlify.app/cli/porter/
NA
None
=> Update help text description of porter

pkg/cnab/provider/driver.go, pkg/cnab/provider/driver_test.go
Sometimes the invocation image only exists in the local docker cache but was never pulled. In that case, there isn't a repository digest for the image in the cache and it will fail validation.
Always pulling, will ensure that the repo digest is always populated to avoid unexpected errors about missing digests.
The docker driver looks for the environment variable PULL_ALWAYS
Fixes #1439
The impact of this is that you cannot use --reference when you haven't pushed the invocation image. Mostly this just closes an accidental loophole where you could be using the definition of a bundle that has been published (and therefore has a digest in the bundle.json for the invocation image) with an invocation image that is only in the local docker cache. That is wonky and we shouldn't allow that …
=> Always pull the invocation image

pkg/cnab/provider/driver.go, pkg/cnab/provider/driver_test.go
This reverts commit 19a26751930e6202bb9e34ef7cd4bbe21de5ff71.
The change is still something we want eventually but it has exposed
problems elsewhere in our codebase that are hard to track down. Namely
that when we run the integration tests all at once (not just one at a
time manually), the test changes behavior and tries to pull when it
normally wouldn't when run separately.
This causes problems because some of our bundles do exist with the same
reference in dockerhub, but they have a different definition. So pulling
causes all sorts of test failures.
While I track all of this down, I'm going to revert this change until I
can get all the bugs worked out with it.
=> Revert "Always pull the invocation image (#1723)"

pkg/runtime/runtime.go, tests/smoke/hello_test.go, tests/testdata/mybuns/helpers.sh, tests/testdata/mybuns/porter.yaml
When a bundle fails, we still need to collect any generated outputs because they may contain state that is needed for the next run.
What I am running into is that when I install a bundle that uses terraform, and it fails, the tfstate file output is not persisted, so I can't repeat the install command again.
I found this bug and was immediately so enraged that I had to fix it immediately
N/A
=> Always collect outputs even when bundle fails

pkg/cnab/parameter_sources.go
This was a debug print statement that I meant to just add while fixing something locally. It shouldn't be printed every time you run a bundle!
=> Remove debug print statement

build/azure-pipelines.integration.yml, build/azure-pipelines.pr-automatic.yml, build/azure-pipelines.release-template.yml
This bumps some of the CI environment variables that we use to configure our CI instrastructure.
* ubuntu 16.04 LTS is being deprecated from Azure pipelines. I'm switching to just following ubuntu latest since we don't rely much on anything distro specific.
* We require go 1.16+ now (for v1+) so I'm going to just bump that as well right now.
=> Bump CI environment variables

docs/content/mixins/helm3.md
Document how to specify multiple values.
Closes https://github.com/MChorfa/porter-helm3/issues/24
=> Update helm3 mixin doc

docs/content/mixins/exec.md, pkg/exec/builder/output_jsonpath.go, pkg/exec/builder/output_jsonpath_test.go, pkg/exec/builder/testdata/install-output.json
When we parse outputs for jsonPath expressions, numbers are not being formatted as expected. For example, a number like "123123123" is being output as "1.23123123e+08".
This is due to how we are parsing the jsonPath. The output is marshaled into a generic map, where json numbers are represented as float64. We use fmt.Sprintf to format the matching output value, and Go by default formats float with %f/%g, neither of which is the desired format.
I've updated our json parsing to use the Number type so that the format of the captured value matches what was used in the original output.
Fixes #1754
They who provide test data to reproduce, get fast bug fixes. ❤️
=> Properly format numbers parsed from jsonPath outputs

examples/airgap/porter.yaml
Helm2 is deprecated and the example doesn't work anymore because of that. Switch to the helm3 mixin.
=> Use helm3 for the airgap example

pkg/porter/outputs.go, pkg/porter/outputs_test.go
Do not include internal outputs, such as porter-state.tgz when listing outputs.
We don't want to expose internals in our commands like explain, and listing outputs.
=> Hide internal outputs from porter installation outputs list

docs/content/blog/v1-alpha3.md, docs/content/blog/v1-roadmap.md
Add a blog post announcing the v1.0.0-alpha.3 prerelease, highlighting key features and explaining how to install it safely.
https://deploy-preview-1768--porter.netlify.app/blog/v1-alpha3/
=> Announce v1.0.0-alpha.3

magefile.go
In order to completely switch over to helm3 we need one more feature in the helm3 mixin, --create-namespace, since our unit tests rely on that.
So I'm adding it back for now to get the tests passing until we can merge #1772.
=> Continue installing the helm2 mixin

cmd/porter/bundle.go, docs/content/cli/bundles_install.md, docs/content/cli/bundles_invoke.md, docs/content/cli/bundles_uninstall.md, docs/content/cli/bundles_upgrade.md, docs/content/cli/install.md, docs/content/cli/invoke.md, docs/content/cli/uninstall.md, docs/content/cli/upgrade.md, pkg/cnab/provider/action.go, pkg/porter/lifecycle.go, tests/smoke/hello_test.go, tests/smoke/main_test.go
Add a flag to the bundle actions allowing the user to skip saving a copy of the logs to Porter's datastore.
```
porter install --no-logs
```
Now when they run `porter logs -i mybuns`, it will return "no logs found".
This is useful in cases where the logs are too large to store.
Closes #1778 
I will cherry-pick this into v1 after this is merged.
=> Make log persistence configurable

docs/content/plugins/mongodb.md, pkg/claims/claimstore.go, pkg/cnab/config-adapter/stamp_test.go, pkg/credentials/credential_store.go, pkg/parameters/parameter_store.go, pkg/storage/migrations/manager.go, pkg/storage/plugin_adapter.go, pkg/storage/plugins/mongodb/mongodb.go, pkg/storage/plugins/mongodb/plugin.go, pkg/storage/plugins/mongodb_docker/plugin.go, pkg/storage/plugins/storage_protocol.go, pkg/storage/query.go, pkg/storage/store.go, tests/tester/main.go
* Consolidate creating indices into just 3 calls. We can further refine this in #1782, when we make initializing the db a single event.
* Do not ping on connect in the mongodb plugin. This does mean that the first query will be slower as it will establish the connection. So let's be aware of that and not assume the first call just has horrible performance.
I am still looking into why the first call that establishes the connection has bad performance. https://www.mongodb.com/community/forums/t/establishing-a-connection-is-slow/125826
I was creating each index in its own call but there's actually a different function on the mongodb client that I can use to batch those calls up to improve performance.
NA
=> Reduce how often we hit the database

go.mod, go.sum, pkg/cnab/cnab-to-oci/registry.go
When cnab-to-oci fixes up a bundle after publishing it, if any error occurs we only get a single error message
"failed to fixup the image for service InvocationImage"
This bumps our cnab-to-oci to use the patch in
cnabio/cnab-to-oci#113
so that we get a more detailed error message that indicates the image that failed, and which fixup step.
Incorporates the fix from cnabio/cnab-to-oci#113
I am referencing a fork of cnab-to-oci that is published in the getporter org because I don't expect the patch to merge quickly.
=> Improve error message when cnab-to-oci fixes up a bundle

docs/content/custom-dockerfile.md, pkg/porter/create.go, pkg/porter/create_test.go, pkg/templates/templates.go, pkg/templates/templates/create/README.md, pkg/templates/templates/create/porter.yaml, pkg/templates/templates/create/template.buildkit.Dockerfile, pkg/templates/templates/create/template.docker.Dockerfile
Change the generated dockerfile template to use `.Dockerfile` file extension to get syntax highlighting in IDEs.
Closes  #1771
N/A
=> Rename Dockerfile.tmpl to template.Dockerfile

pkg/build/dockerfile-generator_test.go, pkg/cli/config_test.go, pkg/config/config.go, pkg/config/config_test.go, pkg/config/datastore.go, pkg/porter/build.go, pkg/porter/porter.go, pkg/templates/templates.go, pkg/templates/templates_test.go
There are two config settings that control which build driver we use:
* experimental
* build-driver
The experimental feature needs to be enabled in order for the build-driver setting to take effect. When I was testing another PR, I realized that in some parts of the code, I was only checking the build-driver setting without making sure the experimental feature was
enabled.
This adds a function GetBuildDriver to Config that we can use to centralize that logic.
Found this while testing #1817 
N/A
=> Fix build driver experimental flag checks

netlify.toml
Fix how the root url is calculated for branch deploys, so that it keeps the special branch subdomain.
e.g. release-v1.porter.sh instead of release-v1--porter.netlify.app
A lot of the links on the porter website are absolute (for reasons). This meant that on the https://release-v1.porter.sh website some links (like the top level navigation) were all sending the user to https://release-v1--porter.netlify.app which is confusing.
This will keep the user on the same domain while using the v1 prerelease site.
This was tested out here: https://test.porter.sh, note that the links in the top nav stay on the same domain now.
=> Fix branch deploy

netlify.toml
Sorry #1833 caused a regression in the v1 website. This test branch that I'm using for the PR is named `fix/branch-deploys` to accurately test that the / is handled correctly. https://fix-branch-deploys.porter.sh.
Replace / with - in branch names, so that release/v1 resolves to https://release-v1.porter.sh
=> Fix branch deploys of website

pkg/porter/porter.go, pkg/porter/porter_test.go
I accidentally tried to use a fallthrough, which go doesn't support. I
have fixed GetBuilder and added a unit test to validate that it is
creating a build driver for all cases.
Fixes regression from #1825 
Sorry I didn't catch this in the PR!
=> Fix GetBuilder

.gitignore, pkg/cnab/cnab-to-oci/helpers.go, pkg/cnab/cnab-to-oci/provider.go, pkg/cnab/cnab-to-oci/registry.go, pkg/porter/copy.go, pkg/porter/publish.go, tests/smoke/copy_test.go, tests/smoke/hello_test.go, tests/smoke/main_test.go
This allows users to successfully copy bundles that use source images in a repository they don't have access to.
Closes #1814 
=> Fix Pushing Bundles that have a relocationMap

cmd/porter/completion.go, cmd/porter/completion_test.go, cmd/porter/main.go, docs/content/cli/completion.md, docs/content/cli/porter.md, docs/content/install.md
This adds the standard Cobra completion command to Porter.
Example:
`porter completion bash > /path/to/shell/completion/files/porter`
```
porter bu[tab][tab]
build bundles
```
Closes #1757
This also adds a test to ensure it completes without error.
This does not include dynamic querying for custom completions.
I also created setup and usage documentation on the bottom of the `/install` web page.
=> 1757  completion command

docs/content/docs.md, docs/themes/porter/layouts/partials/docs-sidebar.html, docs/themes/porter/static/css/custom.css
Makes it easier for people to know which version of the docs they are on (v0.38 or v1.0.0) and switch between the two. Long term, a better strategy for versioning the docs site would be great but this is a small change that we can do right now.
N/A
This PR has a buddy: See #1850.
=> Link to the stable docs from v1 site

CONTRIBUTORS.md, pkg/templates/templates/create/porter.yaml
Change default registry for new bundles from `getporter` to `"localhost:5000"`
Closes #1758 
* Changed default registry
* `make test-unit` and `mage testSmoke` passing
* Verified generated porter.yaml file when running `porter create`
=> Change default registry to localhost:5000

cmd/porter/bundle.go, docs/content/cli/build.md, docs/content/cli/bundles_build.md, docs/content/cli/bundles_install.md, docs/content/cli/bundles_invoke.md, docs/content/cli/bundles_uninstall.md, docs/content/cli/bundles_upgrade.md, docs/content/cli/install.md, docs/content/cli/invoke.md, docs/content/cli/uninstall.md, docs/content/cli/upgrade.md, tests/integration/driver_test.go
This binds the --driver flag for porter install|invoke|upgrade|uninstall
to the PORTER_RUNTIME_DRIVER environment variable used by the operator.
I had already done this for PORTER_BUILD_DRIVER, but missed adding
similar configuration bindings for runtime.
So in the config file, the user can set runtime-driver and build-driver.
The environment variables are named: PORTER_RUNTIME_DRIVER and
PORTER_BUILD_DRIVER. The flag though on any command is just --driver for
simplicity, e.g. porter install --driver kubernetes.
I added docs to the CLI helptext for the affected commands to explain that you can use these environment variables: https://deploy-preview-1848--porter.netlify.app/cli/porter_bundles_install/
This is part of https://github.com/getporter/operator/issues/27.
N/A
=> Fix setting --driver with env variables

pkg/cnab/cnab-to-oci/helpers.go, pkg/cnab/cnab-to-oci/provider.go, pkg/cnab/cnab-to-oci/registry.go, pkg/porter/stamp.go
Check whether the invocation image exists in the host registry and trigger autobuild of the image by setting the return value of `IsBundleUpToDate` to `false`.
Closes #1756
=> Porter triggers autobuild when detecting that invocation image does not exist

tests/integration/dependencies_test.go, tests/integration/invoke_test.go, tests/integration/outputs_test.go, tests/integration/rebuild_test.go, tests/integration/suppress_output_test.go
The integration tests accidentally were passing nil for the context
after I added context.Context as a parameter to some Porter commands in #1831.
This passes in context.Background to fix the nil pointer exceptions that
was causing.
Fixes the porter-integration build on release/v1
Sorry I forgot to manually run the integration tests on that PR before merging. I'll add integration tests to the PR checklist template.
=> Pass context from integration tests

mage/mixins/doc.go, mage/mixins/magefile.go, mage/releases/build.go, mage/releases/git.go, mage/releases/git_test.go, mage/releases/publish.go, mage/setup.go, mage/tools/install.go, magefile.go
The mage/mixins package contains common magefile targets that all mixins
use: build, test, publish, etc. This minimizes the amount of custom
logic in our magefiles and should make it easier to manage the magefile
in all the mixins going forward.
Deals with some longstanding drift between all the mixins build script logic. This should get them all on the same page.
I am testing this out with the docker-compose mixin first in https://github.com/getporter/docker-compose-mixin/pull/23. Please review these two PRs together and let me know if this looks like the right change to make to EVERY mixin repo. Once this is merged I'll make the same change everywhere, so I'd like to make sure this first PR has everything we want in it so I only have to update repos once. 😀
=> Add package for mixins magefile targets

mage/releases/publish.go
First check if we have a local copy of porter and use that to generate a mixin feed. Otherwise assume that porter is installed in the GOPATH.
Fixes publishing binaries for porter v1. When I made a change for mixins it broke it for porter... 🤦‍♀️ Happy 2022!
N/A
=> Use porter from the bin or the PATH

CONTRIBUTORS.md, pkg/config/datastore.go
This PR adds missing double quotes for Telemetry struct tag so it can be
properly set if present.
Part of https://github.com/getporter/porter/issues/1857
=> pkg/config: fix Telemetry struct tag

mage/docker/docker.go, mage/tests/kind.go
I accidentally committed changes to the magefile that broke
connectivity between the test kind cluster and the local registry
running in docker. They need to be on the same network.
This adds back code that I thought wasn't needed anymore to get docker
pulls from localhost:5000 from inside the cluster working again.
It fixes pulling images locally when using KIND to develop the operator
Nope
=> Add back lost docker network logic to magefile

pkg/agent/agent.go, pkg/agent/agent_test.go
The porter agent used to print the porter version before executing the requested command. When I rewrote the bash script as a go program, that regressed and it stopped printing it out.
This adds that back.
I noticed when testing the operator that this broke. It's mostly useful for troubleshooting since the image in the porter agent pod is by digest, not a tag that you could figure out the version from.
N/A
=> Print the porter version from the agent

cmd/porter/installations.go, cmd/porter/main.go, pkg/build/buildkit/buildx.go, pkg/cnab/provider/action.go, pkg/context/context_test.go, pkg/porter/apply.go, pkg/porter/install.go, pkg/porter/list.go, pkg/porter/list_test.go, pkg/tracing/logger.go, pkg/tracing/logger_test.go, pkg/tracing/scopedLogger.go, tests/integration/claim_migration_test.go
command
This PR adds instrumentation for list command. It also adds support for
automatically setting span name during creation by the caller function
name.
Some fixes for unclosed spans is included as well
related to #1857 
=> pkg/{porter,tracing}, cmd/porter: add tracing instrumentation for list

docs/content/reference/file-formats.md
This PR fix some typos in the file fomrats documentation
N/A
=> docs/content/reference: fix typo in /reference/file-formats.md

docs/content/blog/ignoring-errors.md
This adds a blog post about some new features in v1:
* Explain the new ignoreError feature in the exec mixin
* Show how developers can use this functionality to create custom commands for this mixin.
BLOG ALL THE THINGS!
I am going to tell people to make custom commands for mixins but we don't really have enough guidance for that yet. I've opened https://github.com/getporter/skeletor/issues/29 to help address that.
=> Blog: IgnoreErrors and Az group command

pkg/porter/explain.go, pkg/porter/explain_test.go, pkg/porter/testdata/explain/expected-json-output.json, pkg/porter/testdata/explain/expected-table-output.txt, pkg/porter/testdata/explain/expected-yaml-output.yaml, pkg/porter/testdata/explain/params-bundle.json
When porter explain prints a suggested installation command, it should
only include parameters that are required _and_ apply to the install
command. Parameters can be limited to only apply to a particular action
and if it doesn't apply to install, we don't want to tell people to
specify in for porter install.
I found this when running porter explain on the operator bundle, which has a parameter that only applies to the configureNamespace action.
N/A
=> Only include required install params in explain command

mage/mixins/magefile.go, mage/mixins/magefile_test.go, mage/mixins/testdata/.gitignore
I was accidentally copying the mixin runtime binary into the wrong
directory under PORTER_HOME.
If a developer is using a mixin that was using v1.0.0-* for its magefile install target, then the runtime for the mixin wasn't dropped in the right place for it to be picked up during porter build. This affects: skeletor, docker-compose.
Oops 🤦‍♀️ 
=> Fix the mixin install target

.gitignore, cmd/porter/main.go, docs/content/configuration.md, go.mod, go.sum, pkg/cli/config_test.go, pkg/config/config.go, pkg/config/config_test.go, pkg/config/loader.go, pkg/config/loader_test.go, pkg/config/testdata/config.toml, pkg/porter/lifecycle_test.go, pkg/porter/porter.go, pkg/tracing/traceLogger.go
Support templating in the Porter config file, e.g.
~/.porter/config.json|toml|yaml.
The template syntax uses a yaml-friendly delimiiter, ${}. For example,
${env.NAME} or ${secret.NAME}. If you are using toml or json for your
config file format, then you may need to use quotes around template
values to ensure that the config file has valid syntax when it is
loaded.
We load the config file first with only environment variables
substituted, then we initialize the secrets plugin, and finally do a
second pass of the config file to replace any secrets. So that first
pass needs to be a valid file based on the current format.
For example, in a porter.toml file, secrets should be quoted:
```toml
[[storage]]
name = "dev"
plugin = "mongodb"
[storage.config]
url = "${secret.connection-string}"
``` …
=> Add templating to porter config file

docs/static/_redirects
I've created a survey for users to let us know that they are using Porter. This adds a shortlink to make it easier to send it out to people.
We have no idea if people are using Porter, at what scale, and what they are relying upon.
Instant merging because it's a trivial change.
=> Add a shortlink to a user survey

docs/content/blog/secret-free-config.md
Explain the new templating feature in porter's config file and how to use it to keep sensitive data out of your config file
N/A
This is a companion blog post to #1879. That PR needs to merge first and a release cut before the blog post should be published.
Preview at https://deploy-preview-1884--porter.netlify.app/blog/secret-free-config/
=> Blog: Secret-free config file

README.md
Instead of sending people directly to the adopters.md page, try to get some info on who is using the project with a survey first.
=> Link to user survey on README

docs/content/install.md
* The operator requires the most recent version of the prerelease
* They should check for the most recent version as the example on the page may be older.
Our current docs were confusing and people were installing an older version of Porter that isn't compatible with the operator.
https://deploy-preview-1898--porter.netlify.app/install/
N/A
=> Clarify prerelease install instructions

pkg/cnab/cnab-to-oci/registry.go
This is a bug from our very first POC for porter. ❤️
When we push the invocation image for a bundle, instead of just pushing
the single tag that is used by the bundle, it is pushing every single
tag available for that image in the docker image cache.
This is why we were seeing increasingly worse performance when
publishing a bundle the more releases you did for it. I didn't notice
there was a problem until I bought a dedicated drive for my docker cache
and suddenly was keeping around  months of temporary builds of the
porter operator bundle and publish started taking 5+ minutes...
I was seeing multiple images being pushed in the porter publish logs.
<details>
```
Pushing CNAB invocation image...
The push refers to repository [localhost:5000/porter-operator-installer]
fc235af34b1f: …
```
=> Only push the current invocation image tag

go.mod, go.sum, pkg/config/loader.go, pkg/config/loader_test.go
Pin the osteele/liquid dependency to 1.3.0. Now that our patch exposing Template.GetRoot has been merged, this puts us back on the official upstream project.
N/A
I love it when patches get merged! 🎉
=> Pin liquid to 1.3.0

docs/content/cli/completion.md
The generated cli docs got out of sync at some point, so I've re-run mage docsgen to get it updated.
N/A
N/A
=> Sync generated cli docs

go.mod, go.sum, mage/mixins/magefile_test.go, pkg/claims/installation.go, pkg/claims/run.go, pkg/porter/lifecycle_integration_test.go
I originally thought that the concept of an installation document would be included in the cnab spec and Porter was working off of a fork that included those changes.
Now that we have taken a different direction with the CNAB dependency spec that doesn't require the runtime to search existing installations, that isn't necessary anymore.
This gets Porter off of the fork and back on the main branch of cnab-go.
N/A
N/A
=> Switch from a fork of cnab-go to main

pkg/cnab/docker.go, pkg/cnab/docker_test.go, pkg/cnab/file_parameter.go, pkg/porter/explain.go, pkg/porter/explain_test.go, pkg/porter/testdata/explain/bundle-docker.json, pkg/porter/testdata/explain/expected-table-output-docker.txt
When the bundle has docker as one of the required mixins, `porter explain` command warns for the host access in advance and also include `--allow-docker-host-access` flag for the installation command at the end.
I attached the screenshot for running the `porter explain` command for the `tabbycat-demo` bundle with `docker` added as one of the required mixins and also for the `whalesay` bundle.
Closes #1830 
=> Porter explain warns for docker host access

.github/workflows/close-issues.yaml
When we first started using the github action that closes issues that were merged into the v1 branch, github didn't have the pull_request_target workflow type. When you use just the regular pull_request type, and the PR came from a fork, the secrets.GITHUB_TOKEN is read only and cannot close an issue.
The new pull_request_target type works with forks.
This fixes errors like
`403 Resource not accessible by integration`
which required me to manually close issues when the PR was from a fork.
Me manually finding unclosed issues and dealing with them. 😁 
N/A
=> Fix close issues workflow

pkg/config/config.go, pkg/context/context.go
This PR allows setting logging correlation ID through `PORTER_CORRELATION_ID` env variable
Closes #1873 
=> pkg/{config/context}: set log correlation id through env variable

docs/content/author-bundles.md, docs/content/reference/file-formats.md, docs/static/_redirects, pkg/schema/credential-set.schema.json, pkg/schema/installation.schema.json, pkg/schema/parameter-set.schema.json
This PR improves porter's doc in two area:
1. host porter's schema on porter.sh
2. clarify image reference requirement
Closes #1908 and #1887 
=> pkg/schema, doc: improve doc for schema and bundle image reference

cmd/porter/completion_test.go, cmd/porter/docs.go, cmd/porter/main.go, cmd/porter/version.go, pkg/config/config.go, pkg/context/context.go, pkg/context/context_test.go, pkg/context/helpers.go, pkg/context/telemetry.go
When we run certain commands, such as help or version, we shouldn't even bother trying to load configuration. These commands should always execute quickly and never return an error.
I've added an annotation to commands that shouldn't load config: version, docs, porter and the help command/flag. When this annotation is set on a command, we skip loading config.
I have also set a timeout for attempting to connect to a trace exporter and fixed the error handling so that we gracefully continue to execute and only log a warning about the trace problem.
Tests were timing out and getting stuck up on bad config on my machine. Long term, tests should ignore the default config file and use a preset one. But this highlighted a problem with how we handle errors when creating a trace exporter that …
=> Prevent bad config from causing trouble

docs/content/mixins/exec.md, pkg/context/context.go, pkg/context/helpers.go, pkg/exec/action.go, pkg/exec/builder/execute.go, pkg/exec/builder/execute_test.go, pkg/exec/builder/output_jsonpath_test.go, pkg/exec/exec_test.go, pkg/exec/schema/exec.json, pkg/exec/testdata/install-input.yaml, pkg/pkgmgmt/client/install_test.go, pkg/porter/testdata/schema.json
This change add the ability for steps to add environment variables to be added to the env when executing the command for a step.
This change is related to https://github.com/getporter/az-mixin/issues/38. With this change, the mixin could add the user-agent env var to the command.
This is my first contribution here, so please let me know if I missed / misunderstood something.
=> enable steps to define environment variables

mage/releases/publish.go, mage/releases/publish_test.go, magefile.go
Publish checksums for all assets so users can validate whether the downloaded file has been tempered
Part of the fix for #1797 
Since only using checksum doesn't prevent the case when checksum file itself has been tempered, another PR will address that issue by using signing using a private key 
=> mage: add checksum for published assets

pkg/claims/installation.go, pkg/credentials/credentialset.go, pkg/parameters/parameterset.go
Assign `none` value when the schemaVersion was empty on `porter installation apply` command. 
Closes #1960 
=> Assign (none) for empty schemaVersion on applying installation

.github/workflows/close-issues.yaml
I have forked the close issue workflow and edited it to support the new pull_request_target event type. I have submitted PRs upstream to the original workflow but until they are merged we can use this build of the github action.
The close issue workflow only supports pull_request, which does not have permission to close issues when the pull request was created from a fork.
N/A
=> Fix close issue workflow

cmd/porter/main.go, pkg/cache/cache.go, pkg/cache/cached_bundle.go, pkg/cnab/config-adapter/helpers.go, pkg/porter/build.go, pkg/porter/build_integration_test.go, pkg/porter/cnab.go, pkg/porter/cnab_test.go, pkg/porter/dependencies.go, pkg/porter/install.go, pkg/porter/lifecycle.go, pkg/porter/lifecycle_integration_test.go, pkg/porter/lint.go, pkg/porter/options.go, pkg/porter/packages_test.go, pkg/porter/parameters.go, pkg/porter/porter.go, pkg/porter/publish.go, pkg/porter/reconcile.go, pkg/porter/run.go, pkg/porter/stamp.go, tests/integration/install_test.go, tests/integration/invoke_test.go, tests/integration/outputs_test.go, tests/integration/rebuild_test.go, tests/integration/suppress_output_test.go, tests/testdata/config/config.toml
These are changes necessary to have `porter explain` and `porter inspect` work with bundles created with an unsupported porter version.
**Do not require a supported porter.yaml file in the bundle cache**
It's important that we should be able to pull a bundle and fall back to working with it as a vanilla cnab bundle when it was built with an unsupported porter version. This removes trying to load the manifest from the bundle cache and each calling command will need to decide how to gracefully handle the bundle it pulls from the cache (i.e. some commands have to require a supported version, like build, but others like install can still work without a manifest).
**Remove Porter.Manifest field**
The porter struct has always had a Manifest field that is great at causing nil pointer exceptions …
=> Do not assume that all bundles have a supported porter.yaml file

.gitignore, Makefile, mage/docs/docs.go, mage/docs/docs_test.go, netlify.toml
Netlify caches the contents of the directory, so that it can avoid redownloading stuff each time. Our operator clone is being cached and we are ending up with stale content. This updates the operator repo before building the docs so that it has the latest content.
Part of https://github.com/getporter/operator/issues/45
N/A
=> Use latest operator docs during netlify build

build/azure-pipelines.integration.yml, build/azure-pipelines.pr-automatic.yml, build/azure-pipelines.release-template.yml
Go 1.17.6 has a security vulnerability, and this updates us to the most recently patched version of Go 1.17
=> Use Go 1.17.8 in build

go.mod, go.sum, mage/releases/git.go
I was writing to the file without considering that there could already have been content in the file, and therefore was undoing any env vars that other parts of the build had set.
This uses a new version of github.com/carolynvs/magex with built-in support for interacting with the CI system (so I don't mess it up again).
I couldn't set additional GitHub action environment variables in the Operator repository because this helper method was overwriting a file instead of appending.
N/A
=> Fix setting GitHub action env vars

go.mod, go.sum, netlify.toml
When I moved our magefile helpers into a separate repository, I had missed that the integration test helpers were relying on reading files from the current repository to create a kind cluster.
Now that the magefiles are in a separate repo, that doesn't work anymore. I've switched to using go:embed in the magefiles helpers and this bumps our reference to magefiles to pick up the change.
The integration tests on release/v1 can't create a kind cluster at the moment.
=> Bump magefiles to fix integration tests

.github/workflows/security-scan.yaml, .gitignore
If we use the Trivy GitHub action then we can get integrated security reports sent to GitHub. So I decided to build the porter agent image in GH actions so we can use trivy there.
This means that if the security scan fails, it won't block us from cutting a release of Porter.
Long term, it may make sense to move more of our builds to GH actions. This can be the first step.
I have also enabled CodeQL scanning so that issues either in the images or Go code itself can be tracked.
This helps us detect CVEs in our porter agent image before we cut a release and attempt to push to IronBank.
N/A …
=> Add GitHub action to scan our code and porter-agent image

pkg/cli/config.go
Add support for mapping the cobra flag type stringArray. Specifically we should be using stringArray when we do not want cobra to treat flag values with a comma as a comma separated list.
This is prep-work for #1862 and #1999 
N/A
=> Support stringArray cobra flag type

mage/docs/docs.go, mage/docs/docs_test.go, netlify.toml
I had made a change earlier to netlify.toml and forgot to use export when setting BASEURL. So at the moment when you go to release-v1.porter.sh or a pull request preview, the navigation links at the top all redirect back to porter.sh instead of using the unique BASEURL specific for that PR/branch.
I have moved the BASEURL logic into mage so that it's not as easy to break in the future (hopefully).
Note that in each preview, when you hover over the top nav links, they stay on the same domain
Branch Preview: https://fix-branch-deploys--porter.netlify.app/
PR Preview: https://deploy-preview-2003--porter.netlify.app/
Links at the top of release-v1.porter.sh go to pages on porter.sh instead of the v1 website links.
* Comment with /azp run test-porter-release if a magefile or build script was …
=> Fix website BASEURL

pkg/runtime/runtime-manifest.go
We shouldn't always be printing out log lines when executing the runtime manifest. Those were always intended to be debug lines and I just missed gating them with a Debug check.
This makes sure that they are only printed when --debug is speciifed and that they are printed to stderr.
I was running simple bundles and copying the output for our documentation and realize we are printing at the wrong level.
N/A
=> Make runtime manifest log output debug messages

CONTRIBUTORS.md, docs/content/authors/templates.md, pkg/cnab/provider/action.go, pkg/config/config.go, pkg/exec/builder/action.go, pkg/runtime/runtime-manifest.go, pkg/runtime/runtime-manifest_test.go
Signed-off-by: Jeremy Goss <jeremy.goss@hpe.com>
Adds a new template variable `installation.namespace` and strips namespace/ from `installation.name`.
Closes #2000.
As far as I can tell, none of the example apps assume installation.name contains a namespace or / character, so it should be safe to make this change.
- [x ] Did you write tests?
- [x ] Did you write documentation?
- [ x] If this is your first pull request, please add your name to the bottom of our [Contributors][contributors] list. Thank you for making Porter better! 🙇‍♀️
=> Add installation.namespace template var

.github/workflows/security-scan.yaml
When a pull request only affects the docs folder (documentation/website), then skip the security scan workflow so that someone can quickly iterate on a doc change without triggering long unnecessary builds.
I've also switched from pull_request to a pull_request_target workflow type to avoid anyone editing the workflow in their PR to skip the scan.
I hate waiting when the build isn't needed. 😀 
I think(?) the security scan workflow didn't trigger for this PR because we are switching from pull_request (which uses the workflow definition in the PR) to pull_request_target (uses the workflow definition in the target branch, e.g. main). Like crossing the streams in Ghostbusters, I think they are canceling each other out on this PR.
I'm hoping that when we merge this PR, subsequent PRs will …
=> Skip security scan when a PR is only doc changes

cmd/porter/mixins.go, cmd/porter/plugins.go, docs/content/cli/build.md, docs/content/cli/bundles_build.md, go.mod, go.sum, pkg/pkgmgmt/client/helpers.go, pkg/pkgmgmt/client/install.go, pkg/pkgmgmt/client/install_test.go, pkg/pkgmgmt/feed/feed.go, pkg/pkgmgmt/feed/feed_test.go, pkg/pkgmgmt/pkgmgmt.go, pkg/porter/mixins.go, pkg/porter/mixins_test.go, pkg/porter/plugins.go, pkg/porter/plugins_test.go
When the package client (used for mixins and plugins) is looking for a compatible binary to download, fallback to downloading amd64 for macos when arm64 is not available. None of the mixins or plugins build to arm64 yet, so by falling back to amd64 the command succeeds and relies on the M1 Rosetta capabilities to handle running the other format.
My new mac can't build porter. There may be follow ups from here but with this I'm able to run `mage build install` and then `cd examples/hello && porter install` successfully.
=> Fallback to amd64 on M1 when installing binaries

docs/content/quickstart/credentials.md
When running the command as originally given
```
>porter install --cred github
```
The following output results
```
Error: No bundle specified. Either an installation name, --reference, --file or --cnab-file must be specified or the current directory must contain a porter.yaml file.
```
[1]: …
=> Added reference parameter to the install command

.github/workflows/close-issues.yaml
Now that my PR was merged adding support for pull_request_target, we can stop using my fork of the aciton and use the latest upstream release.
No 🍴 
N/A
=> Use upstream close issues github action

CONTRIBUTORS.md, docs/content/contribute/tutorial.md, docs/content/install.md, docs/content/quickstart/_index.md
I recently got Porter running on my M1 mac. During my set up, I ran into a couple of problems. One being using the wrong prerelease version of Porter as well as port 5000 being blocked by Mac OS Monterey. …
=> fix edge cases in docs

CONTRIBUTORS.md, scripts/install/install-linux.sh
Install on Linux saves the binary in PORTER_HOME and is referenced by a symlink in the runtimes directory
Closes #2031
Per the discussion here: https://github.com/getporter/porter/discussions/2014
=> Linux install script uses a symlink

pkg/claims/installation.go, pkg/porter/testdata/show/expected-output.json, pkg/porter/testdata/show/expected-output.yaml, tests/testdata/installations/mybuns.yaml
Since we have merged the change to implement storing sensitive data in secret store, installation/run/output schema has changed. We need to increment the schema version with the change.
Closes #1992 
=> increment installation schema version

docs/content/bundle/manifest/_index.md
1. Add key `config` for `--param` flag for Object Parameter example.
2. Escape double dash for `--param` flag on explanation paragraph.
#2029 
=> [Docs] Add key config param flag for object parameter and escape string for double dash flag

tests/tester/main.go
Sometimes in integration test, if a mongo instance can't be successfully created, the Close() would return a nil panic.
This PR changes to only call Close when we are sure mongo is running
=> Fix nil panic in integration test

CONTRIBUTORS.md, cmd/porter/bundle.go, docs/content/cli/bundles_install.md, docs/content/cli/bundles_invoke.md, docs/content/cli/bundles_uninstall.md, docs/content/cli/bundles_upgrade.md, docs/content/cli/completion.md, docs/content/cli/install.md, docs/content/cli/invoke.md, docs/content/cli/uninstall.md, docs/content/cli/upgrade.md, tests/integration/install_test.go, tests/integration/testdata/bundles/bundle-with-string-params/helpers.sh, tests/integration/testdata/bundles/bundle-with-string-params/porter.yaml
This is a backport of #1931 to the v0.38 stable release.
=> Backport Switch from StringSlice to StringArray (#1931)

scripts/install/install-linux.sh
This reverts commit 9a1934665d8b995277be0a5a1b49c5a2987cb459.
Closes #2048
If we want to make this change, let's redo it on the release/v1 branch, and make sure to run the install script tests with it.
=> Revert "Use a symlink in a linux install"

go.mod, go.sum, pkg/claims/run_test.go
Pin to cnab-go v0.23.2 with a fix for reading output metadata from a claim result after it has been unmarshaled from json.
https://github.com/cnabio/cnab-go/pull/283
N/A
N/A
=> Bump cnab-go to v0.23.2

pkg/storage/sanitizer.go, pkg/storage/sanitizer_test.go
To improve user experience and readability, this PR adds a `-` in the key format for sensitive data
=> pkg/storage: add dash when formating sensitive data's key

pkg/config/loader.go, pkg/config/logs.go, pkg/plugins/pluggable/loader.go, pkg/portercontext/telemetry.go, pkg/tracing/traceLogger.go, tests/integration/telemetry_test.go
* The if statement was inverted so we weren't ever using the tracer.
* I was accidentally closing the tracer instead of ending the span in one spot.
Fixing a regression caused by #2026 when I applied some review feedback and got the boolean logic flipflopped. I've added an integration test to verify that the tracer is a real one.
=> Fix enabling telemetry

pkg/storage/plugins/mongodb/mongodb.go, pkg/storage/pluginstore/store.go
After running `porter installation list`, I was not able to run `mage build install` successfully due to `Error: open /home/yingrong/.porter/porter: text file busy`
I checked running processes on my machine and found that the storage plugin is still running after porter has exited.
This PR fixes the Close function on the store to match with the storage.Store interface …
=> pkg/storage: fix connection leak

pkg/porter/porter.go, pkg/porter/porter_test.go, tests/testdata/config/config-with-storage-secret.yaml
Propagate any secret resolve errors when loading porter's config file.
When a config file uses secrets, porter was ignoring the error if the secret couldn't be resolved.
=> Handle error when resolving config file secrets

cmd/porter/completion.go, cmd/porter/completion_test.go
Mark the `porter completion` command to skip loading porter's config file.
When a user is sourcing porter's completion command in their zshrc file for example, if there is bad config, this causes their entire shell to not load properly. Also the command doesn't need any configuration so loading is slow and silly.
=> Do not load config for the bash completion command

cmd/porter/plugins.go, pkg/plugins/pluggable/loader.go, pkg/plugins/pluggable/loader_test.go
This fixes the internal plugin run command to skip loading config for plugins. Plugins get their config passed to them anyway on stdin and should never try to figure out porter's config file themselves anyway.
I'm also adding a short circuit to the plugin load function to detect when we are trying to load a plugin from INSIDE another plugin. So that instead of infinite recursion, it results in an immediate error sent back to the command output.
When porter starts, the main function optionally loads the config file first, resolving any secrets in the file. When an internal plugin loads, it should not attempt to load the config file. If it tries, if there are secrets in the config file, it causes infinite recursion of the secret plugin loading, trying to resolve secrets by loading another …
=> Fix plugin load recursion

docs/config.toml, docs/content/end-users/configuration.md, docs/content/plugins/filesystem.md
=> Add documentation for Create Porter's Configuration file under Task 

docs/static/_redirects
I missed that the search page was also showing closed issues. This fixes that so only open unassigned issues are displayed.
=> Find Issues link should only show open issues

pkg/porter/explain.go, pkg/porter/explain_test.go, pkg/porter/testdata/explain/expected-table-output-no-mixins.txt, pkg/porter/testdata/explain/expected-table-output-non-porter.txt, pkg/porter/testdata/explain/params-bundle-no-mixins.json, pkg/porter/testdata/explain/params-bundle-non-porter.json, pkg/porter/testdata/explain/params-bundle.json
Explain command will not print `This bundle uses the following tools:` section for (1) non-Porter bundle (the one with no `custom.sh` section) and (2) a bundle with no mixins used.
Closes #1892 
=> Do not print "tools used" section on explain

CONTRIBUTING.md, cmd/porter/main.go, docs/content/configuration.md, pkg/config/config.go, pkg/config/helpers.go, pkg/config/logs.go, pkg/porter/helpers.go, pkg/porter/lifecycle_integration_test.go, pkg/portercontext/context.go, pkg/portercontext/telemetry.go, pkg/tracing/traceLogger.go, tests/integration/archive_test.go, tests/integration/claim_migration_test.go, tests/integration/dependencies_test.go, tests/integration/install_test.go, tests/integration/invoke_test.go, tests/integration/outputs_test.go, tests/integration/pluggable_integration_test.go, tests/integration/publish_test.go, tests/integration/rebuild_test.go, tests/integration/sensitive_data_test.go, tests/integration/suppress_output_test.go, tests/testdata/config/config.yaml
[Trace the integration and smoke tests](https://github.com/getporter/porter/pull/2058/commits/88a318fd835f211ba4123bd2f349dd468864936d)
When PORTER_TEST_TELEMETRY_ENABLED is true, trace the smoke and integration tests.
[Move tracer.Close to the RootTraceLogger](https://github.com/getporter/porter/pull/2058/commits/ffdab1d2ba394e30a152853e325a83312df8909e)
I found that it was way too easy to accidentally call span.Close (instead of span.EndSpan) which then causes the tracer to close. I've moved Close to the RootSpanLogger and Close now also ends the span. This will prevent someone from closing the tracer when they were just trying to close a span.
[Make the temelemtry start timeout configurable](https://github.com/getporter/porter/pull/2058/commits/0635add30de05c1c9d482e5c139e09b616bf8bd2) …
=> Support tracing the smoke and integration tests

pkg/storage/migrations/manager.go, pkg/storage/migrations/manager_test.go
When we tell the user to run porter storage migrate, tell them the version we found in the db and which version we expected.
The original error message just told you that you were "out-of-date" but didn't say what schema version we found in the database or what we expected to get.
N/A
=> Include the schema versions in migration errors

ADOPTERS.md, CONTRIBUTING.md, CONTRIBUTORS.md, cmd/porter/bundle.go, docs/content/cli/bundles_install.md, docs/content/cli/bundles_invoke.md, docs/content/cli/bundles_uninstall.md, docs/content/cli/bundles_upgrade.md, docs/content/cli/install.md, docs/content/cli/invoke.md, docs/content/cli/uninstall.md, docs/content/cli/upgrade.md, docs/content/compatible-registries.md, docs/content/contribute/_index.md, docs/content/contribute/tutorial.md, docs/content/install.md, docs/content/project/short-links.md, docs/content/quickstart/credentials.md, docs/static/_redirects
This merges all recent relevant changes from main back into the release/v1 branch. I didn't do a cherry-pick because it's harder to track what has been synced between the branches but in this case it was a bit messy. I've crossed out the commits that were considered for the merge but backed out because they are not relevant anymore to v1.
This brings in the following pull requests that target main:
d5488470 Merge pull request #2098 from hrittikhere/main
6a11797d Edit index.md for Typo  (#2094)
14662ec2 Merge pull request #2087 from carolynvs/open-issues-only
05ab24cd Merge pull request #2086 from carolynvs/find-issues
~6f59a6bf Merge pull request #2076 from carolynvs/pin-installed-versions~
7db0ea7d Merge pull request #2049 from carolynvs/revert-symlink
678aaf66 Merge pull request #2046 …
=> Sync from main

docs/content/plugins/hashicorp.md
I've updated the Hashicorp plugins documentation page and am instructing people to install our temporary fork until the upstream repo is compatible with Porter v1.
Closes #2035 
Preview available at https://deploy-preview-2108--porter.netlify.app/plugins/hashicorp/
=> Update hashicorp plugin page with temp fork

pkg/plugins/pluggable/loader.go
When the plugin configuration can't be marshaled to json, do not print the plugin config in the error message as it could contain sensitive data.
Closes #2084 
I couldn't figure out how to test this since really we are just handling the error from json.Marshal but there isn't really a way for bad data to get to that point in Porter. We'd error out much earlier just reading the config file.
=> Do not include plugin config in error

pkg/porter/examples/install_example_test.go, pkg/porter/list.go, pkg/porter/list_test.go, pkg/porter/show.go, pkg/porter/show_test.go, pkg/porter/testdata/show/bundle-never-run.txt
Do not retrieve the full installation definition for each installation returned from list. We only need that information
for the show command. Right now porter is making multiple calls to both the storage and secrets plugin for each installation in the list results.
Closes #2040
Here is what the trace looks like with this fix (compared to the original trace which was huge)
=> Fix performance for porter list

CONTRIBUTORS.md, pkg/context/helpers.go
This was breaking unit-tests on porter_home directories which contain uppercase chars.
This change removes an unneeded ToLower on filepath which was breaking unit-tests on porter_home directories with uppercase chars.
Closes #2111 
@carolynvs agreed to remove this.
=> Remove unneeded ToLower

pkg/cnab/cnab-to-oci/helpers.go, pkg/cnab/cnab-to-oci/provider.go, pkg/cnab/cnab-to-oci/registry.go, pkg/cnab/cnab-to-oci/registry_integration_test.go
When resolving dependencies, we need to be able to query a registry for a list of the tags associated with a bundle. This will allow us to select the highest version of a bundle that matches the version range specified by a dependency.
Part of #1939 
I am breaking up some of the changes that we know that we need to support the advanced dependencies feature into small changes that we can safely review and merge now.
N/A
=> Add registry.ListTags

pkg/config/datastore.go, pkg/config/testdata/config.toml
I found a few spots I missed when removing docker from the build-driver options.
Follow-up to #1999
We have plans for adding another build driver in the future: podman. That's why we aren't just removing the build-driver option entirely.
=> Cleanup build-driver config setting

docs/themes/porter/layouts/blog/list.html
The blog posts page was reading from a paginated set of blog entries but wasn't displaying the paginator either.
If you go to https://porter.sh/blogs you only see the most recent blog posts and there's no way to view older posts.
I'll merge this forward into release/v1 after we merge this.
Note that https://deploy-preview-2115--porter.netlify.app/blog/ shows more blog posts. https://porter.sh/blog stops at our announcement of joining the CNCF.
=> Show all blog posts on the blog page

pkg/cnab/config-adapter/adapter.go, pkg/cnab/config-adapter/adapter_test.go, pkg/cnab/config-adapter/helpers.go, pkg/cnab/config-adapter/stamp.go, pkg/cnab/config-adapter/stamp_test.go, pkg/porter/build.go, pkg/porter/cnab_test.go, pkg/porter/stamp.go
[Pass porter config to the bundle converter](https://github.com/getporter/porter/commit/10e1b8da0aef4c7058fe2e95d828c4d49f3371e1)
When we are converting a porter.yaml to a bundle.json we need the porter config file so that we can check if the upcoming dependencies2 feature flag is enabled and conditionally build out a different bundle.
[Add context.Context to the bundle adapter](https://github.com/getporter/porter/commit/a4373f3c5a9b59a15b605f99253f2f1db3a99ea4)
Stop logging directly to stdout(!) and instead log with the current span so that it is traced.
Part of #1939 
I am breaking up some of the changes that we know that we need to support the advanced dependencies feature into small changes that we can safely review and merge now.
N/A
* Comment with /azp run test-porter-release if a …
=> Refactor the bundle adapter

pkg/storage/plugins/mongodb_docker/store.go
In a few places, I must have converted from fmt.Println to log.Debugf and forgot to use placeholders. This fixes the log lines so that they print properly instead of like this:
```
using plugin
pulling%!(EXTRA string=mongo:4.0-xenial)
running a mongo server in a container on port%!(EXTRA string=27018)
waiting for the mongo service to be ready
```
Just something I noticed while running in debug mode.
N/A
=> Fix log messages from mongodb-docker

CONTRIBUTING.md, cmd/porter/main_test.go, docs/content/administrators/diagnostics.md, docs/content/configuration.md, pkg/build/buildkit/buildx.go, pkg/config/config.go, pkg/config/config_test.go, pkg/config/helpers.go, pkg/config/logs.go, pkg/config/testdata/config.toml, pkg/experimental/experimental.go, tests/testdata/config/config-with-telemetry.yaml, tests/testdata/config/config.yaml
[Remove structured-logs experimental flag](https://github.com/getporter/porter/commit/d24e8d5701205f730d225152a7979017789a5386)
We've been using structured-logs for months and it's working well at this point.
[Add NoopFeature flag for testing](https://github.com/getporter/porter/commit/1682ac9e5078873051c9be749b8d249534c242b5)
When I removed the last experimental feature flag, that caused a bunch of tests to not compile that verify that our experimental feature flags are working.
I've added a NoopFeature flag that we can use to always have at least one flag for testing. It's not used in the codebase to enable any functionality.
[Add setting for the console log format](https://github.com/getporter/porter/commit/f7638dad3576b61063d4de766624a52b090d79c5)
The structure-logs feature flag was …
=> Remove structured logs exp flag

pkg/plugins/pluggable/connection.go
When we run a plugin, we start a go routine that captures logs from the plugin and forwards them to our traceLogger. I've found that there is a race condition where:
1. We close the plugin
2. The plugin emits a message saying that its closing
3. We cancel the context for the log go routine but ctx.Done doesn't immediately trigger on the go routine.
4. Instead the plugin connections's close function returns before the routine is stopped.
5. Porter moves on and closes our logger.
6. The log go routine then tries to forward the message to the logger which is now closed.
I've added a wait group that ensures that the log go routine finishes before the plugin connection returns from Close. This ensures that all resources managed by the plugin connection are cleaned up before Close returns.
If …
=> Fix race condition in plugin logs routine

pkg/plugins/pluggable/connection.go, pkg/plugins/pluggable/loader.go
As I was adding back in net/rpc plugins (the legacy v0 plugins), I realized that our plugin timeouts don't work well for net/rpc since it is much slower than gRPC.
I've bumped both the plugin start and stop timeout defaults to make it less likely that a user will run into the timeout, while still giving us a good "oops the plugin is broken" timeout detection.
Part of #1700 
On my machine, the gRPC plugins take about 90ms to start. The net/rpc plugins take 1.4s to start.
=> Increase plugin start/stop timeouts

pkg/porter/list.go, pkg/porter/runs.go, pkg/porter/testdata/runs/expected-output.json, pkg/porter/testdata/runs/expected-output.yaml
I missed this field when I did a sweep earlier to remove the use of the word claim in the release/v1 branch. In the rest of the CLI's output we call the run's id just ID or RunID, and should be consistent with that.
I've changed DisplayID.ClaimID to ID so that we aren't exposing the term claim to our users (and it's not really the claim id anymore anyway).
Follow-up from #2053 
N/A
=> Rename DisplayRun.ClaimID to ID

cmd/porter/bundle.go, docs/content/cli/build.md, docs/content/cli/bundles_build.md, docs/content/cli/bundles_install.md, docs/content/cli/bundles_invoke.md, docs/content/cli/bundles_uninstall.md, docs/content/cli/bundles_upgrade.md, docs/content/cli/install.md, docs/content/cli/invoke.md, docs/content/cli/uninstall.md, docs/content/cli/upgrade.md, docs/content/configuration.md, go.mod, go.sum, pkg/build/buildkit/buildx.go, pkg/cnab/cnab-to-oci/registry.go
We are using the docker cli library to build images and I had thought this gave us automatic support for building against a remote docker host. It works fine for DOCKER_HOST, but turns out the TLS configuration environment variables are only parsed when the docker CLI flags are bound (which doesn't occur when we use it as a library).
I've updated how we initialize the docker cli library so that DOCKER_TLS_VERIFY and DOCKER_CERT_PATH are picked up and passed to the library.
Closes #1532
Waiting on the cnab-go PR to merge before we merge this: https://github.com/cnabio/cnab-go/pull/284
=> Support Docker TLS environment variables

Makefile
When we install packr2 before building, we are trying to download a binary for packr that matches the current arch of the dev machine. Packr doesn't publish a binary for arm64.
I've switched the installation of packr to use go install instead.
`make build` fails on an m1 mac on the main branch only. release/v1 isn't affected because we don't use packr anymore.
N/A
=> Fix build target on an arm dev machine

pkg/porter/porter_integration_test.go, pkg/porter/storage.go, tests/helpers.go
When a config file is not present in PORTER_HOME, we don't do a safe job of detecting that and then skipping trying to set permission on it. So we end up calling fixFile on an empty string, which changes the permissions on the current
working directory, removing the x bit...
I've fixed the command to check if the config file exists before trying to set it and also added more safety checks in fixFile to prevent us from changing permissions on a directory, or to a path outside of PORTER_HOME.
Closes #2143 
N/A
=> Storage fix-permissions should handle missing config

magefile.go
v0.1.16 includes fixes for using nonroot invocation images. This isn't fixing any problems and I'm just making sure that we are using the most recent release on the official feed for the helm3 mixin.
=> Update to helm3 mixin v0.1.16

go.sum, pkg/porter/archive.go, pkg/porter/archive_test.go
Currently, porter uses bundle name as part of the temporary archive folder for storing all artifacts and metadata that's needed for archiving a bundle.
The bundle name may contain invalid path characters, which causes `porter archive` to fail.
This PR fixes above issue by sanitizing bundle name to remove non-standard path characters before using it as part of the archive folder path.
If a path separator is present in a bundle name, we will replace them with a dash, `-`
Closes #2151 
=> Sanitize archive folder name

pkg/porter/archive_test.go
only assert bundle name instead of the full path since the default temporary folder path is different on different OS
=> fix archive folder test for 

CONTRIBUTORS.md, pkg/manifest/manifest.go, pkg/manifest/manifest_test.go, pkg/manifest/testdata/porter-with-badschema.yaml
Improves the error message when loading a bad schema from the porter.yaml. New behavior is:
```
➜  porter build
unsupported property set or a custom action is defined incorrectly: error unmarshaling custom action baddata: yaml: unmarshal errors:
line 1: cannot unmarshal !!bool `true` into manifest.Steps
```
Closes #2085 
=> Improve error message loading wrong schema

.github/workflows/prow-commands.yaml, .github/workflows/prow-merge-pr.yaml, OWNERS
This adds a prow github action that allows specified people (in the
OWNERS file) to comment on a pull request with /lgtm to review the pull
request, or /approve to merge the pull request.
The github action handles executing the commands for you so that you
don't need to have maintainer rights on the repository.
=> Add prow github action

pkg/porter/schema_test.go, pkg/porter/testdata/porter-with-dependencies.yaml, pkg/porter/testdata/schema.json, pkg/schema/manifest.schema.json
Signed-off-by: Steven Gettys <s.gettys@f5.com>
Update the dependency schema for v1 manifests
Extended the current schema unit test to validate a manifest that has dependencies defined in it
This is a breaking change for v1.0.0-alpha.20 and previous
=> Updated installation schema with correct dependency schema

docs/content/contribute/tutorial.md
Unit test and end-to-end test links led nowhere
Signed-off-by: Kevin Barbour <kevinbarbourd@gmail.com>
Fixes broken links in docs.
=> Fix broken links in tutorial docs

.gitignore, Makefile, docs/content/contribute/tutorial.md, docs/content/sources/CONTRIBUTING.md
Now that all new development should be against the release/v1 branch, I've updated the contributing tutorial on the main branch to instruct people to work with release/v1 and use the udpated v1 instructions.
We have been getting a number of confused contributors because they come to the contributing tutorial from the main site which is for our main branch and this should help get them the correct info to contribute.
Here is a preview of the updated contributing tutorial https://deploy-preview-2173--porter.netlify.app/contribute/tutorial/
Closes #2172 
I will open a follow-up PR to the v1 branch with some of the other tweaks I made to the contributing tutorial so that they are both up-to-date.
* Comment …
=> Use v1 contributing info on main porter site

cmd/porter/parameters.go, docs/content/cli/parameters.md, docs/content/cli/parameters_create.md, pkg/porter/parameters.go, pkg/porter/parameters_test.go, pkg/templates/templates.go, pkg/templates/templates/parameters/create/parameter-set.json, pkg/templates/templates/parameters/create/parameter-set.yaml, pkg/templates/templates_test.go
Add new command `porter parameters create` for users to have and use blank resource in creating a new parameter set.
```
$ porter parameter create
schemaType: ParameterSet
schemaVersion: 1.0.1
name: NAME
namespace: NAMESPACE
labels:
LABEL: LABEL_VALUE
parameters:
- name: parameter-path
source:
path: /path/to/parameter-path-file.txt
- name: parameter-command
source:
command: echo 'parameter command'
- name: parameter-env
source:
env: PARAMETER_ENV
- name: parameter-value
source:
value: parametervalue
- name: parameter-secret
source:
secret: parameter-secret
```
Closes #2146 
=> Add porter parameter create command

pkg/plugins/pluggable/connection.go
When connecting to a plugin and it fails to connect, log the error first, and then call close on the connection. This ensures that the order of the error(s) in our log file/traces match the order the events happened. Otherwise it's easy to confuse the error from connect with any additional errors triggered by close, when they are logged out of order.
This fixes the order of the errors being logged which should help with that.
=> Fix timing on logging a plugin connection error

pkg/storage/credential_store.go, pkg/storage/installation_store.go, pkg/storage/migrations/manager.go, pkg/storage/parameter_store.go
This updates how we create indices to not require a store, and instead define the functions directly on the package.
This is refactoring for #1700
=> Refactor functions that create indices

pkg/porter/runs_test.go, pkg/storage/installation.go, pkg/storage/installation_test.go, tests/smoke/hello_test.go
I made a mistake and never set the uninstalled flag when I added this field to installation status. It's now being set when a bundle run is applied to the installation.
=> Set the uninstalled flag on the installation

docs/themes/porter/layouts/partials/nav.html
Updates the Nav Bar to use a dynamic URL instead of static `{{ .Site.BaseURL }}`
Closes https://github.com/getporter/porter/issues/2191
=> Update Navigation Bar

docs/content/install.md
New users should install v1 since it is coming out soon. I've reordered the page so that we promote installing v1 over v0.
Part of #2179
N/A
=> Recommend installing v1

pkg/storage/plugins/mongodb_docker/store.go
Simple change to detect local docker availability and update error message.
The detection mechanism is currently just checking exit code of `docker info`. I suppose this is the most cross platform way of checking it? Open to suggestions on this.
Closes #2066 
I'm not sure I can write a test for this? Ideally, the test could stop docker on the system and test the error message, however, that will prevent parallel runs etc. Let me know your thoughts on this.
I have ofcourse tested this manually on linux/windows :)
=> Update error message when docker is not available

go.mod, pkg/pkgmgmt/client/filesystem.go, pkg/pkgmgmt/client/helpers.go, pkg/porter/build.go, pkg/porter/build_test.go
When we build a bundle, we record metadata about each mixin used in the bundle. Previously we were first retrieving metadata from every single installed mixin, and then filtering that by the mixins used.
I've changed the build command so that instead we first determine which mixins to query, and then we only ask those mixins for their metadata. This avoids problems and unhelpful error messages when installed, but unused, mixins are queried and return an error. It also just speeds up build which is nice too.
Closes #2212 
N/A
=> Only load mixin metadata from used mixins

pkg/cnab/config-adapter/adapter.go, pkg/cnab/config-adapter/adapter_test.go, pkg/cnab/config-adapter/testdata/porter-with-deps.yaml, pkg/manifest/manifest.go, pkg/porter/testdata/schema.json, pkg/schema/manifest.schema.json
When I was implementing the dependencies v2 extension (advanced dependencies proposal), I realized that we had a regression in the v1 extension recently when we updated the porter.yaml schema to move reference and version underneath the bundle field, e.g. 
```yaml
dependencies:
- name: mydep
bundle:
reference: getporter/mydep
version: 1.0.0
```
I had to make two fixes to get the original test passing properly, plus update the test since there was a problem with closures that was making it pass when it shouldn't have.
[Fix yaml tag for dependency version](https://github.com/getporter/porter/commit/5baac5168a216f998e255b30c3711e0b0e737d46)
There was a typo in the yaml tag for a dependency's version in porter.yaml. It has always been version, and we intended to just move reference and …
=> Fix dependencies v1 definition and conversion

cmd/testplugin/main.go, magefile.go, pkg/plugins/pluggable/connection.go, tests/integration/pluggable_integration_test.go
The cause of the inconsistent error message returned when connecting to a plugin was that there is a bit of a race condition in the hashicorp/go-plugin framework where messages written to the plugins stderr may not be reported by the time the plugin framework rejects a non-conformant message that the plugin wrote to stdout.
The result is that sometimes our code would get a chance to see the erorr message that the plugin wrote, and sometimes we wouldn't.
I don't want to modify the plugin framework just make one of our tests more reliable. So instead I have updated our test plugin so that it waits a bit between writing to stderr and writing to stdout. Now we reliably get both messages captured by go-plugins.
In addition, I made the error message returned by the plugin connection consistent …
=> Fix test flake TestPlugins_CatchStderr

docs/content/configuration.md, go.mod, pkg/cnab/config-adapter/adapter.go, pkg/cnab/config-adapter/adapter_test.go, pkg/experimental/experimental.go
This introduces the dependencies-v2 experimental flag, under which any changes from PEP003 - Advanced Dependencies will be implemented.
Closes #2224 
N/A
=> Add dependencies-v2 experimental flag

cmd/porter/bundle.go, pkg/config/datastore.go, pkg/porter/archive.go, pkg/porter/cnab.go, pkg/porter/cnab_test.go, pkg/porter/credentials.go, pkg/porter/delete.go, pkg/porter/dependencies.go, pkg/porter/explain.go, pkg/porter/inspect.go, pkg/porter/install.go, pkg/porter/install_test.go, pkg/porter/invoke.go, pkg/porter/lifecycle.go, pkg/porter/lifecycle_integration_test.go, pkg/porter/lifecycle_test.go, pkg/porter/logs.go, pkg/porter/options.go, pkg/porter/outputs.go, pkg/porter/outputs_test.go, pkg/porter/parameters.go, pkg/porter/reconcile.go, pkg/porter/runs.go, pkg/porter/runs_test.go, pkg/porter/show.go, pkg/porter/show_test.go, pkg/porter/uninstall.go, pkg/porter/upgrade.go
Previously we had a shared option struct, sharedOptions and BundleAction, that were used for a large grouping of commands that work with bundles, from install to explain.
I've refactored the shared options into more granular groupings so that later I can define debug mode for _just_ commands that run bundles. Now there are shared options for commands that execute bundles and commands that merely reference a bundle (such as explain).
This is refactoring that will be used in upcoming changes such as #1430 and #1429 .
N/A
=> Refactor shared bundle action options

cmd/porter/explain.go, cmd/porter/inspect.go, docs/content/archive-bundles.md, docs/content/bundle/create.md, docs/content/cli/bundles_explain.md, docs/content/cli/bundles_inspect.md, docs/content/cli/explain.md, docs/content/cli/inspect.md, docs/content/examine-bundles.md, docs/content/examples/hello.md, docs/content/inspect-bundles.md, docs/content/plugin-tutorial.md, docs/content/quickstart/_index.md, docs/content/quickstart/credentials.md, docs/content/quickstart/desired-state.md, docs/content/quickstart/parameters.md, docs/content/slides/cnab-unpacked/index.md, go.mod, pkg/porter/explain.go, pkg/porter/explain_test.go, pkg/printer/printer.go, pkg/printer/printer_test.go
Since the inspect and explain commands operate directly on a bundle, it makes sense to let the user specify it as a positional argument. I have updated both commands to accept either the existing --reference flag (for consistency with other commands and backwards compatibility) and alow support passing the reference as the first positional argument.
So either of the following now work:
porter explain REFERENCE
porter explain --reference
I've updated the docs to prefer the form without the flag, since it's shorter.
I noticed that our ExplainOptions didn't default the output format, so I updated our ParseFormat function to default an empty format to plaintext. This is mainly useful for the unit tests so that we don't need to repeat logic that normally cobra would handle for us.
Part of …
=> Allow reference as positional arg to explain/inspect 

pkg/runtime/runtime-manifest.go, pkg/runtime/runtime-manifest_test.go, pkg/runtime/runtime.go, pkg/yaml/yq.go
This switches from marshaling the current step to yaml to using the original yaml from the porter.yaml file when rendering a step template.
This avoids problems where the round trip through Unmarshal/Marshal/Unmarshal causes the quotes to not be preserved exactly as was typed into the porter.yaml. Switching to using yaml3.Node preserves the original whitespace and quotes since we are always working directly from the original yaml and not a data structure.
This is useful pre-work for #316, which will allow Porter to finally inject values as data types _other_ than strings, which makes the preservation of exactly what the user typed very important.
Closes #650 
N/A …
=> Render step template from original yaml

docs/content/storage-migrate.md
Signed-off-by: Jacob Stampe Mikkelsen <jmn@systematic.com>
Correct wrong links in storage migration docs
Wrong links
None
- [-] Did you write tests?
- [+] Did you write documentation?
- [-] Did you change porter.yaml or a storage document record? Update the corresponding schema file.
- [-] If this is your first pull request, please add your name to the bottom of our [Contributors][contributors] list. Thank you for making Porter better! 🙇‍♀️
=> Documentation fixes related to migration

.github/ISSUE_TEMPLATE/bug_report.md, cmd/porter/bundle.go, cmd/porter/bundle_test.go, docs/content/blog/docker-mixin-blog-post.md, docs/content/cli/bundles_install.md, docs/content/cli/bundles_invoke.md, docs/content/cli/bundles_uninstall.md, docs/content/cli/bundles_upgrade.md, docs/content/cli/install.md, docs/content/cli/invoke.md, docs/content/cli/uninstall.md, docs/content/cli/upgrade.md, docs/content/credentials.md, docs/content/quickstart/credentials.md, docs/content/slides/pack-your-bags-msp/index.md, docs/content/slides/pack-your-bags/index.md, pkg/porter/explain.go, workshop/aws-bucket/README.md, workshop/etcd-operator/ANSWERS.md, workshop/gcloud-compute/README.md
For all the commands that support running a bundle, install/invoke/upgrade/uninstall, I've renamed the --cred flag to
--credential-set for consistency with the other flags.
The old flag will still work but Porter will print out a message that it's deprecated.
Part of #1430 
~This relies on a couple unmerged PRs, so just ignore for now. #2245 and #2242~
=> Rename --cred to --credential-set

docs/content/docker-images/agent.md, docs/content/docker-images/client.md, docs/content/docker-images/workshop.md
A while back we switched to only publishing images to ghcr.io instead of docker.io due to changes in the Hub service (rate limits, etc). I forgot to update these pages that document the images when I did that, so this fixes the doc to point to the current image locations.
Closes #2262 
I've opened a follow-up issue to consider if it's worth supporting these images (porter, and workshop) in v1.
https://github.com/getporter/porter/issues/2265
=> Document new location of docker images

docs/content/authors/templates.md, pkg/cnab/cnab-to-oci/helpers.go, pkg/cnab/cnab-to-oci/provider.go, pkg/cnab/cnab-to-oci/registry.go, pkg/cnab/cnab-to-oci/registry_test.go, pkg/cnab/config-adapter/adapter.go, pkg/cnab/reference.go, pkg/manifest/manifest.go, pkg/manifest/manifest_test.go, pkg/porter/build.go, pkg/porter/copy_test.go, pkg/porter/generateManifest.go, pkg/porter/generateManifest_test.go, pkg/porter/stamp.go, pkg/porter/testdata/generateManifest/all-fields.yaml, pkg/porter/testdata/generateManifest/custom-input.yaml, pkg/porter/testdata/generateManifest/expected-result.yaml, pkg/porter/testdata/generateManifest/new-name.yaml, pkg/porter/testdata/generateManifest/new-version.yaml, pkg/porter/testdata/generateManifest/original.yaml, pkg/porter/testdata/porter.yaml, pkg/tracing/traceLogger.go, pkg/yaml/yq.go, pkg/yaml/yq_test.go, tests/testdata/mybun-with-img-reference/porter.yaml, tests/tester/main.go
This PR updates generated porter manifest to always have a digest for referenced images.
If a digest is not specified, porter will pull the image from the registry and update the manifest.
Closes #1357 
=> update manifest to always use digest

docs/content/install.md
The install page recommends installing a specific version (so that people can copy/paste the instructions) and this updates the version hard-coded in the docs to match the latest version.
=> Update install page with latest version

pkg/templates/templates/create/.dockerignore
Signed-off-by: Jeremy Goss <jeremy.goss@hpe.com>
The .dockerignore file put down by `porter create` still contained the old template name `Dockerfile.tmpl`. Renaming this to `template.Dockerfile` to match the new template name.
Closes # _(2275)_
As mentioned in the issue, a more thorough global find and replace will touch *many* files that still reference `Dockerfile.tmpl`. I can proceed to do this in another commit if necessary.
=> Fix template name in .dockerignore

pkg/cnab/aliases.go, pkg/cnab/config-adapter/adapter.go, pkg/cnab/config-adapter/adapter_test.go, pkg/cnab/config-adapter/testdata/mybuns.bundle.json, pkg/cnab/extended_bundle.go, pkg/cnab/extended_bundle_test.go, pkg/cnab/provider/action.go, pkg/cnab/provider/bundle.go, pkg/porter/build_integration_test.go, pkg/porter/dependencies.go, pkg/porter/examples/install_example_test.go, pkg/storage/run.go
Update cnab bundle schema version to latest cnab core version and validate the schema version before processing a bundle
Closes #1996
=> update/validate cnab bundle schema version to 1.2.0

docs/content/docs.md, docs/themes/porter/layouts/partials/docs-sidebar.html
Update our links to the old v0 site to use v0.getporter.org now that is set up in Netlify.
I decided to not make a v1 subdomain yet since we aren't even thinking of a v2 yet.
Closes #2219
=> Link to v0.getporter.org for older docs

docs/content/authors/templates.md, pkg/runtime/runtime.go, pkg/runtime/runtime_manifest.go, pkg/runtime/runtime_manifest_test.go, pkg/runtime/testdata/metadata-substitution.yaml, tests/integration/copy_test.go, tests/testdata/mydb/porter.yaml
Template variable bundle.invocationImage has been deprecated and replaced with bundle.installerImage
This PR makes this update and make sure that installer image is always referencing to the current running image instead of the original image reference created during build time
Closes #1824 
=> replace bundle.invocationImage with bundle.installerImage

docs/content/build-image.md, docs/content/bundle/custom-dockerfile.md, pkg/build/testdata/buildkit.Dockerfile, pkg/templates/templates/build/buildkit.Dockerfile, pkg/templates/templates/create/template.buildkit.Dockerfile, pkg/templates/templates_test.go
Currently, if a bundle is build on a linux/amd64 machine, it won't be able to run on a M1 machine. This PR makes it explicit in terms of what porter supports by default. 
Closes #2021 
=> pin invocation image to linux/amd64

docs/content/bundle/manifest/_index.md, docs/content/bundle/manifest/file-format/1.0.0-alpha.1.md, docs/content/bundle/manifest/file-format/_index.md, pkg/storage/run.go, pkg/storage/run_test.go, tests/integration/testdata/bundles/exec-outputs/porter.yaml, tests/testdata/mydb/porter.yaml
When a custom action that does not modify bundle resources and is stateless, its run should be recorded in the database if the action produce any outputs.
This PR implements this behavior.
Closes #1980 
=> persist run record for custom actions that produce outputs

CONTRIBUTING.md
The contributing guide currently tells people to make changes against main which is old info. Once we release v1, we'll need to update this again to stay current.
N/A
I've updated the v1 checklist so that we update mentions of the release/v1 branch in any docs like this one.
=> Update branch instructions in contributing guide

pkg/runtime/runtime_manifest.go, pkg/runtime/runtime_manifest_test.go
If the state.tgz file exists but is empty then the unpack will fail. Suggested behavior would be that in this instance the unpack just continues without trying to read in the file once it knows its empty. 
Closes #2307 
=> Added unexpected EOF error check for when state file exists but is empty

docs/content/plugins/mongodb.md
I accidentally used the wrong setting to configure the mongo plugin. It's a storage plugin, not secrets.
=> Fix typo on mongodb plugin page

build/azure-pipelines.pr-automatic.yml, build/azure-pipelines.release-template.yml
Use the Azure DevOps Cache task to cache the go module directory, and the go build directory, so that go build/test run faster. I am using a separate cache key for the native go build (which is mage build) and the cross compiled binaries (which is mage xbuildall), since they generate different artifacts in the go build directory. Once a cache artifact is persisted, it can't be updated or removed. It is keyed based on our go.sum file along with the agent OS. When we need to clear the cached artifacts, the leading version prefix should be incremented, which is used just to bust the cache.
This has brought our builds down from ~6m to ~1m per job. The smoke test on Windows is still slow, but I'll address that in another PR (or most likely updating the agent image for Windows).
=> Use caching in the CI pipeline

pkg/cnab/config-adapter/adapter.go, pkg/manifest/manifest.go, pkg/manifest/manifest_test.go, pkg/porter/dependencies.go, pkg/runtime/runtime_manifest.go, pkg/runtime/runtime_manifest_test.go
This shortens the names of some structs for dependencies in the porter.yaml manifest because I am tired of typing out long names.
Refactoring work that is for the advanced dependencies feature.
=> Simplify name of dependency structs on the manifest

CONTRIBUTORS.md, pkg/porter/archive.go, pkg/porter/archive_test.go
This sorts images before adding them to the exporter's ImageStore. This ensures consistent layouts when archiving bundles.
Without sorting each invocation of `archive` may result in different checksums for the archive.
Closes #2318
=> Sort list of images when archiving

go.mod, go.sum
Bump cnab-to-oci to fix unexpected size error. This updates cnabio/cnab-to-oci to get a fix for https://github.com/cnabio/cnab-to-oci/issues/128 which is causing "unexpected size" errors when pushing the carolynvs/whalesay image because it has duplicate image layers.
Closes #2320 
N/A
=> Fix unxpected size error when publishing bundle

build/azure-pipelines.pr-automatic.yml, build/azure-pipelines.release-template.yml
Our Windows agent is having awful performance problems because we are unable to turn off windows defender. This is causing our smoke tests to take 3-6x longer than it should on Windows, and they are failing with timeouts in most builds.
Long term we need to build out a new agent that has defender disabled. Until we have time to do that, I am disabling the windows smoke tests.
=> Disable windows smoke tests

docs/content/distribute-bundles.md, docs/content/storage-migrate.md, pkg/cnab/bundle.go, pkg/cnab/bundle_test.go, pkg/cnab/config-adapter/testdata/mybuns.bundle.json, pkg/manifest/manifest.go, pkg/manifest/manifest_test.go, pkg/porter/publish.go, pkg/porter/publish_test.go, pkg/porter/stamp.go, pkg/runtime/runtime_manifest_test.go
When we publish a bundle, we have to push the invocation image temporarily to a tag, so that we can then retrieve its repository digest. Right now the tag is the hash of the bundle reference, which is impossible for someone maintaining a registry to identify and clean up.
This changes the format of the temporary invocation image tag to:
porter-HASH
For example:
The input text for the invocation image hash is the location of the bundle:
ghcr.io/getporter/examples/porter-hello:v0.2.0
which results in a md5 hash of 3cb284ae76addb8d56b52bb7d6838351, so the resulting temporary location where we push the invocation image is:
ghcr.io/getporter/examples/porter-hello:porter-3cb284ae76addb8d56b52bb7d6838351
I have updated all our code to use the same function to generate the temporary tag, even for …
=> Make identifiable temporary bundle image tags

cmd/porter/bundle.go, cmd/porter/copy.go, docs/content/cli/bundles_copy.md, docs/content/cli/copy.md, docs/content/cli/publish.md, docs/content/configuration.md, pkg/cnab/cnab-to-oci/bundle_metadata.go, pkg/cnab/cnab-to-oci/errors.go, pkg/cnab/cnab-to-oci/errors_test.go, pkg/cnab/cnab-to-oci/helpers.go, pkg/cnab/cnab-to-oci/provider.go, pkg/cnab/cnab-to-oci/registry.go, pkg/cnab/reference.go, pkg/config/datastore.go, pkg/porter/copy.go, pkg/porter/copy_test.go, pkg/porter/publish.go, pkg/porter/publish_test.go, tests/integration/archive_test.go, tests/integration/dependencies_test.go, tests/smoke/airgap_test.go, tests/tester/helpers.go
When a bundle is pushed to a registry, check if the destination reference already exists and require that --force is specified to overwrite it.
Close #2017 
I have created https://github.com/getporter/porter/issues/2337 to track coming up with a more robust/reliable system for comparing the contents of the local bundle to the remote bundle. It would be great if we can tell if they are the same, and not just ask them to repush with --force when it already matches.
=> Force push bundles

OWNERS.md
This adds Steven Gettys and Brian DeGeeter as core maintainers for Porter.
=> Add bdegetter and sgettys as maintainers 🎉

docs/content/bundle/manifest/file-format/1.0.0-alpha.1.md, docs/content/bundle/manifest/file-format/_index.md, pkg/porter/testdata/schema.json, pkg/schema/manifest.schema.json, tests/integration/testdata/schema/schema.json
I had originally documented that schemaType was supported on porter.yaml files but then forgot to add it to the manifest data structure (since it's not actually used, it's just a planned helper field for  VS Code autocomplete in the future).
When `schemaType: Bundle` is set in porter.yaml, it causes the manifest to fail validation.
Since this isn't a showstopping problem, more of too eager documentation, I am updating the documentation for porter.yaml to clarify that schemaType isn't supported yet.
Post v1, we can fix this bug in a patch.
Doc fix for #2348. Final fix will come post v1.
N/A …
=> Clarify in docs that schemaType isn't supported on porter.yaml

pkg/porter/list_test.go, pkg/porter/reconcile_test.go, pkg/storage/installation.go, pkg/storage/installation_test.go
This changes how the bundle state is calculated in order to support scenarios where a bundle is uninstalled and then installed again. It will handle state calculations when both installed and uninstalled times are set.
Problem originally observed when migrating from v0.38 to v1 causing bundle to be in an uninstalled state
Partial fix to  #2353 
I'm still not entirely convinced this is the best approach to fix the problem. 
An alternative would be to change the behavior of `ApplyStatus` to ensure that `Installed` and `Uninstalled` timestamps cannot be set at the same time. Ie. the bundle is either installed or uninstalled - but never both.
E.g. in `storage/installation.go`:
```go
// ApplyResult updates cached status data on the installation from the
// last bundle run.
func (i …
```
=> Correct state when uninstalling and (re-)installing bundles

magefile.go
When installing porter from source, don't try to install the testmixin, that is just for our own tests. Also it doesn't have a runtime binary, just a client so install fails anyway.
=> Don't copy textmixin into PORTER_HOME

REVIEWING.md, docs/content/quickstart/_index.md
Add documentation for how to upgrade a bundle using digest.
I also added a section in the release guide to document how to handle failed release tags
Closes #1626 
=> Document how to upgrade a bundle using digest

cmd/exec/main.go, cmd/porter/main.go, pkg/cli/main_helpers.go, pkg/cnab/provider/action.go, pkg/config/config.go, pkg/config/helpers.go, pkg/exec/exec.go, pkg/runtime/context.go, pkg/runtime/context_test.go, pkg/runtime/helpers.go, tests/smoke/hello_test.go
This fixes the bundle output when a bundle is run in debug mode with --debug. It initializes RuntimeConfig.DebugMode (used by the mixins) with the value of the PORTER_DEBUG environment variable. It also configures a logger and puts it on the go context, so that when mixins use tracing.StartSpan or tracing.LoggerFromContext it gets a configured logger that understands the verbosity that was set on the Porter client side.
We are now setting PORTER_VERBOSITY on the bundle's invocation image when run so that --verbosity set on the client is also used in the bundle. When the bundle is run in debug mode (i.e. porter install --debug), we also pass PORTER_VERBOSITY=debug so that a dev can see everything that is happening.
Closes #2358 
I am copy/pasting a lot of boilerplate code from porter's …
=> Set runtime debug mode

pkg/cnab/provider/action.go, pkg/portercontext/context.go
This removes the debug lines printed before running a bundle with the fully resolved set of parameters and credentials passed to the bundle.
Closes #2361
This removes our debug printing. The runtime also has also disabled printing (happened in an earlier PR) but it doesn't use tracelogger and has warnings to not switch until we have censoring working with trace logger.
https://github.com/getporter/porter/blob/a787eef76259a292301561cff6371adfc05b6021/pkg/runtime/runtime_manifest.go#L438-L449
=> Do not print out creds/params before running the bundle

build/azure-pipelines.integration.yml, pkg/cnab/cnab-to-oci/provider.go, pkg/cnab/cnab-to-oci/registry.go, pkg/cnab/cnab-to-oci/registry_test.go, tests/integration/registry_integration_test.go
Before we publish or copy a bundle, we retrieve the destination bundle's metadata as a way to check if it already exists, and requires --force to overwrite. By default crane passes the current keychain when interacting with registries. Crane uses go-containerregistry under the hood and at the time I didn't realize that it was crane, and not go-containerregistry specifying the authentication. The go-containerregistry library authenticates as anonymous by default.
So when a bundle was published to a new location, we would get a 401 auth error because authentication was not supplied, when we expected a 404 to tell that the bundle didn't exist at the destination location. I have fixed our call to get the bundle metadata so that we pass in the keychain.
Closes #2365 
N/A
* Comment with /azp …
=> Pass docker auth when retrieving bundle metadata

go.mod, go.sum
Update github.com/ulikunitz/xz to v0.5.10 to address CVE-2020-16845 for rc2.
=> Bump github.com/ulikunitz/xz for CVE-2020-16845 (release candidate)

build/azure-pipelines.release-template.yml
The release build also runs the integraiton tests, so we need to log into docker there too. TestRegistry relies on us being logged in to test authentication.
Follow-up to #2366 , I could have caught this in the PR if I had run `/azp run test-porter-release`. Oops, let's try again!
=> Log in to docker in release build

docs/content/mixins/arm.md, docs/content/mixins/aws.md, docs/content/mixins/az.md, docs/content/mixins/docker-compose.md, docs/content/mixins/docker.md, docs/content/mixins/exec.md, docs/content/mixins/gcloud.md, docs/content/mixins/helm3.md, docs/content/mixins/kubernetes.md, docs/content/mixins/terraform.md
The porter mixins install command by default only installs stable (non-prerelease) versions. Update our mixin instructions to explicitly have the user set a version so that they get the most recent release.
=> Update installation instructions for mixins

pkg/pkgmgmt/client/runner.go, pkg/porter/plugins.go
since porter has removed the debug flag from plugins, we need to remove the reference in porter when running a plugin command
Closes #2375 
=> stop using unsupported debug flag for plugins

docs/content/credentials.md, pkg/porter/helpers.go, pkg/porter/install.go, pkg/porter/install_test.go, tests/integration/dependencies_test.go
When we run a bundle, like with porter install/upgrade, we should replace the names of any previously used parameter or credential sets with the ones specified in the most recent run. If none were specified, then reuse from the previous run.
Closes #2372 
N/A
=> Replace associated credential sets when running bundle

docs/content/install.md, docs/content/mixins/exec.md
Update the installation instructions for porter and the exec mixin to reference the most recent version of v1
=> Update install page with 1.0.0-rc.3

docs/content/install.md, docs/content/mixins/exec.md
* Default new users to installing v1.0.0
* Removing dual instructions for v0 and v1. People can use the version env var to install an old version of Porter, or follow the instructions on the v0 version of the site.
=> Update install instructions to specify v1.0.0

CONTRIBUTING.md, docs/content/bundle/manifest/file-format/1.0.0-alpha.1.md, docs/content/bundle/manifest/file-format/_index.md, docs/content/contribute/tutorial.md, docs/content/docs.md, docs/content/plugins/types/_index.md, docs/content/project/version-strategy/index.md, docs/themes/porter/layouts/index.html
* Use permalinks to our json schemas
* Remove v1 release plan
* Update contributing instructions to base branches from main
* Remove prerelease warning from docs homepage
* Update text on homepage
* Bump supported cnab version on homepage
=> Update docs post 1.0 golive

.github/dependabot.yml
By default dependabot wants to label its pull requests with a label named "dependacies". Instead what is happening since we don't have that label is that it is picking up on the first label with "dependencies" in it, which is pep003-advanced-dependencies. Oops.
I've created a dependabot 🤖 label and this updates dependabot to apply that instead.
=> Open dependabot PRs with a well-known label

docs/content/configuration.md, docs/content/plugin-tutorial.md, docs/content/plugins/azure.md, docs/content/plugins/hashicorp.md, docs/content/plugins/kubernetes.md, docs/content/plugins/mongodb-docker.md, docs/content/plugins/mongodb.md
* Document the configuration file in YAML instead of TOML
Switching our default documentation for our configuration file from TOML to YAML because our other files are by default documented in YAML as well. This will just be consistent and not require that people are familiar with multiple markup languages when reading our docs.
* Update plugin docs to use YAML instead of TOML
Previews available at:
* https://deploy-preview-2403--porter.netlify.app/configuration/
* https://deploy-preview-2403--porter.netlify.app/plugins/azure/#plugin-configuration
* https://deploy-preview-2403--porter.netlify.app/plugins/hashicorp/#plugin-configuration
* https://deploy-preview-2403--porter.netlify.app/plugins/kubernetes/#plugin-configuration
* https://deploy-preview-2403--porter.netlify.app/plugins/mongodb- …
=> Doc config in yaml

go.mod, go.sum, mage/setup/tools.go
Update to the most recent version of magefiles, mage and magex. I'm doing this manually since dependabot doesn't know to bump them all together.
N/A
=> Bump magefiles to v0.3.2

magefile.go
When we cross-compile porter or the mixins (anything really), some of Porter's common publishing code (such as the atom.xml feed generator), expects that the canary build will be in bin/canary (or bin/mixins/exec/canary).
When I migrated this part of publishing from make to mage on the release/v1 branch, I missed prepping the build for publish and never noticed because we weren't publishing canary builds of porter from the release/v1 branch. Now that we are on main again, the canary publish was failing because we had a dev directory and a versioned directory (e.g. v1.0.0-gblah) but no canary.
Fixes #2406
=> Prepare canary builds for publishing

scripts/test/test-linux-install.sh, scripts/test/test-mac-install.sh, scripts/test/test-windows-install.ps1
The macos install script check is failing because it calls porter list, which requires docker to be installed on the CI agent. If we had a plugin that didn't require docker configured instead, we could revert this and use that instead. But for now I'm only calling porter version and skipping calling porter list in the macos install check script.
The linux and windows checks will keep running porter list, which vets that our default config works.
Closes #2411
=> Fix macos install check to not use docker

magefile.go, scripts/test/test-linux-install.sh, scripts/test/test-mac-install.sh, scripts/test/test-windows-install.ps1
[Use permalink in install scripts for canary](https://github.com/getporter/porter/commit/69dbc4826e9419b364d2ae2b3309bbbd2f4c74fb)
When we upload an installation script to our github releases page for a release, the script is rewritten to include the version of porter to install. When it's a tagged release that works fine, but at the moment it's embedding the version number even when it's not a release, namely the canary build. Canary binaries are not uploaded under v1.0.0-gsomehash, and instead go into a release named "canary".
I've updated the build scripts so that when we upload the fixed install script for a canary release, the permalink "canary" is replaced in the install script instead of the git describe generated version number.
[Do not call list when installing …
=> Fix canary script

docs/content/install.md, docs/content/mixins/exec.md
Update our install page to use the most recent release (1.0.1)
=> Update install instructions to use v1.0.1

docs/content/mixins/arm.md, docs/content/mixins/aws.md, docs/content/mixins/az.md, docs/content/mixins/docker-compose.md, docs/content/mixins/docker.md, docs/content/mixins/exec.md, docs/content/mixins/gcloud.md, docs/content/mixins/helm3.md, docs/content/mixins/kubernetes.md, docs/content/mixins/terraform.md, docs/content/plugins/azure.md, docs/content/plugins/hashicorp.md, docs/content/plugins/kubernetes.md
For a while we had to explicitly set the version when installing prerelease mixins/plugins. Now that a bunch of them have 1.0.0 releases, we can remove that since porter will automatically install the most recent stable version.
A couple packages are still using release candidates, so I updated the version number in the install command to the most recent release.
Closes #2415
=> Update installation instructions for plugins/mixins

pkg/cnab/provider/credentials_test.go, pkg/porter/apply.go, pkg/porter/install_test.go, pkg/porter/invoke.go, pkg/porter/lifecycle_test.go, pkg/porter/list.go, pkg/porter/parameters_test.go, pkg/porter/reconcile_test.go, pkg/storage/installation.go, pkg/storage/installation_test.go, pkg/storage/migrations/manager_test.go
I have updated Installation to be composed of
* Instance specific fields that make testing difficult, such as the ID since tests have to make those values consistent to compare data structures easily
* Spec - all fields that a user would set on an installation
* Status - our own internal tracking of the installation status.
This makes it easier for us to test or work with just the values the user specified by having a spec that won't have auto-generated values like IDs, timestamps, etc. It also enables us to embed an installation spec in another data structure, like a workflow that runs multiple installations, without having unnecessary fields embedded like the status and id. It lets us think about just the desired state of the installation.
This is refactoring work in support of PEP003 - …
=> Split Installation into a spec and status

build/azure-pipelines.integration.yml, build/azure-pipelines.pr-automatic.yml, build/azure-pipelines.release-template.yml, go.mod, go.sum, netlify.toml
CVE-2022-41716 was reported in Go 1.19.2, so this updates to the most recently patched version of Go for our build.
This addresses https://repo1.dso.mil/dsop/opensource/getporter/porter-agent/-/issues/16 in our IronBank registry.
I saw another vulnerability reported in GitHub (but not IronBank), so I've also bumped go-restful from v2.9.5 to v2.16.0 to address https://github.com/advisories/GHSA-r48q-9g5r-8q2h
=> Compile with Go 1.19.3, update go-restful

.github/workflows/codeql.yaml, .github/workflows/trivy.yaml, magefile.go
After we upgraded from CodeQL v1 to v2, the performance of our "security scan" workflow went from 15m to over an hour, usually timing out. When CodeQL is initialized it replaces the go binary with their own custom one, and any builds done with it are included in the analysis.
I have moved everything that doesn't need to be analyzed to before initializing CodeQL, and also split out the cross-compilation required by Trivy (which scans our porter agent image) into a separate workflow. This way only the native builds for the porter client, runtime, exec mixin and agent are scanned by CodeQL.
This has brought performance back to a tolerable level, about 12m again.
=> Split codeql from trivy

CONTRIBUTING.md, tests/tester/main.go
Add test configuration that detects that a specific porter command should be run through delve so that it can be attached to and debugged while the smoke tests are running.
* PORTER_RUN_IN_DEBUGGER contains a prefix that when matched, tells the tests to run that command in delve.
* PORTER_DEBUGGER_PORT specifies the delve port to listen on, defaults to 55942.
This makes tests that use tests/tester package to run tests (which executes the porter cli directly and validates porter from the "outside").
N/A
=> Support debugging smoke tests

magefile.go
It was trying to call make, but the makefile was removed a while back. This updates the target to use the magefile target TestUnit instead.
=> Fix UpdateTestFiles target

cmd/porter/storage.go, docs/content/cli/storage_migrate.md, docs/content/storage-migrate.md
Include an explanation on the website and in the command doc on how the storage migrate command behaves. Warn people to not repeat the migration after they have used Porter v1 with the migrated database.
I realized that the migration behavior wasn't documented when I was helping a user with their migration.
N/A
=> Explain v0 to v1 migration

pkg/build/dockerfile-generator.go, pkg/build/dockerfile-generator_test.go, pkg/build/testdata/buildkit.Dockerfile, pkg/build/testdata/custom-dockerfile-expected-output.Dockerfile, pkg/build/testdata/missing-args-expected-output.Dockerfile, pkg/build/testdata/missing-mixins-token-expected-output.Dockerfile, pkg/linter/linter.go, pkg/manifest/manifest_test.go, pkg/manifest/testdata/mixin-with-config.yaml, pkg/mixin/helpers.go, pkg/mixin/query/query.go, pkg/pkgmgmt/client/helpers.go, pkg/pkgmgmt/client/runner.go, pkg/porter/build_test.go
When we are querying mixins, such as when we are asking each mixin for Dockerfile lines to include in the bundle image, we call them in go routines. Depending on how quickly they return, the order is not guaranteed and may change. I have updated our mixin query function to sort the results of querying the mixins in a consistent order, the order that they are defined in the bundle.
During build in particular, this ensures that we optimize layer caching as much as possible by always outputing the same contents of the Dockerfile when building a bundle. Previously, it could include the mixins in varying order which prevented reuse of layers from previous builds.
Fixes #2469
N/A …
=> Sort mixin output in order declared

docs/content/quickstart/credentials.md, docs/content/quickstart/desired-state.md
The quickstarts were referencing an old bundle location from Docker Hub which doesn't exist anymore. I've updated the quickstarts to reference the new location of our example bundle on ghcr.io
=> Fix credentials tutorial bundle ref in quickstarts

build/azure-pipelines.integration.yml, build/azure-pipelines.pr-automatic.yml, build/azure-pipelines.release-template.yml, netlify.toml
Updating to Go 1.19.4 because it contains security patches for two CVEs
https://go.dev/doc/devel/release#go1.19.4
1. CVE-2022-41720 and Go issue https://go.dev/issue/56694.
2. CVE-2022-41717 and Go issue https://go.dev/issue/56350.
=> Update to Go 1.19.4

docs/content/mixins/az.md
Update the documentation for the az mixin for its v1.0.0 release.
N/A
N/A
=> Sync az mixin documentation

CONTRIBUTION_LADDER.md, CONTRIBUTORS.md
Add missing "Contributing Guide" link to "Contributor Ladder".
=> Add missing "Contributing Guide" link to "Contributor Ladder"

magefile.go
Mg.Deps makes sure that the Ensure function is only called once if there'are multiple calls to lint
=> only call EnsureStaticCheck once

cmd/porter/plugins.go, docs/content/cli/plugins_install.md, docs/content/reference/file-formats.md, pkg/plugins/install.go, pkg/plugins/install_test.go, pkg/porter/plugins.go, pkg/porter/plugins_test.go, pkg/porter/testdata/plugins.json, pkg/porter/testdata/plugins.yaml, pkg/schema/plugins.json
This PR adds a new `--file` flag to the `porter plugins install` command.
This allows users to define multiple plugins in a file and install them with a single porter command.
Closes #2491
Maybe we need to define a schema for this plugins config file?
=> Install multiple plugins by passing in a file argument to porter plugins install

docs/content/blog/install-multiple-plugins.md, docs/content/reference/file-formats.md, pkg/plugins/install.go, pkg/plugins/install_test.go, pkg/porter/plugins.go, pkg/porter/plugins_test.go, pkg/porter/testdata/invalid-plugins.json, pkg/porter/testdata/plugins.json, pkg/porter/testdata/plugins.yaml, pkg/schema/plugins.schema.json, tests/smoke/hello_test.go, tests/smoke/testdata/plugins.yaml
Previously, the `SchemaType` and `SchemaVersion` are not parsed or validated. This PR adds the corresponding logic to properly process these fields
=> check for plugins file schema version and type

magefile.go
This is a hack to work around a codesigning problem on Apple Silicon where overwriting a binary that has already been executed doesn't cause the corresponding codesign entry in the OS cache to update. Mac then prevents the updated binary from running because the signature doesn't match. Removing the file first clears the cache so that we don't run into "zsh: killed ..."
I've updated the magefile so that when we run the install target, the original binaries are removed before we copy. I considered fixing this directly in shx.Copy but lots of people use that and this is a bug in just regular old cp too. So I don't want shx.Copy to do stuff that even cp doesn't.
See:
* https://stackoverflow.com/questions/67378106/mac-m1-cping-binary-over-another-results-in-crash
* …
=> Workaround apple silicon codesigning cache bug

.github/CODEOWNERS
I've updated our codeowneres file (which is responsible for automatically asking people for reviews when a PR is submitted) with our most active reviewers.
* Added Steven and Brian
* Removed Vaughn
=> Update codeowners with active reviewers 

docs/content/blog/2023-roadmap.md
This takes our roadmap from our annual sandbox review that we submitted to the TOC last year and shares our major themes for 2023 development.
=> Announce 2023 roadmap

docs/content/bundle/manifest/file-format/1.0.0.md, docs/content/bundle/manifest/file-format/1.0.1.md, docs/content/bundle/manifest/file-format/_index.md
Originally we planned to release v1.0.1 of the Porter manifest schema in Porter 1.10.0 but have since released it in v1.0.8. This updates the docs for the manifest to reflect that.
I have also created a new page for 1.0.1 of the manifest to match how the other file format pages work (with an index page and a separate page just for the current version).
Fixes a problem introduced in #2428 
N/A
=> Fix associated Porter version for 1.0.1 manifest schema

docs/static/_redirects
Update our release binary matching redirect rule on Netlify from hard-coded binary names to attempting to download whatever file name was specified. This will let people download the arm64 binaries that we are now publishing, and also our checksum files.
=> Support downloading any release artifact through Netlify

pkg/pkgmgmt/feed/generate.go, pkg/pkgmgmt/feed/generate_test.go, pkg/pkgmgmt/feed/testdata/atom-existing.xml, pkg/pkgmgmt/feed/testdata/atom.xml
Include entries for arm64 binaries in the atom feed generated by porter mixins feed generate
=> Include arm64 binaries when we publish a mixin

build/azure-pipelines.integration.yml, build/azure-pipelines.pr-automatic.yml, build/azure-pipelines.release-template.yml, netlify.toml
This addresses CVE-2023-24532, which is a problem with crypto/elliptic which is used by the hashicorp go-plugin module.
Fixes #2638
=> Build with Go 1.19.7

CONTRIBUTING.md
This is follow up to https://github.com/getporter/porter/pull/2641#discussion_r1145003973 which documents why we use require in integration/smoke tests instead of assert.
=> Document why we use require in long tests

pkg/porter/testdata/schema.json, pkg/schema/manifest.schema.json, tests/integration/testdata/schema/schema.json
* Default schemaVersion to 1.0.1. Now when someone in VS Code inserts a schemaVersion field it is defaulted to 1.0.1 for them automatically.
* Fix typo in spelling of definition
* Provide better json schema for dependency parameters, previously we only defined it as an object. I've added a description and requires the parameter keys to be strings
Just minor gaps in our current manifest schema that I found when updating the schema for PEP003
N/A
=> Updates to bundle schema v1.0.1

go.mod, go.sum
This reverts commit 7ee355f25822d76fa7eafab5642ba4b70c48b135, reversing changes made to 09297d650523f34f4283743fdf752897e9132504.
This fixes `TestArchive_StableDigest` and ensures that the tgz file generated by porter archive keeps its current contents/digest. See #2703 for more details on the problem. This PR reverts to the last working version of go-containerregistry, and long term we'll need to figure out how to deal with this breaking change.
=> Revert "Merge pull request #2653 from getporter/dependabot/go_modules/github.com/google/go-containerregistry-0.14.0"

cmd/porter/bundle.go, docs/content/cli/build.md, docs/content/cli/bundles_build.md, pkg/cnab/cnab-to-oci/helpers.go, pkg/cnab/cnab-to-oci/provider.go, pkg/cnab/cnab-to-oci/registry.go, pkg/cnab/cnab-to-oci/registry_test.go, pkg/porter/build.go, pkg/porter/generateManifest.go, pkg/porter/generateManifest_test.go, pkg/porter/stamp.go, tests/smoke/airgap_test.go
At build time, Porter needs the repository digest of each referenced image from porter.yaml. We update the referenced images in the final porter.yaml generated to .cnab/app/porter.yaml with the digest, so that the bundle is "pinned" to a specific image that can't be messed up by a force push over an existing tag for example.
I have updated how we do this so that instead of pulling the entire referenced image, we just call HEAD on the image to get its repository digest.
Previously when we pulled images during build, we always allowed insecure registries (because the underlying implementation didn't support making that configurable). Now that we are executing a HEAD request instead to get the digest, instead of pulling the image with PullImage, we can be more explicit like we are with the …
=> Do not pull referenced images during build

pkg/cnab/config-adapter/stamp.go, pkg/cnab/config-adapter/stamp_test.go, pkg/porter/lifecycle.go, pkg/porter/publish.go, pkg/porter/stamp.go, tests/integration/build_test.go, tests/smoke/airgap_test.go
This patch corrects two interrelated issues that were causing our bundle out-of-date check to not work well:
1. We weren't passing the --insecure-registry flag from publish to build when a rebuild was triggered.
2. We were incorrectly comparing the mixins from the cached bundle and the current bundle, with Go maps instead of a sorted array, so rebuilds would be triggered when nothing had changed.
I have updated the calls to EnsureBundleIsUpToDate so that it correctly passes through the --insecure-registry flag. I have also fixed the mixin comparison to use a sorted array so that it consistently generates the same manifest digest when detecting changes to the bundle.
I have also added a bunch of debug messages to the comparison of the cached and current bundle so that when it's flagged as …
=> Fix inconsistent rebuild

pkg/pkgmgmt/client/runner_integration_test.go
I have updated this test to only check for the desired string, and not attempt to match the entire debug output generated by porter, which can contain stray debug lines depending on the dev env. For example, on my machine I have telemetry enabled but when the backing otel collector is down, porter logs debug lines that it can't connect. The test is failing locally for me cause the test is requiring that ONLY that one line is printed, instead of just checking if the line was printed at all (more accurate and less fragile).
Since the test is intended to check that we are ****'ing out sensitive words, it doesn't need to be that strict.
Avoids test flakes when running integration tests on a local dev env.
N/A
* Comment with /azp run test-porter-release if a magefile or build script was …
=> Fix test to work on dev machines

docs/content/blog/docker-mixin-blog-post.md, docs/content/build-image.md, docs/content/bundle/custom-dockerfile.md, docs/content/slides/pack-your-bags-msp/index.md, docs/content/slides/pack-your-bags/index.md, pkg/build/buildkit/testdata/custom-build-arg.Dockerfile, pkg/build/buildkit/testdata/template.Dockerfile, pkg/build/testdata/buildkit.Dockerfile, pkg/templates/templates/build/buildkit.Dockerfile, pkg/templates/templates/create/template.buildkit.Dockerfile, tests/integration/testdata/bundles/exec-outputs/Dockerfile.tmpl, tests/integration/testdata/bundles/outputs-example/Dockerfile, tests/testdata/mybuns/Dockerfile.tmpl, workshop/asciiart/Dockerfile.tmpl, workshop/asciiart/README.md
Use stable instead of a specific debian release, so that when the release is archived, we don't end up with an unbuildable bundle. If a user wants to pin to a base image, they should use a custom Dockerfile. Porter should default to a release (stable) that will always work, so that porter doesn't need to be recompiled or a new version installed because a debian release was archived.
Fixes #2744
N/A
=> Do not pin invocation image to a specific debian release

OWNERS.md
Moving to the Emeritus Maintainers section of OWNERS.md as I'm no longer an active maintainer of this project.  ❤️ 
Ref https://github.com/getporter/porter/pull/2728
=> docs(OWNERS.md): Move vdice to the Emeritus section

build/azure-pipelines.release-template.yml
When I updated all our builds to Go 1.19.8, I missed the most important file, the one for our release build. 🤦‍♀️
=> Use Go 1.19.8 for the release build

CONTRIBUTORS.md, docs/content/cli/explain.md, pkg/porter/explain.go, pkg/porter/testdata/explain/expected-json-output.json, pkg/porter/testdata/explain/expected-yaml-output.yaml, pkg/porter/testdata/explain/params-bundle.json
Adds the user-defined [custom](https://getporter.org/bundle/manifest/#custom) section data to the output of `porter explain` command when the output format is JSON or YAML:
- Implements the feature
- Updates unit tests
- Updates documentation
Closes #2764 
=> Porter explain command displays custom section data when output is JSON or YAML

pkg/porter/parameters.go
Fix for Bug https://github.com/getporter/porter/issues/2785 porter param list doesn't display params
Wrong line "cr, ok := v.(DisplayCredentialSet)" was changed to "cr, ok := v.(DisplayParameterSet)"
Closes # bug #2785 
=> fix printParamRow

pkg/cache/cache_test.go, pkg/cnab/config-adapter/adapter.go, pkg/cnab/config-adapter/adapter_test.go, pkg/cnab/dependencies/v1/solver_test.go, pkg/cnab/extensions_test.go, pkg/porter/list_test.go, pkg/porter/parameters_test.go
Using gov1.20.5, performing `go vet ./...` and `staticcheck ./...` produces a number of errors that need to be fixed. This PR fixes them and adjusts the test to not only run the last value in the iteration of tests but maximizes the `t.Parallel()` with `go test -v -race ./...`
**go vet:**
```bash
pkg/cnab/extensions_test.go:84:38: loop variable supported captured by func literal
pkg/cnab/extensions_test.go:86:21: loop variable supported captured by func literal
pkg/cnab/extensions_test.go:92:38: loop variable supported captured by func literal
pkg/cnab/extensions_test.go:94:21: loop variable supported captured by func literal
pkg/cache/cache_test.go:174:10: loop variable tc captured by func literal
pkg/cache/cache_test.go:232:10: loop variable tc captured by func literal …
```
=> Go vet and staticcheck with gov1.20.5

cmd/porter/installations.go, docs/content/cli/explain.md, docs/content/cli/install.md, docs/content/cli/installations_install.md, docs/content/cli/installations_list.md, docs/content/cli/installations_runs_list.md, docs/content/cli/list.md
Changes the help text to properly describe how to use the `porter installation run list`
```zsh
List runs of an Installation
Usage:
porter installations runs list [flags]
Examples:
porter installations runs list [NAME] [--namespace NAMESPACE] [--output FORMAT]
porter installations runs list myapp --namespace dev
Flags:
-h, --help               help for list
-n, --namespace string   Namespace in which the installation is defined. Defaults to the global namespace.
-o, --output string      Specify an output format.  Allowed values: plaintext, json, yaml (default "plaintext")
Global Flags:
--experimental strings   Comma separated list of experimental features to enable. See https://getporter.org/configuration/#experimental-feature-flags for available feature flags.
--verbosity string …
```
=> Update help text to perform as expected

docs/content/install.md
Changes installation documentation to display v1.0.14 instead of v1.0.1
Closes #2776 
=> updating installation doc to display v1.0.14 instead of v1.0.1

docs/content/quickstart/desired-state.md
:flags: 
It fixes the broken link on Porter Documentation website in the **Quickstart: Desired State** page. At the bottom of page and under **Next Steps**, On clicking [click a bundle](https://getporter.org/bundle/create/), it is leading us to some error 404 page while the correct link is [Create a Bundle](https://getporter.org/development/create-a-bundle/) . A new user trying/learning porter won't have to run around to find the correct link to the relevant page
Please review my PR and suggest any possible change if necessary :smile: 
=> Fixed Broken link 'Create a Bundle'

docs/content/quickstart/desired-state.md
This PR fixes the 'Understand the difference between imperative commands and desired state' broken link on Porter docs https://getporter.org/end-users/installations/ leading to error 404 page but the the target page is https://porter.sh/operations/manage-installations/
Closes #2820 
Please review my PR and suggest any changes if any :smile: 
=> docs: Fixes the broken link on Porter docs

CONTRIBUTORS.md, mage/setup/tools.go
Fixes a 404 during mage build on windows
Closes #2840 
Could also use an if statement and just set the extension to be .exe if os is windows (instead of using ArchiveDownloader)
=> Added .exe extension for buf download to prevent 404

CONTRIBUTING.md
Adds a name to the installed bundle so it doesn't show up as empty, see issue below
Closes #2849
None
=> Added bundle name to jaeger command

docs/content/operations/manage-installations.md, docs/themes/porter/assets/sass/styles.scss
Clarifies what STATE and STATUS fields are in `porter list`.
Closes #2357 
Feedback appreciated
=> added clarification for STATE and STATUS

pkg/generator/generator.go, pkg/generator/generator_test.go, pkg/porter/credentials.go
Checks credentialset to see if the filepath list user's home directory with `~/`
Closes https://github.com/getporter/porter/issues/1131
Before: 
```python
porter credentials list porter-hello -oyaml
- schemaType: CredentialSet
schemaVersion: 1.0.1
namespace: ""
name: porter-hello
credentials:
- name: kubeconfig
source:
path: ~/.kube/config
- name: username
source:
env: FAKE_USER
status:
created: 2023-08-14T10:03:43.959668445-04:00
modified: 2023-08-14T10:03:43.959668445-04:00
```
After:
```
porter credentials list porter-hello -oyaml
- schemaType: CredentialSet
schemaVersion: 1.0.1
namespace: ""
name: porter-hello
credentials:
- name: kubeconfig
source:
path: /home/troy0820/.kube/config
- name: username
source:
env: FAKE_USER
status:
created: 2023-08-14T10:04:55.919030332-04:00
modified: …
```
=> Checks to see if credentialset uses `~/` as user's home directory 

cmd/porter/main.go
Fixes the improper nesting of traces which looks like caused by passing of the same context which is returned after logging the config traces, making the following traces as child traces of config trace.
Closes #2563 
I have tested the tracing which is mentioned in the issue is properly nested now.
=> fixing the nesting of tracing

pkg/porter/lifecycle.go, pkg/porter/lifecycle_integration_test.go, pkg/porter/lifecycle_test.go
`porter explain -r getporter/hello-llama:0.1.1` now prepends a `v` to the version (0.1.1), so that it will find the bundle if it is tagged v1.2.3 in the registry.
Closes #2886 
=> add v prefix

pkg/porter/create.go
Adds back a logging statement which was removed by accident in #2892.
=> revert removal of logging for `porter create`

CONTRIBUTORS.md, cmd/porter/installations.go, pkg/porter/list.go, pkg/porter/list_test.go
Filter output of **porter installation list** based on any field/combination of fields using the **--field-selector**". Supports '=' ,e.g. **--field-selector bundle.version=0.2.0,status.action=install**. All fields from the json output are supported.
Output below
```bash
$ porter installation list                                                                                                                        
--------------------------------------------------------------------------------
NAMESPACE  NAME                    VERSION  STATE      STATUS     MODIFIED    
--------------------------------------------------------------------------------
differentporterinstall  0.2.0    installed  succeeded  2023-08-24  
porter-hello            0.2.0    installed  succeeded  2023-08-21
$ …
```
=> Add field-selector argument to installations list

cmd/porter/main.go, pkg/config/logs.go, tests/integration/telemetry_test.go
Seeing what is flaky and what isn't rn
=> (bug): Flake in TestTelemetrySetup

CONTRIBUTING.md, CONTRIBUTORS.md
Hello there, I notice this issue https://github.com/getporter/porter/issues/2907. And indeed if you go to Porter contribute page https://getporter.org/contribute/ you will see those links leading to a 404 on GitHub.
This addresses that.
Closes https://github.com/getporter/porter/issues/2907.
Let me know if I missed something as this is my first PR.
=> docs: Fix broken links on CONTRIBUTING.md

pkg/porter/lifecycle.go, pkg/porter/lifecycle_test.go
=> Fix bug where unwanted v is prepended to tag name

pkg/agent/agent.go, pkg/agent/agent_test.go, pkg/porter/archive.go, pkg/porter/archive_test.go, pkg/porter/helpers.go, pkg/porter/porter_integration_test.go, tests/integration/archive_test.go
Fixes integration tests so they pass on windows . Also fixes a bug where `porter archive` fails on windows due to not being able to create a temp directory, because it tried to create 2 nesting levels at once.
One windows bug remains which is tracked separately, see #2917 
Closes #2908 
Please review agent.go. I have removed printing out the filecontents, because on windows there is no way to determine if a file is executable or not. I would like confirmation that this is ok (or not).
* Comment with /azp run test-porter-release if …
=> Fix integration tests on windows

CONTRIBUTORS.md, docs/go.mod, docs/go.sum, docs/hugo.toml, docs/layouts/index.html
Bumping the version of the docs theme version, and fixes small styling issues, including the order of the blog posts.
Bumping the version of the theme which fixes several issues including the order of the blog posts
<details>
<summary>Details</summary>
</details>
=> docs: bump hextra to v0.4.0

docs/static/_redirects
Fixes google 404 
Closes #2932 
Haven't tested locally since this is the netlify _redirects file. 
=> fix 404 from google

.github/workflows/check-licenses.yaml, CONTRIBUTORS.md
Use github.com/google/go-licenses in GitHub Actions to check the licenses of dependencies.
Closes #2942.
https://github.com/kallydev/porter/actions/runs/6518629371
If we need to ignore more packages, we can use the `--ignore` multiple times.
```bash
go-licenses check ./... \
--ignore github.com/xi2/xz,golang.org/x/sys/unix # https://github.com/xi2/xz/blob/master/LICENSE \
--ignore github.com/xi2/xz,golang.org/x/sys/unix # https://github.com/xi2/xz/blob/master/LICENSE
```
=> Check the licenses of dependencies

CONTRIBUTORS.md, pkg/build/buildkit/buildx.go
Use docker to look up current context vs hardcoding to "default"
Closes #2901 
=> Use docker to look up current context vs hardcoding to "default"

.github/workflows/build_azure_pipelinesrelease_template.yml, .github/workflows/porter-canary.yml, .github/workflows/porter-install-check.yml, .github/workflows/porter-integration.yml, .github/workflows/porter-release.yml, .github/workflows/test-porter-release.yml, .github/workflows/testporterbot.porter-release.yml
This should move the rest of the getporter/porter pipelines
=> (chore) Migrate from ADO -> GHA 

.github/workflows/build_pipelinesrelease_template.yml, .github/workflows/integ-reuseable-workflow.yml, .github/workflows/porter-integration-pr.yml, .github/workflows/porter-integration-release.yml, .github/workflows/porter-integration.yml
Right now canary is failing because
1) this `s`
2) exit 125 from docker, which needs to be updated in the magefile repo if it's not a flake
=> chore: remove typo S from "copy_test"

CONTRIBUTORS.md, cmd/porter/bundle_test.go, pkg/porter/build.go, pkg/porter/build_test.go
Provides are more user-friendly error message when running `porter build` from a directory not containing `porter.yaml`.
Previously the error message looked like this:
```
$ porter build
unable to read manifest file : could not read the manifest at "": read ~/unclear-message: is a directory
unable to generate manifest: unable to read manifest file : could not read the manifest at "": read ~/unclear-message: is a directory
```
With this change it looks like this:
```
$ porter build
could not find porter.yaml in the current directory ~/unclear-message, make sure you are in the right directory or specify the porter manifest with --file
```
Closes #2926 and closes #2991 …
=> Build missing yaml message

pkg/porter/build.go, pkg/porter/lifecycle.go, pkg/porter/list.go, pkg/porter/publish.go, pkg/porter/reconcile.go
=> fixed typo in comments

CONTRIBUTORS.md, pkg/linter/linter.go, pkg/linter/linter_test.go
When porter generates a lint message directly, instead of the message coming from a mixin, we should change the message so that it doesn't print out extra "empty" text about mixins that isn't relevant.
Closes #2526
There is a stale PR, #2530, for the same issue.
=> Lint messages reported from porter should not mention mixins

go.mod, go.sum
Reverts getporter/porter#3011
I thought tests were green but that was a lie
=> Revert "Bump github.com/docker/docker from 24.0.5-0.20230714235725-36e9e796c6fc+incompatible to 26.0.0-rc2+incompatible"

pkg/porter/parameters.go, pkg/porter/parameters_test.go
Remove parameter from installation if parameter is removed from bundle.
Otherwise it is not possible to upgrade to a version of bundle where parameters are removed since the last installation.
Closes #2929
=> Remove parameter from installation if parameter is removed from bundle

docs/content/docs/getting-started/install-porter.md
Fixes headers in the getting started - install page to render TOC correctly. 
=> docs: fix headers in getting started install guide

CONTRIBUTORS.md, magefile.go
It allows for installing porter on a fresh system from source code
Closes #3032
I manually tested changing the permissions on `~/.porter/porter` to ensure it threw an error it the binary existed but couldn't be removed, however I do not have access to an apple mac to confirm the original issue it was attempting to fix is still OK.
=> Fixed the expectation that porter would already be installed

pkg/manifest/manifest.go, pkg/manifest/manifest_test.go
Validate the upgrade action during `porter build`, otherwise it will only the validated when `porter upgrade` is executed. All other actions `install`, `uninstall` and custom actions are validated on `porter build` already.
Closes #3030 
The test introduced is using some pointers in order to make it more generic, making it a little harder to understand. I'm not 100% convinced myself it is a good idea, please let me know what you think.
=> Validate upgrade action on build

.gitignore, magefile.go
Adds code coverage output to Unit & Integration test commands
Closes #372
The issue mentions that someone else will need to enable the code coverage tool on the pipeline.
=> Add coverage profile to test commands

.github/workflows/build_pipelinesrelease_template.yml
Our release pipeline isn't triggering on success because it doesn't know what success is?
[Trying what is in this blog here](https://medium.com/@sohail.ra5/github-actions-passing-boolean-input-variables-to-reusable-workflow-call-42d39bf7342e)
=> (bug): GHA does not use bools how you think

GOVERNANCE.md
Let's try to aim for releases every three months, and triaging issues within five days. 
I would love to get some automation around getting pinged for issues that need talked at, or autolabeling.
:)
=> (chore) Update GOVERNANCE.md for release process & triage time

docs/content/docs/faq/_index.md
Updates the ToC on the [FAQ page](https://porter.sh/docs/faq/)
Closes #3053 
An alternative solution could be to removed the ToC on the page in favor for using the one on the right provided by the theme. Please let me know what you think about that solution. The change in this PR mimics what is done on other pages, but there are pros and cons for both approaches.
=> Update FAQ ToC

CONTRIBUTING.md
The Contributing Guide is taken directly from CONTRIBUTING.md, while the formatting plays nice in the Github view, it breaks the ToC on the website. This changes changes the headings to make it work in both Github and on the website.
Closes #3062
=> Make the Contributing Guide play nice with website

pkg/manifest/manifest.go, pkg/manifest/manifest_test.go
Instead of giving a cryptic error message, "more than one mixin specified", better describe the most likely cause of the problem, making it easier for people to understand what to fix.
Closes #370
=> Improve error message on malformed step

tests/integration/build_test.go
No matter what I try I cannot get this test to fail anymore. Tried to increase the iterations to 100 without getting any failures, not in Github Actions or locally.
Based on that, the test is reenabled, and then it should be monitored if the build becomes unstable again.
Closes #2948
=> Reenable bundle reuse test

.github/workflows/porter-canary.yml, .github/workflows/porter-integration-release.yml
Fixes the porter-canary action so it can run when changes are pushed to `main` or `release/*` branches.
Also removes the workflow_dispatch trigger, but that is up for discussion as it also removes the functionality to manually trigger the action if needed.
And for readability names is added to the integration test steps.
Closes #3073
It is hard to test if it works a 100% as I cannot run or trigger the action in the porter repository to see the full flow, and check if everything is pushed as it should be.
As mentioned the removal of the workflow_dispatch trigger is up for discussion, as it removes the ability to manually run the action if needed. But if we want it to stay, then conditions on the jobs on job needs to be introduced, as inputs can only be passed on when through …
=> Publish canary builds

.github/workflows/build_pipelinesrelease_template.yml
Perform full checkout of repository during release
Otherwise `git describe --tags` won't work correctly, because of the missing history, causing the canary build to not be published.
Closes #3087
=> Perform full checkout of repository during release

cmd/porter/bundle.go, pkg/porter/archive.go, pkg/porter/archive_test.go, tests/integration/archive_test.go
This adds an extra command line flag for the `archive` command that allows configuring the level of compression to use when creating the gzipped tar archive.
```bash
$ porter archive whalegap.tgz --reference ghcr.io/getporter/examples/whalegap:v0.2.0 --compression NoCompression
```
If the flag is omitted the gzipped tar archive will be compressed with `DefaultCompression` - this is equivalent to the pre-configurable-compression behavior of Porter.
Possible values for the  `--compression` flag is listed in the help text.
```bash
$ porter archive -h
[snipped]
Flags:
-c, --compression string   Compression level to use when creating the gzipped tar archive. Allowed values are: BestCompression, BestSpeed, DefaultCompression, HuffmanOnly, NoCompression (default "DefaultCompression")
``` …
=> Support configuring the compression level when archiving bundles

pkg/cnab/extended_bundle.go
If a bundle is referenced explicitly using a tag or a digest, we should not try to use the default tag.
Fixes the failing integration test for dep v2 https://github.com/getporter/porter/actions/runs/9136153884/job/25124605136
=> Don't determine default tag if bundle is referenced using digest

pkg/generator/credentials.go, pkg/generator/generator.go, pkg/generator/generator_test.go, pkg/generator/parameters.go
Optionally displays the description for parameters and credentials in the survey prompt (if present)
The following screengrab was generated with this credential set:
```yaml
credentials:
- name: kubeconfig
path: /home/nonroot/.kube/config
description: The path to your kubeconfig (usually something like /home/nonroot/.kube/config)
- name: username
env: USERNAME
```
Closes #3076 
Whilst rebasing the branch I managed to close the original PR somehow (https://github.com/getporter/porter/pull/3112) which is pretty impressively wrong. Apologies. I think I must have pushed up without any commits, and that led to this!
=> Added the description to the credentials generate output

docs/hugo.toml
A missing trailing slash causes a extra redirect to the page with a trailing slash. It also fixes some for the errors reported by the link checker in #3027.
=> Add trailing slash to items in the website menu

.github/workflows/porter-integration-pr.yml
Run integration tests on PR
The number of check actions on a PR increases a lot, but I think that is okay compared to the value it provides
=> Run integration tests on PR

.github/workflows/build_pipelinesrelease_template.yml
Otherwise the Git version calculated will not match the one used later when publishing the binaries.
Hopefully handles #3073
It is really hard to test without merging, because it is using different code flows depending on the branch name
=> Checkout history when cross compiling in the canary workflow

.github/workflows/porter-integration-pr.yml, .github/workflows/porter-integration-release.yml, tests/integration/signing_test.go
In order parallelize integration tests, the Github workflow doesn't use Mage to run all integration tests directly. Instead each integration test file is run in different jobs, requiring new integration test files to be manually added to the workflow.
The integration test for signing images was missing and is added in this PR.
For some reason running the Notation and Cosign test in parallel fails on in the Github workflow, so parallelization of those two tests are also disabled.
Related to #2902 
=> Run signing integration test

.github/workflows/build_pipelinesrelease_template.yml
GITHUB_TOKEN only have access to the current repository, when publishing mixins we need permission to create commits in the packages repo.
Related to #3073 
Because the secret is only available to workflows, and requires a canary release or tagged release to be triggered, it has not been tested if the secret is still valid. Worst case it will fail just as much as it did before.
=> Use PUBLISH_TOKEN for publishing mixins

.github/workflows/porter-canary.yml, .github/workflows/porter-release.yml
Secrets are not passed to reusable workflows by default, it has to be enabled. See https://docs.github.com/en/actions/using-workflows/reusing-workflows#passing-inputs-and-secrets-to-a-reusable-workflow for more information
Related to #3073 
=> Pass secrets to release workflow

docs/content/docs/quickstart/_index.md
Fixes a typo in one of the [Quickstart][1] commands. When following Quickstart for the first time, I received an error in the _[Upgrade the Installation][2]_ section:
```
$ porter upgrade
no bundle specified. Either an installation name, --reference, --file or --cnab-file must be specified or the current directory must contain a porter.yaml file
```
I believe the intention was for this command to include an installation name. It _does_ succeed when running `porter upgrade porter-hello` so I've updated the command in the doc.
[1]: https://porter.sh/docs/quickstart/
[2]: https://porter.sh/docs/quickstart/#upgrade-the-installation
_["It's OK to submit a PR directly for problems such as misspellings or other things where the motivation/problem is unambiguous."][1]_
[1]: …
=> Add installation name to `porter upgrade` command in Quickstart

docs/content/docs/integrations/aks.md
Add documentation concerning AKS integration.
Closes #3173
=> Add doc for AKS integration

.github/workflows/build_pipelinesrelease_template.yml, .github/workflows/porter.yml
Update the upload-artifact version so the build no longer fails
=> fix: Update version of upload-artifact

.github/workflows/porter-integration-pr.yml, pkg/porter/upgrade.go, tests/integration/testdata/bundles/bundle-with-failing-install/helpers.sh, tests/integration/testdata/bundles/bundle-with-failing-install/porter.yaml, tests/integration/upgrade_test.go
Upgrade should only be allowed when a bundle has been successfully installed.
Upgrading an failed installation or even an uninstalled installation can caused unexpected behavior since installation never was completed.
Closes #2355
=> Upgrade should not be allowed if installation is not installed

pkg/linter/linter.go, pkg/linter/linter_test.go, pkg/manifest/manifest.go, pkg/manifest/manifest_test.go, pkg/manifest/testdata/mixin-with-empty-version.yaml, pkg/manifest/testdata/mixin-with-invalid-version.yaml, pkg/manifest/testdata/mixin-with-versions.yaml, pkg/mixin/helpers.go
Added a check on version numbers if specified in your porter YAML
Delivers towards #3136 
@kichristensen - this is just a draft to make sure I'd got the right idea, before adding the checks into the linting side. I was fairly sure I'd understood, but thought it was worth double checking as it's been a little while :)
=> Support for version number validation against mixins

CONTRIBUTORS.md, pkg/runtime/runtime_manifest.go, pkg/runtime/runtime_manifest_test.go
This change makes it possible to access a parameter in templating, not only to the top-level, i.e. the parameter itself, but also -- if the parameter is of type "object" -- to access properties of the object value. For example:
```yaml
parameters:
- name: foo
type: object
default:
a: 1
b: 2
install:
mymixin:
some_property: ${ bundle.parameters.foo.a }
```
In this case, the `.a` was not possible before as `foo` was merely a JSON string at the point of template resolution.
Closes #1508 (partly?)
This does not solve the same issue for credentials. I'm not sure if that scenario is as common as with parameters though.
I wasn't sure how to handle `sensitive` along with a parameter of type object. Right now it's required for the type to be `string` is `sensitive` is to work. What would be a good …
=> Treat object parameters as objects in templating

.github/workflows/porter-integration-pr.yml, .github/workflows/porter-integration-release.yml, pkg/plugins/pluggable/connection.go, tests/integration/plugin_log_level_test.go
Fixes in bug in the implementation from #3185, that causes plugins to not fully respect the verbosity level.
Related to #3189
=> Plugins should respect verbosity

CONTRIBUTORS.md, pkg/storage/installation.go
=> Remove Status from InstallationSpec (closes #3232)

docs/content/docs/references/examples/airgap.md
Adds an additional example of how to wire bundled images with exec mixin.
It was not obvious how to wire images into a exec mixin and the only example in the documentation was for helm.
In the process of learning how to wire bundled images I found a bug (#3237).  There is a workaround to this bug which I didn't include in the documentation, but it might be useful to include it. Here is the workaround.
```yaml
envs:
IMAGE_whalesayd: <bundle repository>/my-bundle@${ bundle.images.whalesayd.digest }
```
This references the whalesayd image that is actually bundled in my-bundle. In all my testing, `bundle.images.whalesayd.repository` is actaully just referencing the …
=> Exec image wiring

docs/.htmltest.yml
Do not validate porter.sh/find-issue during link checking, as it causes a lot of 429s during scan
=> Do not validate porter.sh/find-issue

pkg/porter/parameters.go, tests/integration/upgrade_test.go
This fixes a regression bug, where the `--debug` carries over to other invocations of the `porter upgrade` command.
Closes #3240 
=> Debug flag should apply to single invocation only

.github/workflows/porter-canary.yml, .github/workflows/porter-release.yml
Since Git tags and GitHub releases are created automatically, concurrent releases are not supported. This PR ensures that canary releases and stable releases do not run simultaneously. If another release is triggered during an ongoing release, it will wait for the current release to complete.
=> Ensure concurrency control for canary and release workflows

pkg/porter/lifecycle.go
When getting a bundle through a reference, e.g. `porter explain --reference...`, and the version of the bundle does not contain a `v`, write warning on missing `v` to stderr. Writing it to stdout can cause structured results, such as when using `--format json` to become invalid.
Closes #3262
=> Write warning on missing version `v` to stderr

pkg/runtime/runtime_manifest_test.go
Stabilize the flaky TestResolveSensitiveParameters test
=> Stabilize the flaky TestResolveSensitiveParameters test

pkg/porter/outputs.go
If the output is a binary format, then newlines can mess that up if directly using the value of the output.
Use `Fprint` instead of the previous `Fprintln` when printing output value using `porter installation output show ...`.
Closes #3274
=> Don't write new line when printing outputs

cmd/porter/bundle.go, docs/content/docs/references/cli/build.md, docs/content/docs/references/cli/bundles_build.md, pkg/build/build.go, pkg/build/buildkit/buildx.go, pkg/build/buildkit/buildx_test.go
Add new `--build-context` parameter to porter, and pass through the value to `docker build`.
https://github.com/docker/buildx/blob/master/docs/reference/buildx_build.md#build-context
Closes #3271
=> Support docker build --build-context parameter

go.mod, go.sum
Upgraded to use the new release of magex to remove archiver.
Closes #3282
It's currently in draft as it's pointing to a commit instead of a release. I'm not sure how to get a release cut of magefiles?
=> Upgraded magex to remove archiver

tests/integration/signing_test.go
For some unknown reason sometimes the copied bundle is already present in the registry. It is safe to overwrite it, as the signature is unique to the bundle, at the test will fail it is not the correct image.
=> Stabilize the TestNotationCopyBundle test

docs/.htmltest.yml
To avoid the workflow failing on incomplete SSL chains, as it is out of our control.
Closes #3310 
=> Do not validate SSL certificate chains in HTMLTest

CONTRIBUTORS.md, pkg/porter/list.go, pkg/porter/list_test.go
Return an empty slice instead of a `nil` slice if there are no matching installations, so that the json marshaler returns `[]` instead of `null`.
Closes #3338
=> Return empty slice from ListInstallations

pkg/cnab/oci_reference.go, pkg/cnab/oci_reference_test.go, pkg/manifest/manifest.go, pkg/porter/lifecycle.go, pkg/porter/lifecycle_test.go
#2890 added implicit `v` prefixes to all image tags if they were missing, #2915 adds a few exceptions and this MR changes the behavior to only prefix actual semver tags with `v`, so that custom tags are not altered. Tags `1.2.3` and `1.2.3-pre_build` will be converted to `v1.2.3` and `v1.2.3-pre_build` respectively, whereas `latest`, `v1.2.3` or `my-branch-build` will not be altered.
Interally support for buildmetadata has also been added to `OCIReference` and it has been made responsible for version<->tag mapping where applicable. Tests related to `ensureVPrefix` have also been simplified.
Closely related to #2914, also touches on the implementation of #1431.
=> Only add `v` prefix to semver tags

pkg/cnab/provider/action.go, pkg/porter/dependencies.go, pkg/porter/lifecycle.go, pkg/porter/lifecycle_test.go
Remove unused parameters from `ActionArguments` struct.
related to #2699
=> Remove unused parameters from ActionArguments struct

pkg/porter/packages_test.go, pkg/porter/testdata/packages/search-multi-match.txt
Update package search test to reflect mixin name change from 'ku' to 'docker' and modify expected output in search-multi-match.txt.
This is needed after the kustomize mixin have been removed from the feed
=> Fix failing unit tests after kustomize mixin have been removed from the feed

pkg/porter/parameters.go, tests/integration/install_test.go, tests/integration/testdata/bundles/bundle-with-file-params/porter.yaml
Remove parameter resolution short-cut in `loadParameterSets` so that the name (or value) of file parameters are resolved in the same way as other parameters, unless the parameter strategy is `path`. Later, in `finalizeParameters`, 
getUnconvertedValueFromRaw` will perform special handling to either load the file or pass the data along assuming it is base64 encoded. 
This makes porter first resolve the parameter value as usual for all parameter types except `path`, then check whether the resolved value is a file path instead of assuming the value is a path (essentially ignoring the parameter resolution strategy).
Closes #3349 
=> Fix resolution of file parameters

pkg/storage/plugins/mongodb_docker/store.go
- Moved the definition of the MongoDB image variable to the top of the function for clarity.
- Added an error message to prompt users to upgrade their MongoDB data format if the current version does not match the required image version.
This change enhances the user experience by providing clear instructions for necessary upgrades.
This logic won't catch the situation where the MongoDB container cannot start
=> Improve MongoDB image version check in EnsureMongoIsRunning

cmd/porter/bundle.go, docs/content/docs/references/cli/build.md, docs/content/docs/references/cli/bundles_build.md, pkg/build/build.go, pkg/build/buildkit/buildx.go, pkg/build/buildkit/buildx_test.go, tests/integration/build_test.go
This change introduces a number of new build flags, `--cache-to`, `--cache-from`, `--builder` and `--output` which map to the corresponding `docker buildx build` / buildkit options. `--output` is restricted compared to its `docker build` counterpart in that it does not allow overriding the `type` and `name` parameters as those must be controlled by porter for builds to be successful.
It also changes default builder selection slightly to use the default builder for the current docker context instead of the builder with the same name as the current context and enables the `docker-container` buildkit driver. By using the `docker-container` build driver instead of the default `docker` driver it is possible to export cache to the repo directly instead of storing it inline in the built image. …
=> Expose more buildkit build options

docs/content/docs/references/file-formats/parameter-set/_index.md
It sets porter 1.3.0 as the first version that supports ParameterSet 1.1.0
=> Update ParameterSet documentation
