cmd/porter/main.go
cmd/porter/mixins.go
cmd/porter/mixins_test.go
docs/config.toml
docs/content/cli.md
docs/themes/porter/layouts/index.html
docs/themes/porter/layouts/partials/header.html
docs/themes/porter/static/src/css/custom.css
pkg/mixin/exec/exec.go
pkg/porter/mixins.go
pkg/porter/mixins_test.go
pkg/printer/json.go
pkg/printer/json_test.go
pkg/printer/printer.go
pkg/printer/printer_test.go
pkg/printer/table.go
pkg/printer/table_test.go

List installed mixins

---

README.md

The website and the readme should explain porter the same way.

Explain porter consistently

---

docs/config.toml
docs/content/architecture-buildtime.md
docs/content/architecture-runtime.md
docs/content/distributing-bundles.md
docs/content/docs.md
docs/content/finding-bundles.md
docs/content/signing-bundles.md
docs/content/using-mixins.md

This adds placeholder pages for missing doc pages with explanations for the content that we need and how to add it.

Add placeholder doc pages

---

docs/content/authoring-bundles.md

Huh, I guess we didn't have an issue for documenting the manifest? 🤷‍♀️ 
Preview at https://deploy-preview-164--porter.netlify.com/authoring-bundles/
Closes #34

Document porter manifest

---

docs/themes/porter/layouts/index.html
docs/themes/porter/layouts/partials/nav.html

Preview at https://deploy-preview-170--porter.netlify.com/

Link to quickstart from landing page

---

cmd/porter/main.go

Resolves https://github.com/deislabs/porter/issues/53

Silence usage help text when cli errors

---

docs/content/porter-or-duffle.md

Add newlines to fix bullet list formatting.

---

azure-pipelines.yml

Having trouble with our brigade cluster after the azure subscription migration so back to pipelines

Re-enable azure pipelines

---

brigade.js

The public Kashti instance has moved to https://brigadecore.github.io/kashti/dashboard

chore(brigade.js): update Kashti build URL

---

build/testdata/bundles/mysql/porter.yaml
build/testdata/bundles/wordpress/porter.yaml
cmd/porter/bundle.go
cmd/porter/bundle_test.go
cmd/porter/main.go
cmd/porter/main_test.go
pkg/cnab/provider/uninstall.go
pkg/config/testdata/bundles/mysql/porter.yaml
pkg/porter/cnab.go
pkg/porter/install.go
pkg/porter/install_test.go
pkg/porter/options.go
pkg/porter/uninstall.go

Implement porter uninstall

---

scripts/install/install-linux.sh

Carolyn can't type but she can open pull requests! 😊 
Closes #247 
cc @nunix

Fix typo in install script

---

pkg/test/helper.go

Closes https://github.com/deislabs/porter/issues/231

feat(pkg/test/helper.go): support multiple expected commands

---

build/testdata/bundles/mysql/porter.yaml
build/testdata/bundles/terraform/porter.yaml
build/testdata/bundles/wordpress/porter.yaml
examples/azure-ark/porter.yaml
examples/azure-mysql-wordpress/porter.yaml
pkg/porter/testdata/paramafest.yaml

Follow-up/cleanup now that https://github.com/deislabs/porter/pull/264 is in.

fix(*): remove last of the source references

---

docs/content/faq.md

preview available at https://deploy-preview-286--porter.netlify.com/faq/#how-does-your-release-naming-scheme-work

Explain release scheme

---

cmd/porter/bundle.go
pkg/cnab/provider/duffle.go
pkg/cnab/provider/install.go
pkg/cnab/provider/uninstall.go
pkg/porter/cnab.go
pkg/porter/install.go
pkg/porter/install_test.go
pkg/porter/uninstall.go

Closes https://github.com/deislabs/porter/issues/252

feat(*): add --driver opt to action commands

---

azure-pipelines.install.yml
azure-pipelines.yml
brigade.js

I've made 2 pipelines, one for testing install scripts (which we don't care if that always passes) and the full CI test suite ending with a publish.

Flip azure devops back on

---

docs/config.toml
docs/content/docs.md
docs/content/faq.md
docs/content/porter-or-duffle.md

* Make it easier to find the page
* Refresh docs
* Summarize at the top and in the FAQ
Preview available at:
* https://deploy-preview-297--porter.netlify.com/faq/
* https://deploy-preview-297--porter.netlify.com/porter-or-duffle/

Improve docs for porter or duffle

---

docs/content/porter-or-duffle.md

Preview available at https://deploy-preview-298--porter.netlify.com/porter-or-duffle/#wordpress-bundle-with-porter

Fix templating on porter-or-duffle page

---

docs/config.toml
docs/content/cli.md

It's not the doc we deserve (#131) but the docs we need or something like that. Batman knows what I'm talking about.

Doc current commands with helptext

---

docs/content/build-image.md
docs/content/docs.md

We switched from name to a list of releases a while ago

Fix helm uninstall docs

---

cmd/exec/install.go
cmd/exec/uninstall.go
cmd/exec/upgrade.go
cmd/porter/mixins.go
pkg/exec/install.go
pkg/exec/uninstall.go
pkg/exec/upgrade.go
pkg/porter/mixins.go
pkg/porter/mixins_test.go

A quick follow-up refactor spurred by https://github.com/deislabs/porter/pull/329

ref(*): remove use of anonymous options where applicable

---

docs/config.toml
docs/content/install.md
docs/content/mixins/_index.md
docs/content/mixins/azure.md
docs/content/mixins/exec.md
docs/content/mixins/helm.md
docs/content/mixins/kubernetes.md
docs/content/mixins/terraform.md
scripts/install/install-linux.sh
scripts/install/install-mac.sh
scripts/install/install-windows.ps1

* Install k8s mixin by default 
* Explain how to install a mixin 
* Document existing mixins (Closes #294)
Preview available at :
* https://deploy-preview-321--porter.netlify.com/install/
* https://deploy-preview-321--porter.netlify.com/mixins/

Moar mixins

---

azure-pipelines.install.yml
scripts/test/test-install.sh

The inline script wasn't stopping on errors, so I'm using
a real bash script. Here's hoping it works better.

Stop on error during install check

---

brigade.js

Refactor to support running a specific check run when handling a `check_run:rerequested` event.

feat(brigade.js): run specific check run on check_run:rerequested event

---

Makefile
cmd/porter/mixins.go
docs/content/install.md

Use CDN URL instead of direct azure storage URL

---

docs/config.toml
docs/content/cli.md

* Adds Bundle List command
* Adjusts formatting for Create and Build commands
Closes https://github.com/deislabs/porter/issues/348

docs(cli.md): add bundle list command

---

README.md
docs/content/faq.md

Added some words about spec compat and linked to CNAB 1.0 milestone

Added some words about spec compatibility

---

brigade.js

- Addresses TODO now that the [upstream fix](https://github.com/brigadecore/brigade/pull/915) is in.
- Fixes indentation.

chore(brigade.js): address/rm TODO around error throw

---

brigade.js

Update the `brigadecore/brigade-github-check-run` image tag to the latest semver release.

chore(brigade.js): update check-run image tag to latest immutable release

---

pkg/porter/build.go
pkg/porter/build_test.go

Adding a WORKDIR statement to the Dockerfile.
Fixes: #388

Adds a WORKDIR statement to Dockerfile.

---

docs/content/slides/pack-your-bags/index.md
docs/themes/porter/layouts/slides/single.html

Preview available at https://deploy-preview-391--porter.netlify.com/pack-your-bags/#author

Workshop: Authoring Bundles

---

docs/content/oci-bundle-format.md
docs/content/slides/pack-your-bags/index.md
examples/aks-spring-music/porter.yaml
examples/azure-ark/porter.yaml
examples/azure-mysql-wordpress/porter.yaml

Adding a little bit to describe the publish process, with some interactivity
This also incidentally updates the examples to have bundle tags.

Adding some tutorial on publishing

---

brigade.js

A smattering of fixes re: recent learnings with @krancour while iterating on similar pipelines in other projects (https://github.com/brigadecore/brigade, https://github.com/brigadecore/kashti, etc.)

fix(brigade.js): misc Promise-related fixes

---

pkg/porter/lifecycle.go
pkg/porter/lifecycle_test.go

I was merging
You were there
Two PR collided
And they could never get install passing again
https://www.youtube.com/watch?v=LEso4_ecR5A

Fix bad merge

---

docs/content/slides/pack-your-bags/index.md

These are extra commands or hacks that I needed using v0.8.1 when running through the workshop exercises.

Fix workshop bugs

---

brigade.js

- Update comments around Docker daemon use
- Fix typo

docs(brigade.js): update/amend a few comments

---

cmd/porter/bundle.go
docs/config.toml
docs/content/cli.md
pkg/porter/outputs.go
pkg/porter/outputs_test.go
pkg/porter/run.go
pkg/porter/show.go
pkg/porter/testdata/outputs/bad-outputs-bundle/bad-output
pkg/porter/testdata/outputs/test-bundle/bar
pkg/porter/testdata/outputs/test-bundle/foo
scripts/test/test-terraform.sh

Closes https://github.com/deislabs/porter/issues/445

feat(*): add bundle outputs commands

---

Gopkg.lock
Gopkg.toml
pkg/cnab/cnab-to-oci/registry.go
vendor/github.com/deislabs/cnab-go/action/action.go
vendor/github.com/deislabs/cnab-go/bundle/definition/schema.go
vendor/github.com/docker/cnab-to-oci/converter/convert.go
vendor/github.com/docker/cnab-to-oci/converter/types.go
vendor/github.com/docker/cnab-to-oci/remotes/fixup.go
vendor/github.com/docker/cnab-to-oci/remotes/mount.go
vendor/github.com/docker/cnab-to-oci/remotes/resolver.go

The latest of docker/cnab-to-oci has a fix for populating the bundle schema version when pulling a bundle from a registry.

Bump cnab to oci

---

pkg/porter/templates/schema.json
pkg/porter/testdata/porter.yaml
pkg/porter/testdata/schema.json

* Updates Porter's manifest schema to add credentials, outputs and parameters and their corresponding definitions
Closes https://github.com/deislabs/porter/issues/449

feat(schema.json): update manifest schema

---

Gopkg.lock
Gopkg.toml
pkg/cnab/config_adapter/adapter.go
pkg/cnab/config_adapter/adapter_test.go
pkg/cnab/provider/duffle.go
pkg/cnab/provider/install.go
pkg/cnab/provider/invoke.go
pkg/cnab/provider/parameters.go
pkg/cnab/provider/uninstall.go
pkg/cnab/provider/upgrade.go
pkg/config/manifest.go
pkg/outputs/outputs.go
pkg/outputs/outputs_test.go
pkg/porter/outputs.go
pkg/porter/outputs_test.go
pkg/porter/run.go
pkg/porter/run_test.go
pkg/porter/show.go
pkg/porter/show_test.go
vendor/github.com/deislabs/cnab-go/action/action.go
vendor/github.com/deislabs/cnab-go/bundle/bundle.go
vendor/github.com/deislabs/cnab-go/bundle/parameters.go
vendor/github.com/deislabs/cnab-go/claim/claim.go
vendor/github.com/deislabs/cnab-go/driver/command/command.go
vendor/github.com/deislabs/cnab-go/driver/command/command_nix.go
vendor/github.com/deislabs/cnab-go/driver/command/command_windows.go
vendor/github.com/deislabs/cnab-go/driver/docker/docker.go
vendor/github.com/deislabs/cnab-go/driver/driver.go
vendor/github.com/deislabs/cnab-go/driver/kubernetes/kubernetes.go

- adds logic to add/update outputs after an action to a bundle claim
- includes a bit of refactoring to simplify/reduce duplication
TODO
Closes https://github.com/deislabs/porter/issues/457

feat(*): add outputs to a bundle claim

---

docs/content/slides/pack-your-bags/index.md
docs/themes/porter/static/src/css/slides.css

Preview @ https://deploy-preview-479--porter.netlify.com/pack-your-bags

Devops Days MSP workshop slides

---

docs/content/slides/pack-your-bags-msp/index.md
docs/themes/porter/static/src/css/slides.css

These are available at /pack-your-bags-msp

Slides for DevOps Days MSP Workshop

---

docs/content/build-image.md
docs/content/slides/pack-your-bags-msp/index.md
docs/content/slides/pack-your-bags/index.md
workshop/porter-tf/azure/README.md

* cnab is .cnab now
* Fix storage account name to not use special chars

Workshop tweaks

---

scripts/install/install-linux.sh
scripts/install/install-mac.sh
scripts/install/install-windows.ps1

After this is merged, I'll test on canary then do another release to beta.2

Install the terraform mixin by default

---

docs/config.toml
docs/content/mixins/_index.md
docs/content/mixins/aws.md

Doc is at https://porter.sh/mixins/aws

Document the aws mixin

---

cmd/kubernetes/invoke.go
cmd/kubernetes/main.go
cmd/kubernetes/uninstall.go
pkg/exec/schema/exec.json
pkg/exec/testdata/schema.json
pkg/kubernetes/execute.go
pkg/kubernetes/execute_test.go
pkg/kubernetes/schema/kubernetes.json
pkg/kubernetes/schema_test.go
pkg/kubernetes/testdata/invoke-input.yaml
pkg/kubernetes/testdata/schema.json
pkg/porter/schema.go
pkg/porter/templates/schema.json
pkg/porter/testdata/schema.json

* Fix Porter schema merge to use patternProperties for custom actions 
* Support custom actions in the kubernetes mixin 
* Fix exec schema to use pattern properties for custom action

Fix custom action schema

---

workshop/porter-tf-aci/azure/app/Dockerfile
workshop/porter-tf-aci/azure/app/main.go
workshop/porter-tf-aci/azure/bundle/porter.yaml
workshop/porter-tf/azure/porter.yaml

* Add a bundle output to porter-tf and porter-tf-aci
* Update the update/uninstall steps to not print anything
* Updated porter-tf-aci to deploy a trivial webapp to ACI
Still need to update the porter-tf-aci README so people can use it.

Update the workshop examples:

---

docs/content/mixins/gcloud.md

Updated doc is at https://porter.sh/mixins/gcloud

Document outputs for gcloud mixin

---

Makefile
azure-pipelines.yml
brigade.js
examples/aks-spring-music/cnab/app/Dockerfile.base

Passing validation depends on getting Porter's cnab-go use (and resulting generated bundle.json files) up to spec in https://github.com/deislabs/porter/pull/505
Closes https://github.com/deislabs/porter/issues/423

feat(ci): add bundle validation

---

brigade.js

Fixes https://github.com/deislabs/porter/issues/522

fix(brigade.js): fetch ajv for publishExamples job

---

docs/content/mixins/exec.md

Preview at https://deploy-preview-527--porter.netlify.com/mixins/exec/#faq

exec faq: how do I use pipes?

---

docs/content/install.md

SHIP IT WHILE IT'S HOT, @squillace 🐦 
Preview available at https://deploy-preview-552--porter.netlify.com/install/

Spell out how to install a canary build

---

docs/config.toml
docs/content/mixins/_index.md
docs/content/mixins/az.md

* Sort cloud mixins in alphabetical order

Add az mixin to docs

---

CONTRIBUTING.md
REVIEWING.md

Update contributing guide and create a reviewing guide.

Lay out the welcome mat

---

.github/pull_request_template.md
CONTRIBUTING.md

* Add a PR template
* Explain what to run locally before you push

Explain what to put in a pull request

---

CONTRIBUTING.md
REVIEWING.md

Explain the roles and how to achieve them

Define the project roles

---

README.md
docs/content/contribute.md
docs/content/resources.md
docs/themes/porter/layouts/index.html

Add a landing page to send someone who is interested in contributing to the project.
Preview at https://deploy-preview-627--porter.netlify.com/contribute/
N/A
There may be some overlap with the contributing guide. I think that's okay. This is for people coming into the funnel of awesome. The guide is the final answer but is a bit overwhelming because it answers many questions about lots of stuff, and I wanted to focus on the top questions someone judging the project would have.

Contributing Landing Page

---

docs/config.toml

Fix the image displayed on the twitter card.

Fix twitter card image

---

docs/content/mixins/az.md

This documents the new mixin configuration for the `az` mixin available in v0.3.0-beta.1
Preview available at https://deploy-preview-633--porter.netlify.com/mixins/az/
Related to #621 
None

Document az mixin configuration

---

examples/aks-spring-music/.gitignore
examples/azure-ark/.gitignore
examples/azure-ark/cnab/app/run
examples/azure-mysql-wordpress/.gitignore
examples/azure-tf-example/.gitignore
workshop/asciiart/.gitignore
workshop/azure-cli/.gitignore
workshop/etcd-operator/.gitignore
workshop/gcloud-compute/.gitignore
workshop/hello-llama/.gitignore
workshop/porter-tf-aci/azure/bundle/.gitignore
workshop/porter-tf/azure/.gitignore
workshop/wordpress/.gitignore

Updates cnab dir in `.gitignore` files where applicable; adds missing `.gitignore` files.
N/A
N/A

chore(*): s/cnab/.cnab in applicable .gitignore files

---

build/azure-pipelines.pr-automatic.yml
build/azure-pipelines.pr-manual.yml
build/azure-pipelines.setup-go-workspace.sh

Run the parts of the CI build in parallel.
Closes #641 
* I'm going to run a bunch of tests on this PR first before assigning it for review.
* We should squash when we merge.
* Are we cool with how jobs are reported back to the PR? Is this a good level of granularity or too much?
* I am going to do the release pipeline in a separate PR so that I can test it in a sandbox.

Use parallel jobs for CI build

---

Gopkg.lock
Gopkg.toml
pkg/cnab/provider/parameters.go
pkg/manifest/runtime-manifest.go
vendor/github.com/deislabs/cnab-go/driver/docker/docker.go
vendor/github.com/deislabs/cnab-go/driver/kubernetes/kubernetes.go
vendor/github.com/deislabs/cnab-go/packager/import.go

Bumps our `deislabs/cnab-go` dep to latest release and addresses a few `TODO`s to use added upstream logic.
N/A
N/A

chore(Gopkg.toml): bump cnab-go dep; update some usage

---

CONTRIBUTING.md
Makefile

* Explain which makefile targets to use to help avoid packr problems in a PR.
* Add text to verify-vendor to tell people what to do when it fails in a PR so they can fix it.
N/A
N/A

Add tips for packr to contributing

---

cmd/kubernetes/main.go

`s/kuberetes/kubernetes`
N/A
N/A

fix(cmd/kubernetes/main.go): fix typo

---

build/azure-pipelines.release.yml

Fixes the release pipeline. The binaries were missing the templates. 
Closes #737

Fix the release pipeline, make templates exist again

---

docs/content/install.md

Give more explicit instructions on how to change the URL to install a specific version.
This is just a dummy PR to help me test releases

Explain how to install a specific version

---

docs/config.toml
docs/content/authoring-bundles.md
docs/content/best-practices/gke.md
docs/content/custom-dockerfile.md
docs/content/faq.md

Document how to use a custom dockerfile
N/A
Should have written this 6 months ago...

Document custom dockerfiles

---

pkg/porter/dependencies.go

These debug lines were accidentally checked in

Remove debug lines from dependencies

---

pkg/porter/testdata/porter.yaml
pkg/porter/testdata/schema.json
pkg/templates/templates/schema.json

Updates the JSON schema to model `images`
Closes #784

Update the JSON schema to handle images

---

docs/content/install.md

Link to the Porter VS Code extension from our install page.
https://deploy-preview-805--porter.netlify.com/install/
N/A
⭐️

Link to the vscode extension

---

docs/content/wiring.md

OCD on fire seeing small typo/grammar issues.
Just updated the docs - no changes to code or user XP
Closes nothing.
_If there is not an existing issue, please make sure we have context on why this change is needed. Just a doc change. No existing issue for this specifically.

typo/grammar fixes in 'Outputs' section

---

Makefile

Minor simplification of looping logic in the Makefile
N/A
N/A

ref(Makefile): simplify loop

---

CONTRIBUTING.md
infra/cdn.md

- Adds a section in `CONTRIBUTING.md` around infrastructure
- Adds a document around Porter's current CDN setup
😅 
🤘 🐀

docs(*): add CDN doc; link in CONTRIBUTING.md

---

docs/content/resources.md

Add our CNCF webinar from last year to the resources page.
My guilt
None, I'm gonna merge sans review 😈

Add CNAB webinar to resources page

---

docs/content/cli/plugins_uninstall.md

I fixed the doc but forgot to rerun make build locally so I missed a file...
Hubris
🙇‍♀️ Will self-merge after the release is done

Sync docs for plugin uninstall

---

cmd/porter/credentials.go
docs/content/cli/credentials.md
docs/content/cli/credentials_delete.md
docs/content/cli/credentials_generate.md
docs/content/cli/plugins_uninstall.md
pkg/porter/credentials.go
pkg/porter/credentials_test.go
pkg/storage/in-memory/store.go

Add command to delete credentials
Closes #854

feat(creds): Add delete credentials command

---

cmd/porter/credentials.go

Delete unused porter credentials add stub command
Closes #891

remove function creating credential add command

---

docs/content/wiring.md

Amends some wording to the file param section per feedback in https://github.com/deislabs/porter/pull/912
N/A
N/A

docs(wiring.md): amendments to file param section

---

go.mod
go.sum

This is the exact same code as before, but is tagged version on cnab-go instead of my fork now that it's all merged and stable.
N/A
🙇‍♀

Use cnab-go v0.9.0-beta1

---

docs/content/compatible-registries.md

I have verified that the Digital Ocean container registry beta works with porter and cnab-to-oci. 🎉 
https://deploy-preview-933--porter.netlify.com/compatible-registries/
Updates an empty cell in our magic grid of compatibility
```console
$ porter publish
Pushing CNAB invocation image...
The push refers to repository [registry.digitalocean.com/getporter/porter-hello-installer]
abeb5afa8643: Preparing
b71ccb040bbb: Preparing
9bbd554374b6: Preparing
47cdccbcf1a0: Preparing
13d2047f5c7d: Preparing
badfbcebf7f8: Preparing
badfbcebf7f8: Waiting
abeb5afa8643: Pushed
9bbd554374b6: Pushed
13d2047f5c7d: Pushed
badfbcebf7f8: Pushed
b71ccb040bbb: Pushed
47cdccbcf1a0: Pushed
0.1.0: digest: sha256:1a717acd67bc312e2f85f76e25ab1579d3199f9ff12a982fbad97d3ac1dd7c94 size: 1579
Rewriting CNAB bundle.json... …
```

Digital Ocean works with cnab-to-oci and porter

---

cmd/porter/credentials.go
docs/content/cli/credentials.md
docs/content/cli/credentials_edit.md
pkg/credentials/credentialProvider.go
pkg/credentials/credentialStorage.go
pkg/credentials/credentialStorage_test.go
pkg/editor/editor.go
pkg/editor/editor_nix.go
pkg/editor/editor_windows.go
pkg/porter/credentials.go
pkg/porter/credentials_test.go
pkg/porter/editor.go

Adds `porter credentials edit` command allowing the user to edit their credentials.
#890

feat(creds): Add edit credentials command

---

docs/static/_redirects

Add short easy to remember links for some of our external resources such as twitter, or our slack channel.
My poor memory
I will follow up with links to these resources from our website and README.

Add shortcut links for external resources

---

.github/ISSUE_TEMPLATE/feature_request.md
.github/ISSUE_TEMPLATE/question.md

* Add feature request template
* Add question template

Add issue templates for features and questions

---

Makefile

* Updates the schema URLs to pull from https://cnab.io
N/A
N/A

ci(Makefile): update schema URL to use cnab.io

---

.github/pull_request_template.md

Add the porter.yaml schema to the PR checklist
We keep breaking the schema... Let's add it to the checklist to help update the schema in the same PR that affects it.
I've removed, "doc not impacted" because not checking the box essentially means that.

Add porter.yaml schema to PR checklist

---

pkg/cnab/extensions/schema/io-cnab-docker.schema.json
pkg/porter/testdata/schema.json
pkg/templates/templates/schema.json

Follow-up to #977 per https://github.com/deislabs/porter/pull/977#discussion_r406858862
N/A
N/A

feat(schema.json): update required extension section of porter manifest schema

---

examples/README.md
examples/docker/.dockerignore
examples/docker/.gitignore
examples/docker/Dockerfile.tmpl
examples/docker/README.md
examples/docker/helpers.sh
examples/docker/porter.yaml

Add an example bundle that uses docker.
Follow-up to #951
🐳

Add an example docker bundle

---

examples/docker/porter.yaml

It was repeating "Install Hello World" which is confusing
Printing the same description for both install and invoke actions.
🐳

Fix description for whalesay invoke action

---

pkg/credentialsgenerator/generator.go

Fixes duplicate question while up/down-ing, while surveying
Partial prevents problem mentioned at #398 . But doesn't completely fix it
I couldn't resist adding extra space after question

🐛 Fix duplicate question while up/down-ing, while surveying

---

examples/airgap/charts/whalegap/templates/deployment.yaml

The message parameter wasn't being passed from the chart values on the deployment.
None, came up during a demo.
😱

Fix setting message parameter

---

docs/content/install.md
scripts/install/install-linux.sh
scripts/install/install-mac.sh
scripts/install/install-windows.ps1

This changes the instructions given at the end of the install script to tell the user how to add porter to their path. 
Closes #1081

fixes to install scripts for path set up

---

pkg/cnab/extensions/solver.go
pkg/cnab/extensions/solver_test.go

Fix a bug in how we parse references to bundle dependencies by switching from parsing based on the presence of a colon to using the docker references library instead, which properly handles ports in the registry domain.
Note that we don't fully support dependencies in thick bundles as mentioned in the original issue. This only addresses the parsing problem. Follow #554 for a solution to that gap.
Closes #1097
None

Parse dependency references using docker library

---

docs/themes/porter/layouts/_default/section.html

The template was assuming a paginator, but our template doesn't use one, so print all pages. This fixes https://porter.sh/cli/
Preview of the fixed page https://deploy-preview-1104--porter.netlify.app/cli/
N/A

List all pags in a section

---

build/azure-pipelines.pr-automatic.yml
build/azure-pipelines.pr-manual.yml

* Trigger PR builds on any branch, instead of only main or a release branch. This lets us use feature branches for larger changes we are holding back until they are ready.
I had originally targeted `dev` with a similar change (see  #1107). After discussing with @vdice we aren't going to use gitflow, so I'm going to delete dev and go with this fix instead.
NA
Gonna kick some builds against this to make sure it works

Trigger PR builds on any branch

---

docs/content/contribute.md

* Incorporate feedback on how we link to issue labels
* Link to list of mixins and mixin ideas
* Offer mentoring
* Link to quickstart
Preview at https://deploy-preview-1121--porter.netlify.app/contribute/
N/A
🍫

Refresh contribute page

---

docs/static/_redirects

* Link to the hackmd agenda/minutes
* Link to a dedicated zoom meeting
Discussion in July 13th dev call
None

Add permalinks for the dev meeting

---

Makefile
go.sum
pkg/kubernetes/execute_test.go
pkg/kubernetes/install.go
pkg/kubernetes/install_test.go
pkg/kubernetes/schema.go
pkg/kubernetes/schema/kubernetes.json
pkg/kubernetes/schema_test.go
pkg/kubernetes/uninstall.go
pkg/kubernetes/uninstall_test.go

Add `--context` arg to the schema 
Closes #1141
- These changes were made with `go version go1.14.4 darwin/amd64`. where I am having some unstable issues not related to changes made. Please wait until I confirm the environment behavior

Porter#1141

---

pkg/exec/builder/execute.go
pkg/exec/builder/execute_test.go

This change adds an option for mixin commands to put arguments at the end of the command in addition to the current functionality of adding arguments at the beginning.
This change was needed for the docker mixin in order to have some arguments come at the end of the command such as the path for docker build which comes after all the optional flags. 
- docker build -t tag -f file path ARGUMENTS --FLAGS

Added suffix arguments to mixin executableStep

---

go.mod
go.sum

Stop using the fork, Luke. 
NA
NA

Bump cnab-go to v0.13.2

---

docs/content/configuration.md

* debug-plugins should be defined under flags
* Remove stray codefence
Noticed while reading doc page
Let's make sure to review the netlify page instead of just the markdown. Oops! 😊 

Fix formatting of configuration page

---

docs/content/cli/installations_delete.md
docs/content/cli/installations_show.md
docs/content/cli/show.md

* Adds doc updates to the cli pages (generation missed in PR #1189 😬 )
n/a
n/a

docs(cli): missed doc updates from PR #1189

---

examples/azure-terraform/README.md
examples/azure-terraform/arm/storage.json
examples/azure-terraform/helpers.sh
examples/azure-terraform/porter.yaml

* Updates the Azure Terraform example bundle to harness Porter's ability to persist outputs across actions
Depends on https://github.com/deislabs/porter/pull/1205 (or similar)

ref(examples): update azure terraform bundle

---

go.sum

Sync go.sum. I thought I was working off of a short-lived cnab-go branch but turns out it will live longer than the porter branch that I started from... So this will end up in go.sum forever. ☠️ 
A modified go.sum after doing a build
Sorry about not doing this in my PR!

Sync go.sum

---

pkg/storage/manager.go

Fix the message printed when a credential is migrated
Forgot the word schema from the message! >.<;
NA

Fix migrate credential log message

---

OWNERS.md

Add OWNERS file because that CNCF wants one BECAUSE WE GOT INTO THE CNCF! 🥳 
None, but transparency is great. This explains what is in our GH teams.
The important part is that your name is in the file. I made up what area you like to help with. You may want to edit what I wrote!

Add OWNERS file

---

docs/content/author-bundles.md
docs/content/dependencies.md

* Updates the dependency doc to mention required fields and ordering (now that https://github.com/deislabs/porter/pull/1170 is in 🎉 )
n/a
n/a

docs(dependencies.md): mention ordering

---

docs/static/_redirects

* updates applicable links in the netlify _redirects file
Ref https://github.com/getporter/porter/issues/1249
n/a

chore(_redirects): update links where applicable

---

.github/workflows/assign-issues.yaml

* updates the assign-issues GH action to point to the new board location
Ref https://github.com/getporter/porter/issues/1249
n/a

chore(.github): update assign-issues action

---

docs/content/community.md
docs/static/_redirects

Add redirect links to the calendar, forum, and devstats. Link to the new forum on our community page.
https://deploy-preview-1289--porter.netlify.app/community/
N/A
N/A

Add redirect links

---

.github/CODEOWNERS

This adds Jennifer Davis as a codeowner for our website content. She will be automatically requested for reviews when any of these files are changed.
N/A
N/A

Add Jennifer as codeowner for website content

---

docs/content/mixin-dev-guide/commands.md
docs/static/_redirects

Based on the Q&A from #1327 this updates the schema documentation to bring it up-to-date and include extra tips that were provided in the forum.
I'm also adding a src shortcut for other porter repos so that we can be consistent about source code links.
NA
NA

Improve mixin dev guide for schema command

---

CONTRIBUTORS.md

Signed-off-by: nhcarrigan <nhcarrigan@gmail.com>
As requested, adds my name to the `CONTRIBUTORS.md` file. 🙂 
If this is your first pull request, please add your name to the bottom of our [Contributors][contributors] list. Thank you …

Add myself to contributors.md

---

docs/content/best-practices/kind.md

* Updates a section in the KinD doc to clarify current supported options
In response to a question posted in https://github.com/getporter/porter/discussions/1366
N/A

docs(kind.md): clarify host networking option

---

docs/content/learning.md

Add my talk about bundle use cases to our learning page.
NA
NA

Link to bundle use cases talk

---

magefile.go

It sometimes takes a longer time for docker to start depending on if this is the first run on this agent before or not. I have updated the scripts for our agents to start docker once before we allow jobs to be run on it. This should fix most timeouts, because the first time docker desktop is started, it downloads a big wsl distro. But just to be safe, I've bumped the timeout before each job as well.
I have also changed how docker runs as a service through the magic of [Non-Sucking Service Manager](https://nssm.cc/usage). It seems to be doing well so far.
NA
NA

Wait 3 minutes for Docker service to start

---

docs/content/mixins/az.md

Sync changes from https://github.com/getporter/az-mixin/pull/26 to the az mixin documentation.
NA
NA

Sync az mixin doc

---

docs/content/blog/ci-flags.md

Explain the major changes in the release around build and publish
N/A
N/A

Release notes for v0.31.0

---

Makefile
docs/static/_redirects
mixin.mk

This puts in the necessary redirects and cache settings to use Netlify for our CDN. After this is live, I'll update DNS.

Support switching our CDN to Netlify

---

Makefile
mixin.mk

I'm seeing really slow downloads through the Netlify proxy, so trying to get it to cache responses for a bit.

Cache volatile assets for 5minutes

---

Makefile
mixin.mk

Fix max-age header

---

cmd/porter/bundle.go
docs/content/cli/publish.md

I cannot change that I transpose letters when I type. I can only accept that I am human and submit very short PRs when it is pointed out to me. 😂 
Reported on slack.
N/A

Fix typo on publish page

---

docs/content/learning.md
docs/static/_redirects

Add a shortlink porter.sh/videos that redirects to our youtube channel. Also link to it from our Learning page.
N/A
N/A

Link to our new youtube channel

---

build/azure-pipelines.release-template.yml

My last PR #1496 lost this commit because I suck at git.
I managed to push the branch to both this repo and my fork and then Azure Pipelines tested the branch in this repo, while the PR that merged was my fork's branch (which was missing a commit). THERE IS NO WINNING ONLY PAIN.

Fix pool references

---

build/images/client/Dockerfile

Includes the kubernetes plugin in the porter docker image

Add the kubernetes plugin to container

---

build/git_askpass.sh
mage/releases/publish.go

* Don't require every repo to have an askpass script
* Handle both mixins and plugins

Fix mixin publish

---

docs/static/_redirects

After this I'll remove the publish step from the packages repo.

Redirect package indexes

---

README.md

Link directly to our new adopters issue so that people can say that they are using Porter without making a PR themselves.

Link to adopters issue from readme

---

CONTRIBUTORS.md
pkg/build/doc.go
pkg/build/provider/doc.go
pkg/cache/doc.go
pkg/claims/doc.go
pkg/cnab/cnab-to-oci/doc.go
pkg/cnab/config-adapter/doc.go
pkg/cnab/doc.go
pkg/cnab/extensions/doc.go
pkg/cnab/provider/doc.go
pkg/config/datastore/doc.go
pkg/config/doc.go
pkg/context/doc.go
pkg/credentials/doc.go
pkg/doc.go
pkg/docs/doc.go
pkg/exec/builder/doc.go
pkg/exec/doc.go
pkg/secrets/pluginstore/doc.go
pkg/storage/pluginstore/doc.go

Hi, new contributor here 👋
This PR removes import comments over the porter codebase. They are not needed anymore since we use go.mod.
Closes #1285 

Remove all import comments

---

CONTRIBUTORS.md
docs/content/plugins/kubernetes.md

Added Doc for Integration of Porter with Kubernetes, using Kubernetes Plugin on Plugin Page.
Closes #1591 

Listed the Kubernetes Plugin on Plugin Page

---

docs/content/mixins/helm2.md
docs/content/mixins/helm3.md

* Rename the existing helm mixin page to /mixins/helm2 and indicate it is only for Helm v2.
* Add a /mixins/helm3/ page for mchorfa's mixin which is the recommended mixin.
* Redirect /mixins/helm/ to /mixins/helm3/
https://deploy-preview-1652--porter.netlify.app/mixins/helm2/
https://deploy-preview-1652--porter.netlify.app/mixins/helm3/
Part of #1395

Document helm3 mixin

---

docs/content/blog/helm-mixin-rename.md

Announce the helm -> helm2 rename and tell people to upgrade to helm3.

Blog: Helm v2 rename

---

CONTRIBUTORS.md

As suggested by @carolynvs here https://github.com/getporter/docker-mixin/pull/36#issuecomment-884998904, thanks !

doc(contributor): update the contributors file.

---

docs/content/faq.md

Faq ,question added 
just added , a new FAQ
- [.] Documentation

faq.md updated

---

ADOPTERS.md

https://github.com/getporter/porter/issues/1596#issuecomment-900534824
WOOOOOOOOOO! 🐱🎉

Add Thinktecture AG to the adopters list

---

pkg/storage/plugins/mongodb_docker/store.go

This fixes a problem I kept having when trying to run tests locally. When the docker container for mongo was stopped (in my case because I ran out of disk space), we weren't removing the container before starting a new one.
I know that before we ship v1 we need to switch to using the docker library instead of calling the docker binary directly but this at least fixes the logic until we can do that.
My poor machine doesn't have enough space. PLZ SEND MOAR TB!

Remove stopped mongo

---

build/azure-pipelines.integration.yml
build/azure-pipelines.pr-automatic.yml

Syncs the #1750 change to the v1 branch too.

Bump CI environment variables on v1 branch

---

magefile.go

When we build the example bundles, they rely on some mixins being installed on the CI machine. In a recent PR #1759, I updated an example to use the helm3 mixin since the old helm mixin is deprecated. I forgot to update the mixins installed in CI, so the example mixin build is failing.
This should fix that.

Install the helm3 mixin on CI machine

---

pkg/cnab/extensions/parameter_sources.go

Remove debug print statement

---

docs/content/blog/helm3-updates.md

Explain the latest release and why Porter moved to it immediately.
https://deploy-preview-1777--porter.netlify.app/blog/helm3-updates/

Blog about the helm3 v0.1.14 mixin release

---

docs/content/mixins/helm3.md

update helm3 mixin documentation to the latest release

---

docs/content/contribute/tutorial.md

Fix contribution tutorial.
N/A

docs: fix command in contrib tutorial

---

CONTRIBUTING.md
CONTRIBUTORS.md

remove accidental packr word from contribution guide
Context - https://cloud-native.slack.com/archives/CN8NA4F8V/p1637076713084400?thread_ts=1637076443.083800&cid=CN8NA4F8V
N/A

Doc packr word fix

---

.github/pull_request_template.md

* Clarify the checklist items for the author
* Add checklist items for the reviewer
I keep forgetting to run some manual tests before merging then regret my life choices.
Anything else that we should prompt people about?

Update PR checklists

---

README.md
pkg/cnab/cnab-to-oci/registry.go

* Only push the current invocation image tag https://github.com/getporter/porter/pull/1903
* Link to user survey on README https://github.com/getporter/porter/pull/1894
N/A
N/A

Sync main into v1

---

docs/content/install.md

* Update the hard-coded version in the example commands
* Copy over improvements from the main website in our links and wording that was missed when I synced main into v1.
N/A
N/A

Update install prerelease instructions

---

docs/content/faq.md

Some sub headings didn't read quite right. I think this reads a little better.
This updates the FAQ.

Fix up sub heading

---

CODE_OF_CONDUCT.md
CONTRIBUTING.md
CONTRIBUTION_LADDER.md
CONTRIBUTORS.md
README.md
REVIEWING.md

This will fix some typos and update the docs.
Closes #1914 

Fix typos in docs

---

.github/workflows/close-issues.yaml

Revert #1927 because the github action is old and doesn't support pull_request_target. I'll either fork it or get a patch accepted upstream with support for that trigger type.
N/A
N/A

Revert "Merge pull request #1927 from carolynvs/fix-close-issue-action"

---

docs/static/_redirects

add redirect for schema files
Closes #1887 

docs: add redirect for schema

---

pkg/version.go
pkg/version_test.go

This PR improves the uniqueness of porter's user agent, so it's easier to parse it out.
Closes https://github.com/getporter/az-mixin/issues/38

pkg/version: make user-agent more unique

---

CODE_OF_CONDUCT.md
CONTRIBUTING.md
CONTRIBUTION_LADDER.md
CONTRIBUTORS.md
README.md
REVIEWING.md
scripts/install/install-linux.sh
scripts/install/install-mac.sh

* Remove +x from install scripts https://github.com/getporter/porter/pull/1967
* docs: add redirect for schema https://github.com/getporter/porter/pull/1943
* Fix typos in docs https://github.com/getporter/porter/pull/1915
N/A
N/A

Sync main into release/v1

---

ADOPTERS.md

This adds F5 to Porter's adopters list! 🎉
Thank you @bdegeeter and @steven-gettys for all your work making this happen.

Add F5 to adopters list

---

build/azure-pipelines.integration.yml
build/azure-pipelines.pr-automatic.yml
build/azure-pipelines.release-template.yml
go.mod
go.sum
magefile.go

update go version to 1.18
Closes #1989 

Update to go 1.18

---

.github/workflows/close-issues.yaml

L's and I's look the same in some fonts... 🤦‍♀️

Fix typo of close issues gh action

---

docs/content/parameters.md
docs/content/plugins/types/_index.md
docs/content/quickstart/parameters.md
docs/content/reference/file-formats.md

add documentation for storing sensitive data into secret store

---

CONTRIBUTING.md
docs/content/contribute/_index.md
docs/content/project/short-links.md
docs/static/_redirects

https://getporter.org/find-issue redirects to a search of the getporter org for any issues labeled with "help wanted" or "good first issue"
Tricking people into working on our backlog 😂 
This needs to also be cherry-picked to release/v1 too.

Add shortlink to find an issue to work on

---

CONTRIBUTORS.md
docs/content/contribute/_index.md

Signed-off-by: Hrittik Roy <67012359+hrittikhere@users.noreply.github.com>
Fixes a Typo at `_index.md`
Adds Hrittik to Contributor
N/A

Edit index.md for Typo 

---

docs/content/compatible-registries.md

Signed-off-by: Hrittik Roy <67012359+hrittikhere@users.noreply.github.com>
Added an entry for GitLab now that we have verified that they are not supported.
Closes https://github.com/getporter/porter/issues/1932

Add GitLab to Registries

---

docs/content/plugins/kubernetes.md

Update doc file for the kubernetes plugins update
Part of https://github.com/getporter/porter/issues/1027 …

update kubernetes-plugins doc

---

docs/content/examples/hello.md
docs/content/quickstart/credentials.md

Fixes a couple small typos I noticed while going through the Quickstart guide

Fix two small typos in docs

---

tests/tester/main.go

When we run commands in our smoke and integration tests, sometimes it
would help to be able to set an environment variable for just that
command (so the test can still run in parallel), or to change the
directory for a single command.
This exposes the underlying PreparedCommand object that builds the
porter command so that a caller can set extra environment variables,
change the working directory, etc.

Support customizing the test porter command

---

OWNERS
OWNERS.md

Add Yingrong to OWNERS

---

build/azure-pipelines.integration.yml
build/azure-pipelines.pr-automatic.yml

Our PR build and our release build (for the main and v1 branches) have drifted a bit. I'm copying changes over from the release build to our PR build:
* Do not run the integration tests when it's a doc only change
* Run vet and lint

Sync CI changes to the PR build

---

docs/themes/porter/assets/sass/docs-footer.scss

Closes #2192
Link: https://deploy-preview-2227--porter.netlify.app/

Removes Invert Filter from CNCF Logo

---

OWNERS.md

Add Yingrong to OWNERS.md. They are already there on our release/v1 branch, this just copies that change to main.

Sync changes to OWNERS.md

---

docs/content/blog/new-template-delimiter.md

Announce the new template delimiter and explain how to update your bundle.
Preview at https://deploy-preview-2260--porter.netlify.app/blog/new-template-delimiter/
Part of #316 
🛑 Do not merge until we release v1.0.0-beta.2 so that the blog post goes out at the same time.

Blog: New template delimiter

---

pkg/porter/lint.go
pkg/porter/lint_test.go
pkg/porter/testdata/lint/success.txt

With this PR, `porter bundle lint` will print a success message upon successful linting
Closes #2237

Add linter success message

---

CONTRIBUTING.md
REVIEWING.md

Add steps for how to do a porter release into the contributing guide 

add docs for release process

---

CONTRIBUTING.md
infra/custom-windows-ci-agent.md

These are my notes from how I set up the windows agent that we use to run tests and whatnot on Windows in our build pipeline, mainly running the smoke tests on windows.
They aren't complete but it gets the notes off of my computer. The commands have been scrubbed for any sensitive data.
N/A
N/A

Notes for windows agent configuration

---

docs/content/quickstart/credentials.md

Proof once again that I cannot type

Fix typo in credentials quickstart

---

docs/content/install.md
docs/content/plugins/mongodb-docker.md

Document how to do a clean installation
Fixes #2311 

Document how to do a clean install

---

docs/content/plugins/mongodb.md

This explains how to customize the cosmos connection string so that it works with the mongodb driver.
N/A

Document how to use cosmos with the mongodb plugin

---

README.md

The badge counts the number of help wanted and good first issues that are open and unassigned.
Closes #1635 

Add help wanted badge to readme

---

docs/config.toml
docs/content/quickstart/desired-state.md

Link to the create a bundle task under the quickstart so that the flow of what to do next as someone is learning Porter moves from end-user into bundle-author scenarios.
https://deploy-preview-2381--porter.netlify.app/bundle/create/

Quickstart: create a bundle

---

docs/themes/porter/layouts/index.html

* Remove the underline on the word together since it's not displaying correctly at some sizes
* Remove uppercase words from the title
* Add back my favorite emoji in place of the underline
Fixes #2305

Remove underline on the website title word together

---

docs/content/blog/v1-is-here.md
docs/content/security-features.md

This announces Porter's v1 release, covering what is porter, new features, and our roadmap going forward.
https://deploy-preview-2389--porter.netlify.app/blog/v1-is-here/

Announce v1

---

pkg/tracing/traceLogger.go

When we panic inside a span, right now you only end up seeing the panic message, e.g. EOF, but not the associated stack trace. Because we also recover in main, we get a stack trace on the main function, but it would be much more helpful to get the stack on the originating span.
I've updated our recover in EndSpan so that we record the stack trace when a traced function panics. Eventually we won't need the last resort recover in main, but we aren't quite there yet so the panic is double logged.
N/A

Include stack traces when we recover a panic in EndSpan

---

CONTRIBUTORS.md
docs/content/learning.md
docs/content/quickstart/credentials.md
docs/content/quickstart/desired-state.md

Signed-off-by: chengweg <chengweg@andrew.cmu.edu>
fix typo in quickstart documents
Closes https://github.com/getporter/porter/issues/2550

fix typo in quickstart documents

---

build/azure-pipelines.integration.yml
build/azure-pipelines.pr-automatic.yml
build/azure-pipelines.release-template.yml
netlify.toml

Update to the most recently patched version of Go 1.19
N/A
Trying to stay ahead of the IronBank security alerts

Use Go 1.19.6

---

CONTRIBUTING.md

adding an alternative site launch option

adding an alternative site launch option

---

netlify.toml

Closes #https://github.com/getporter/porter/issues/2575 …

fix not loading fonts

---

.gitignore

Closes https://github.com/getporter/porter/issues/2587

add hugo lock to gitignore

---

docs/themes/porter/layouts/index.html

Closes https://github.com/getporter/porter/issues/2595

update current year

---

docs/themes/porter/layouts/partials/docs-sidebar.html
netlify.toml

Closes https://github.com/getporter/porter/issues/2598

update website hugo

---

docs/themes/porter/assets/sass/docs-footer.scss

Closes https://github.com/getporter/porter/issues/2630

fix cncf img on mobile

---

ADOPTERS.md

Include notes about how Microsoft is using bundles to distribute bundles on Azure Marketplace, and create environments for Azure TRE.

Update Microsoft usage in adopters.md

---

docs/themes/porter/layouts/partials/docs-sidebar.html
docs/themes/porter/static/css/custom.css

More details in issue
Closes https://github.com/getporter/porter/issues/2640

Accessibility fix list

---

CONTRIBUTORS.md
cmd/porter/tag_docs.go
mage.go
magefile.go
pkg/agent/agent_test.go
pkg/editor/editor_nix.go
pkg/editor/editor_windows.go
pkg/mixin/pkgmgmt_integration_test.go
pkg/pkgmgmt/client/runner_integration_test.go
pkg/pkgmgmt/pkgmgmt_nix.go
pkg/pkgmgmt/pkgmgmt_windows.go
pkg/plugins/pluggable/loader_nix.go
pkg/plugins/pluggable/loader_windows.go
pkg/porter/build_integration_test.go
pkg/porter/lifecycle_integration_test.go
tests/integration/driver_test.go
tests/integration/install_test.go
tests/integration/invoke_test.go
tests/integration/outputs_test.go
tests/integration/pull_test.go
tests/integration/sensitive_data_test.go
tests/integration/suppress_output_test.go

Remove all "// +build" tags

---

docs/themes/porter/assets/sass/helm-blog.scss

Closes https://github.com/getporter/porter/issues/2717 …

fix content on mobile

---

docs/themes/porter/assets/sass/helm-blog.scss
docs/themes/porter/layouts/partials/tags.html

Closes https://github.com/getporter/porter/issues/2721 …

fix tags render on mobile

---

build/azure-pipelines.integration.yml
build/azure-pipelines.pr-automatic.yml
build/azure-pipelines.release-template.yml
netlify.toml

Build with the most recent patch release for Go 1.19. Earlier versions have vulnerabilities that are being [flagged](https://repo1.dso.mil/dsop/opensource/getporter/porter-agent/-/issues/37) in IronBank.
Ensures that our porter-agent image in IronBank does not have any vulnerabilities reported.
N/A

Build with GO 1.19.8

---

CONTRIBUTING.md
netlify.toml

Closes https://github.com/getporter/porter/issues/2739 …

update website hugo to latest version

---

CONTRIBUTING.md
netlify.toml

Closes https://github.com/getporter/porter/issues/2770 …

update hugo to v0.112.7

---

CONTRIBUTING.md
netlify.toml

Closes https://github.com/getporter/porter/issues/2777

update hugo to v0.113.0

---

CONTRIBUTING.md
netlify.toml

Closes https://github.com/getporter/porter/issues/2793 …

update hugo to v0.114.1

---

CONTRIBUTORS.md

adding name in contributors list

---

CONTRIBUTING.md
netlify.toml

Closes https://github.com/getporter/porter/issues/2805 …

update hugo to v0.115.2

---

docs/themes/porter/layouts/partials/nav.html

Closes https://github.com/getporter/porter/issues/2821 …

fix learning link

---

docs/themes/porter/assets/sass/helm-blog.scss

Closes https://github.com/getporter/porter/issues/2844 …

update blog page

---

CONTRIBUTING.md
netlify.toml

Closes https://github.com/getporter/porter/issues/2826 …

update hugo to v0.115.4

---

tests/integration/build_test.go
tests/integration/testdata/bundles/exec-outputs/Dockerfile.tmpl

bug: fix jq url in image 

---

.github/CODEOWNERS

Update porter CODEOWNERS

---

CONTRIBUTING.md
CONTRIBUTORS.md
README.md
docs/content/blog/2023-roadmap.md
docs/content/blog/cncf.md
docs/content/blog/v1-roadmap.md
docs/content/community.md
docs/content/docs/contribute/tutorial.md
docs/content/docs/contribute/work-with-us.md
docs/content/docs/learn/_index.md
docs/content/slides/cnab-unpacked/index.md

I fixed some broken links that lead to 404 not found page. I hope this helps.
Broken links
This is my first PR, please let me know if any changes needed. Thanks.

fix broken links

---

docs/content/docs/references/logo.md
docs/content/slides/pack-your-bags-msp/index.md
docs/content/slides/pack-your-bags/index.md

update content folder links

---

docs/content/docs/getting-started/create-bundle.md

This issue fixes create-bundle.md as per as per https://github.com/getporter/porter/pull/2790
Closes #2799 
I have looked at all the comments. I would want to revisit the following comments once and see if any changes should be made to the PR based on the corresponding discussions. The other changes were straightforward. 
cc: @schristoff @bdegeeter 

Update: Made changes to update bundle documentation

---

docs/i18n/en.yaml

resolve https://github.com/getporter/porter/issues/2959

update current date

---

.github/workflows/porter-integration.yml

Fix indent to see if integration test show up in the pipeline

 ix indent in porter-int-yaml

---

.github/workflows/build_pipelinesrelease_template.yml
.github/workflows/porter-release.yml

Use GitHub Actions and not ADO.

---

.github/workflows/build_pipelinesrelease_template.yml

Remove {{.vars}}  

---

CONTRIBUTORS.md
magefile.go

Removed lines 682-683 which causes the isssue no such file or directory

---

.github/workflows/porter-canary.yml
.github/workflows/test-porter-release.yml

Addressing some syntax errors in the github actions and testing the current PR workflow.

chore: add description to gh actions workflow inputs

---

.github/workflows/porter-release.yml

The publish step keeps skipping itself, unsure if it's because I'm skipping the tests, so we're just going to force the tests to test.

(bug): publish step isnt publishing

---

docs/assets/css/custom.css

resolve https://github.com/getporter/porter/issues/3066

fix iframe video on mobile

---

docs/go.mod
docs/go.sum

Closes https://github.com/getporter/porter/issues/3056

update porter site to hextra v0.7.3

---

SECURITY.md
SECURITY_CONTACTS.md
embargo-policy.md

(chore): Add security documentation

---

docs/layouts/index.html

resolve https://github.com/getporter/porter/issues/3070

Accessibility add link name to Cloud Native image

---

docs/layouts/index.html

resolve https://github.com/getporter/porter/issues/3078

fix cncf logo on mobile

---

OWNERS.md

Add Kim Christensen to the list of maintainers

Update maintainer list

---

.github/workflows/trivy.yaml
go.mod
go.sum

Update magefile dependency to calculate release tag and branch name correctly in Github Actions

Update magefile dependency

---

.github/CODEOWNERS

Add kichristensen as code owner

Add kichristensen as code owner

---

mage/docs/docs.go
pkg/build/dockerfile-generator_test.go
pkg/cache/cache_test.go
pkg/cnab/config-adapter/stamp.go
pkg/config/config.go
pkg/config/helpers.go
pkg/config/loader.go
pkg/editor/editor.go
pkg/exec/builder/errors.go
pkg/exec/version_test.go
pkg/pkgmgmt/client/install.go
pkg/pkgmgmt/client/runner.go
pkg/pkgmgmt/feed/generate_test.go
pkg/plugins/pluggable/connection.go
pkg/portercontext/context_test.go
pkg/runtime/runtime_manifest.go
pkg/runtime/runtime_manifest_test.go
pkg/storage/plugins/mongodb/mongodb.go
pkg/storage/plugins/mongodb/mongodb_test.go
pkg/test/helper.go
workshop/porter-tf-aci/azure/app/main.go

(chore): Appease GolangLintCI in steps

---

pkg/build/dockerfile-generator_test.go
pkg/portercontext/context.go
tests/integration/build_test.go
tests/integration/invoke_test.go
tests/integration/migration_test.go
tests/integration/publish_test.go
tests/smoke/hello_test.go

Fix integration tests broken after #3005.

Fix integration tests broken after #3005

---

CONTRIBUTORS.md
pkg/runtime/runtime_manifest.go

fix: close state file

---

.github/workflows/build_pipelinesrelease_template.yml

Publishes the Porter server images as part of the release workflow
Closes #3137
The actual push to the registry haven't been tested because of missing permissions

Publish Porter server images

---

go.mod
go.sum

Updated google container registry version to solve archive issue on windows.
Closes #2917

Bumped container registry version

---

CONTRIBUTORS.md

Recommended in [getporter/porter#3182](https://github.com/getporter/porter/pull/3182):
> [Thank you so much! Please don't forget to add your name to the contributors file!](https://github.com/getporter/porter/pull/3182#issuecomment-2223669935)

Update CONTRIBUTORS.md for #3182

---

pkg/porter/packages_test.go

This test is dependent on the description of the Azure Plugin, that have changed.

Fix package search test

---

.github/CODEOWNERS

Update owners to use the Github team

Update CODEOWNERS to use the Github team
